

```{r setup}

library(nimble)
library(here)
library(dplyr)
library(lubridate)
library(reshape2)
library(ggplot2)
library(IPMbook)
library(popbio)
library(foreach) 
library(doParallel) 

source(here::here('scripts', 'PlotTheme.R'))

#returns precision matrix weights
iar.Q <- function (n, p, return_nimble=TRUE){
  if (n < 2 * p)
    stop("n must be >= 2*p\n")
  tmp1 <- out <- matrix(0, n, n)
  tmp2 <- ((-1)^c(0:p)) * choose(p, c(0:p))
  for (i in (p + 1):n) {
    tmp1[, i] <- c(rep(0, i - p - 1), tmp2, rep(0, n - i))
  }
  for (i in n:(p + 1)) {
    tmp4 <- tmp1[, c(1:n)[tmp1[i, ] != 0]]
    tmp5 <- tmp1[i, tmp1[i, ] != 0]
    tmp6 <- t(t(tmp4) * tmp5)
    tmp6[i, ] <- 0
    out[i, ] <- -rowSums(tmp6)
  }
  out[1:p, ] <- out[n:(n - p + 1), n:1]
  out <- diag(apply(out, 1, sum)) - out
  if(!return_nimble){
    return(out)
  } else{
    A <- -out; diag(A) <- 0
    num <- rowSums(out!=0)-1
    adj <- unlist(apply(A, 1, function(v){which(v!=0)})) 
    w <- unlist(apply(A, 1, function(v)v[which(v!=0)]))
    r <- nrow(out)-sum(zapsmall(eigen(out)$values)!=0)
    return(
      list(L=length(adj), num=num, weights=w, adj=adj, c=r)
    )
  }
}


```

```{r MR load data}

#capture histories
ch_fem <- read.csv(here::here('data', 'ProcData','ch_fem.csv'),
                   header = T, stringsAsFactors = F) %>%
  transform(Sex = ifelse(Sex == 'FALSE', 'F', NA)) %>%
  transform(reg_0b = as.numeric(factor(reg_0, levels = c("C GULF", "E ALEU", "E GULF",
                                                        "W GULF", "C ALEU", "W ALEU")))) %>%
  transform(reg_0c = as.numeric(factor(reg_0c, levels = c('East', 'West'))))
ch_male <- read.csv(here::here('data', 'ProcData', 'ch_m.csv'),
                    header = T, stringsAsFactors = F) %>%
  transform(reg_0b = as.numeric(factor(reg_0, levels = c("C GULF", "E ALEU", "E GULF",
                                                        "W GULF", "C ALEU", "W ALEU")))) %>%
  transform(reg_0c = as.numeric(factor(reg_0c, levels = c('East', 'West'))))

#number of times females seen per year
resights <- read.csv(here::here('data', 'ProcData', 'num_resight.csv'),
                     header = T, stringsAsFactors = F) 

## variables and dimensions
n_occasions <- dim(ch_fem)[2]-7 #subtract id columns
res_mat <- as.matrix(resights[,2:dim(resights)[2]]) #1: 1-2 resights, 2: 3-8, 3: 9+, 4: ND

## rough estimate of effort
eff <- c(rep(1, 18))[1:18]
eff[c(6,17,18)] <- 2 #less effort in 2006, 2017-2018 (no field camps)

mass_f <- ch_fem$Mass_std
mass_m <- ch_male$Mass_std
reg_f <- ch_fem$reg_0b #levels = C GULF E ALEU E GULF
reg_m <- ch_male$reg_0b
reg_fb <- ch_fem$reg_0c #levels = east, west
reg_mb <- ch_male$reg_0c

#### informed priors
#from K.Hastings et al. (2018)
# https://figshare.com/articles/journal_contribution/Supplemental_Table_S3_Age-_and_sex-specific_survival_probabilities_S_of_Steller_sea_lions_in_southeastern_Alaska_by_natal_rookery_from_Survival_of_adult_Steller_sea_lions_in_Alaska_senescence_annual_variation_and_covariation_with_male_reproductive_success/5769219?backTo=/collections/Supplementary_material_from_Survival_of_adult_Steller_sea_lions_in_Alaska_senescence_annual_variation_and_covariation_with_male_reproductive_success_/3971808
# K. Hastings, Kelly; A. Jemison, Lauri; W. Pendleton, Grey (2018): Supplemental Table S3. Age- and sex-specific survival probabilities of Steller sea lions in southeastern Alaska by natal rookery. from Survival of adult Steller sea lions in Alaska: senescence, annual variation and covariation with male reproductive success.. The Royal Society. Journal contribution. https://doi.org/10.6084/m9.figshare.5769219.v2 

dem_ests <- read.csv(file = here::here('data', 'ProcData', 'dem.rates.eDPS.csv'),
                     header = T, stringsAsFactors = F) %>%
  # filter(Rookery == 'Forrester') #just pick one of the four rookeries
  group_by(Age, Sex) %>%
  dplyr::summarize(med = mean(med), lower = mean(lower), upper = mean(upper), .groups = 'keep')
 
phi_ests <- dem_ests %>% 
  group_by(Sex, Age) %>%
  dplyr::summarize(med = mean(med), lower = mean(lower), 
                   upper = mean(upper), .groups = 'keep') %>% #mean of adult ages
  transform(sd = (upper-lower)/4) %>%
  transform(Age = factor(Age, levels = c('P', '1', '2', '3', '4', '5', 'A'))) %>%
  arrange(Sex, Age) %>% dplyr::select(med, sd)

#table for manuscript
prior_tab <- dem_ests %>%
  transform(sd = (upper-lower)/4) %>% 
  transform(Age = factor(Age, levels = c('P', '1', '2', '3', '4', '5', 'A'))) %>%
  dplyr::select(Age, Sex, med, sd)

#approximately gauged from Alexey's draft manuscript and figure
psi_ests <- data.frame(med = c(0.2, 0.6, 0.4, 0.8, 0.5),
                       sd = c(0.01, 0.01, 0.1, 0.05, 0.1))

```

```{r aerial survey NEW agTrend modeled count data}

#after discussion with Tom, Katie, Devin Feb 2023
###count data
np_raw <- read.csv(here::here('Data', 'wdpsnp_count_region_2022.csv'), 
                     header = T, stringsAsFactors = F) %>%
  filter(year > 1999) #%>%
  # transform(se.real = ifelse(se.real < 2, 2, se.real))

np_reg_med <- np_raw %>%
  group_by(year, region) %>%
  dplyr::rename(n_np = est.pred) %>%
  # transform(region = factor(region, levels = c('C GULF', 'E ALEU', 'E GULF',
  #                                              'W GULF', 'C ALEU', 'W ALEU'))) %>%
  reshape2::dcast(year ~ region, value.var = 'n_np') %>% dplyr::select(-year)

# np_reg_sd <- np_raw %>%
#   group_by(year, region) %>%
#   transform(region = factor(region, levels = c('C GULF', 'E ALEU', 'E GULF',
#                                                'W GULF', 'C ALEU', 'W ALEU'))) %>%
#   reshape2::dcast(year ~ region, value.var = 'se.real') %>% dplyr::select(-year)
  
#pups
pups_raw <- read.csv(here::here('Data', 'wdpspup_count_region_2022.csv'), 
                     header = T, stringsAsFactors = F) %>%
  filter(year > 1999) #%>%
  #if surveyed == 0, adopt pred, but this is built-in already
  # transform(median.fill = ifelse(surveyed == 0, est.pred, est.real),
  #           low.fill = ifelse(surveyed == 0, ci.pred.lower, ci.real.lower),
  #           high.fill = ifelse(surveyed == 0, ci.pred.upper, ci.real.upper)) %>%
  # transform(sd = (high.fill-low.fill)/4) %>%
  # transform(se.real = ifelse(se.real < 2, 2, se.real))

pups_reg_med <- pups_raw %>%
  group_by(year, region) %>%
  dplyr::rename(n_pup = est.pred) %>%
  # transform(region = factor(region, levels = c('C GULF', 'E ALEU', 'E GULF',
  #                                              'W GULF', 'C ALEU', 'W ALEU'))) %>%
  reshape2::dcast(year ~ region, value.var = 'n_pup') %>% dplyr::select(-year)

# pups_reg_sd <- pups_raw %>%
#   group_by(year, region) %>%
#   transform(region = factor(region, levels = c('C GULF', 'E ALEU', 'E GULF',
#                                                'W GULF', 'C ALEU', 'W ALEU'))) %>%
#   reshape2::dcast(year ~ region, value.var = 'se.real') %>% dplyr::select(-year)

#pups
ggplot(pups_raw, 
       aes(x = year, y = est.pred, group = region, color = region)) +
  geom_point(position = position_dodge(0.5)) + geom_line(position = position_dodge(0.5)) +
  geom_errorbar(aes(x = year, ymin = ci.real.lower, ymax = ci.real.upper), position = position_dodge(0.5)) +
  ylab('Number of pups') +
  scale_color_manual(values = rainbow2[-c(1,4)]) +
  plot_theme(panel.border = element_rect(fill = NA), legend.position = 'top')

#non-pups
ggplot(np_raw, 
       aes(x = year, y = est.pred, group = region, color = region)) +
  geom_point(position = position_dodge(0.5)) + geom_line(position = position_dodge(0.5)) +
  geom_errorbar(aes(x = year, ymin = ci.real.lower, ymax = ci.real.upper), position = position_dodge(0.5)) +
  ylab('Number of non-pups') +
  scale_color_manual(values = rainbow2[-c(1,4)]) +
  plot_theme(panel.border = element_rect(fill = NA), legend.position = 'top')

###Nmin and pup multiplier approaches

#Nmin from combined pup and np counts
Nmin <- pups_raw %>% dplyr::select(region, year, est.pred) %>%
  transform(type = 'pup') %>%
  bind_rows(np_raw %>% dplyr::select(region, year, est.pred) %>%
              transform(type = 'np')) %>%
  reshape2::dcast(region + year ~ type, value.var = 'est.pred') %>%
  transform(Nmin = np+pup)

ggplot(Nmin, aes(year, Nmin)) +
  geom_line() + geom_point() +
  facet_wrap(~region) +
  plot_theme()

Nmin_lambda_mean <- array(NA, dim = c(6, n_occasions-1+4)) #add 4 bc has data up through 2022
years <- 2000:2022
nyears.burnin <- 0
regs <- c('E GULF', 'C GULF', 'W GULF', 'E ALEU', 'C ALEU', 'W ALEU')
for (r in 1:6) {
  for (t in (nyears.burnin+2):(n_occasions+nyears.burnin+4)) {
  Nmin_lambda_mean[r,(t-nyears.burnin-1)] <- Nmin[Nmin$region == regs[r] &
                               Nmin$year == (years[t]), 'Nmin']/
        Nmin[Nmin$region == regs[r] &
                    Nmin$year == (years[t]-1), 'Nmin']
  }
}

Nmin_lambda_reg <- data.frame(reg = regs,
                              est = c(apply(Nmin_lambda_mean, 1, mean)))
write.csv(Nmin_lambda_reg, file = here::here('data', 'Nmin_lambda_2022.csv'), row.names = F)

Nmin_range <- Nmin %>% dplyr::select(-c(np,pup)) %>%
  transform(region = gsub(' ', '', region)) %>%
  reshape2::dcast(year ~ region, value.var = 'Nmin') %>%
  transform(tot = EGULF+CGULF+WGULF+EALEU+CALEU+WALEU) %>%
  dplyr::select(year, tot)

Nmin_lambda_range <- numeric()
for (t in (nyears.burnin+2):(n_occasions+nyears.burnin+4)) {
  Nmin_lambda_range[(t-nyears.burnin-1)] <- Nmin_range[Nmin_range$year == (years[t]), 'tot']/
        Nmin_range[Nmin_range$year == (years[t]-1), 'tot']
}

#mean over study period -- for figure
exp(mean(log(Nmin_lambda_range)))

#lambda from agTrend output (pups * 4.5)
agTrend_ests <- pups_raw %>% dplyr::select(region, year, est.pred) %>%
  transform(abund_ind = est.pred*4.5)

# ggplot(agTrend_ests, aes(year, est.pred)) +
#   geom_line() + geom_point() +
#   facet_wrap(~region) +
#   plot_theme()

agTrend_lambda_mean <- array(NA, dim = c(6, n_occasions-1+4))
years <- 2000:2022
nyears.burnin <- 0
regs <- c('E GULF', 'C GULF', 'W GULF', 'E ALEU', 'C ALEU', 'W ALEU')
for (r in 1:6) {
  for (t in (nyears.burnin+2):(n_occasions+nyears.burnin+4)) { #add 4 bc has data up through 2022
  agTrend_lambda_mean[r,(t-nyears.burnin-1)] <- agTrend_ests[agTrend_ests$region == regs[r] &
                               agTrend_ests$year == (years[t]), 'abund_ind']/
        agTrend_ests[agTrend_ests$region == regs[r] &
                    agTrend_ests$year == (years[t]-1), 'abund_ind']
  }
}

agTrend_lambda_reg <- data.frame(reg = regs,
                              est = c(apply(agTrend_lambda_mean, 1, mean)))
write.csv(agTrend_lambda_reg, file = here::here('data', 'agTrend_lambda_2022.csv'), row.names = F)

#rangewide for dashed line on figure
agTrend_range <- agTrend_ests %>%
  transform(region = gsub(' ', '', region)) %>%
  reshape2::dcast(year ~ region, value.var = 'abund_ind') %>%
  transform(tot = EGULF+CGULF+WGULF+EALEU+CALEU+WALEU) %>%
  dplyr::select(year, tot)

agTrend_lambda_range <- numeric()
for (t in (nyears.burnin+2):(n_occasions+nyears.burnin+4)) {
  agTrend_lambda_range[(t-nyears.burnin-1)] <- agTrend_range[agTrend_range$year == (years[t]), 'tot']/
        agTrend_range[agTrend_range$year == (years[t]-1), 'tot']
}

#mean over study period -- for figure
exp(mean(log(agTrend_lambda_range)))

```


```{r ocean covariates}

#adjusted year is the phi period (adj year == 1 is pups born in 2000 surviving to 2001)
#fall and summer adj_year 0 == NA (would be Sept-Dec 1999)
#spring and winter adj_year 18 == NA (would be Jan-May 2018, for pups born in 2017)
#if want to study lag time (pups born in June 2000 strongly affected by mom's forage availability in winter 1999-2000 rather than first solo foraging winter 2000-2001), get June-Dec 1999 data exclude 1999 and 2019, just want up through May/Spring of 2018 for pups born in 2017

#range-wide
ocean_SSL <- read.csv(here::here('data', 'ProcData', 'ocean_all_adj_east.csv'), 
                      stringsAsFactors = F, header = T) %>%
  filter(adj_year > 0 & adj_year < 19) 

#adj_year 1 = survival from 2000 to 2001; 18 = survival from 2017 to 2018
start <- 1; stop <- 18
seas <- 'NB'
# seas <- 'spr'
seas <- 'sum'
# seas <- 'fall'
# seas <- 'win'

albsa <- as.numeric(scale(eval(parse(text = paste0('ocean_SSL$ALBSA_', seas, '[', start,':', stop,']')))))
PDO <- as.numeric(scale(eval(parse(text = paste0('ocean_SSL$PDO_', seas, '[', start,':', stop,']')))))
AOI <- as.numeric(scale(eval(parse(text = paste0('ocean_SSL$AOI_', seas, '[', start,':', stop,']')))))
upwell <- as.numeric(scale(eval(parse(text = paste0('ocean_SSL$upwell_', seas, '[', start,':', stop,']')))))
chla <- as.numeric(scale(eval(parse(text = paste0('ocean_SSL$chla_', seas, '[', start,':', stop,']')))))
sst <- as.numeric(scale(eval(parse(text = paste0('ocean_SSL$sst_', seas, '[', start,':', stop,']')))))
vwnd <- as.numeric(scale(eval(parse(text = paste0('ocean_SSL$vwnd_', seas, '[', start,':', stop,']')))))
uwnd <- as.numeric(scale(eval(parse(text = paste0('ocean_SSL$uwnd_', seas, '[', start,':', stop,']')))))
NOI <- as.numeric(scale(eval(parse(text = paste0('ocean_SSL$NOI_', seas, '[', start,':', stop,']')))))
prod <- as.numeric(scale(eval(parse(text = paste0('ocean_SSL$prod_', seas, '[', start,':', stop,']')))))
scal <- as.numeric(scale(eval(parse(text = paste0('ocean_SSL$scalar_', seas, '[', start,':', stop,']')))))
npgo <- eval(parse(text = paste0('ocean_SSL$NPGO_', seas, '[', start,':', stop,']')))

# fix NA values
albsa[is.na(albsa)] <- 0
PDO[is.na(PDO)] <- 0
AOI[is.na(AOI)] <- 0
upwell[is.na(upwell)] <- 0
npgo[is.na(npgo)] <- 0
chla[is.na(chla)] <- 0
sst[is.na(sst)] <- 0
vwnd[is.na(vwnd)] <- 0
uwnd[is.na(uwnd)] <- 0
prod[is.na(prod)] <- 0
NOI[is.na(NOI)] <- 0
scal[is.na(scal)] <- 0

### To examine correlations
# library(Hmisc)
# 
# ## single season - all variables
# flattenCorrMatrix <- function(cormat, pmat) {
#   ut <- upper.tri(cormat)
#   data.frame(
#     row = rownames(cormat)[row(cormat)[ut]],
#     column = rownames(cormat)[col(cormat)[ut]],
#     cor  =(cormat)[ut],
#     p = pmat[ut]
#   )
# }
# cor <- rcorr(as.matrix(ocean_SSL[,grepl('win', colnames(ocean_SSL))]))
# cor_vals <- flattenCorrMatrix(cor$r, cor$P) %>% arrange(cor)
# corrplot(cor$r, type = "lower", order = "original", p.mat = cor$P,
#          insig = "blank", sig.level = 0.01, tl.col = "black", tl.cex = .9, number.cex = .2)
# 
# #strongly correlated variables
# #NB: PDO-MEI/NOI/NPI, albsa-NPI
# # spring: PDO-NOI/NPI/SST, albsa-curl, NPI-up, sst-MEI
# #summer: MEI-PDO/NPGO, albsa-NPI, AOI-NPI, MEI-NOI
# #fall: NOI-PDO, PDO-MEI, NOI-MEI, AOI-albsa
# #winter: NPI-albsa, MEI-albsa, MEI-PDO, uwnd-PDO, curl-albsa, curl-chla


```

```{r fc inits}

##female
#first capture
get.first <- function(x) min(which(x == 1)) #pups only
fc <- apply(ch_fem[,-c(1:7)], 1, get.first)

ch <- ch_fem[,-c(1:7)]
for (i in 1:dim(ch)[1]) {
  if(fc[i] > 1) {ch[i, 1:(fc[i]-1)] <- NA }
}

y <- as.matrix(ch)

# Initial values for possible states
# "NA" for the latent state at all places before an individual was observed, 
# if t > fc & t <= fc + 3, then init = t-fc
# if t = fc + 4, then ind is 4yr, init = either 5 or 7
# if t = fc + 5, then ind is 5yr, init = either 6, 8, 10
# if t >= fc + 6, then ind is 6yr, init = either 9 or 10

cjs.me.init <- function(ch, fc){
  inits <- ch    #initialize with observations up until states diverge from observations (4yr olds)
  for(i in 1:dim(ch)[1]) { 
    inits[i,fc[i]] <- NA #pups at release
      if(n_occasions-fc[i]>=1){   
        inits[i,(fc[i] + 1)] <- 2} #1 yr old
      if(n_occasions-fc[i]>=2){
        inits[i,(fc[i] + 2)] <- 3}  #2 yr old
      if(n_occasions-fc[i]>=3){
        inits[i,(fc[i] + 3)] <- 4} #3 yr old
      if(n_occasions-fc[i]>=4) {
        inits[i,(fc[i] + 4)] <- 7} #all 4yrs are (pre-)breeders
      if(n_occasions-fc[i]>=5) {
        inits[i,(fc[i] + 5)] <- 8} #all 5yrs are breeders
      if(n_occasions-fc[i]>=6) {
        inits[i,((fc[i] + 6):n_occasions)] <- 9} #all 6yrs+ are breeders
  } #i
  return(inits)
}

z.init = as.matrix(cjs.me.init(ch, fc))
#if giving latent z.st as data, change z.init in these ways:
z.init[which(y < 5)] <- NA #all obs pre-breeders are known state, so don't estimate
z.init[which(y == 6)] <- NA  #all obs w pup are known state, don't estimate
z.init[which(y == 8)] <- NA
z.init[which(y == 10)] <- NA

#want NAs where we're estimating, except state == 1 since that is set in the model
z.st <- as.matrix(ch)
z.st[which(z.st == 1)] <- NA
z.st[which(z.st == 11)] <- NA #all ND are unknown state
z.st[which(z.st == 5)] <- NA  #all obs w/o pup are unknown state, otherwise state can be obs equivalent
z.st[which(z.st == 7)] <- NA
z.st[which(z.st == 9)] <- NA
z.st[which(z.st == 6)] <- 7 #obs of 6 is state 7
z.st[which(z.st == 10)] <- 9 #obs of 10 is state 9; obs of 8 is state 8 leave as is

get.first.m <- function(x) min(which(x != 8)) #include animals branded as non-pups
fc_m <- apply(ch_male[,-c(1:7)], 1, get.first.m)

ch_m <- ch_male[,-c(1:7)]
for (i in 1:dim(ch_m)[1]) {
  if(fc_m[i] > 1) {ch_m[i, 1:(fc_m[i]-1)] <- NA } #everything NA before first capture
}

ym <- as.matrix(ch_m)

cjs.me.init.m <- function(ch, fc) {
    inits <- ch    #initialize with observations up until states diverge from observations (4yr olds)
    for(i in 1:dim(ch)[1]) { 
    inits[i,fc[i]] <- NA #pups at release
      if(n_occasions-fc[i]>=1){    
        inits[i,(fc[i] + 1)] <- 2} #1 yr old
      if(n_occasions-fc[i]>=2){
        inits[i,(fc[i] + 2)] <- 3}  #2 yr old
      if(n_occasions-fc[i]>=3){
        inits[i,(fc[i] + 3)] <- 4} #3 yr old
      if(n_occasions-fc[i]>=4) {
        inits[i,(fc[i] + 4)] <- 5} #4 yr old
      if(n_occasions-fc[i]>=5) {
        inits[i,(fc[i] + 5)] <- 6} #5 yr olds
     if(n_occasions-fc[i]>=6) {
        inits[i,((fc[i] + 6):n_occasions)] <- 7} #start all adult age animals at 7
  } #i
  return(inits)
}

z.init.m = as.matrix(cjs.me.init.m(ch_m, fc_m))
#if giving latent z.st as data, change z.init in these ways:
z.init.m[which(ym == 1)] <- NA
z.init.m[which(ym == 2)] <- NA
z.init.m[which(ym == 3)] <- NA
z.init.m[which(ym == 4)] <- NA
z.init.m[which(ym == 5)] <- NA
z.init.m[which(ym == 6)] <- NA
z.init.m[which(ym == 7)] <- NA

#known latent state
z.st.m <- as.matrix(ch_m)

get.first.B <- function(x) min(which(x == 7))
fb <- apply(ch_male[,-c(1:7)], 1, get.first.B) #inf warnings for animals never seen as an adult
get.last.B <- function(x) max(which(x == 7)) 
lb <- apply(ch_male[,-c(1:7)], 1, get.last.B)

#want NAs where we're estimating, except state == 1 since that is set in the model
z.st.m[which(z.st.m == 1)] <- NA
z.st.m[which(z.st.m == 8)] <- NA #not detected

#breeder between breeding observations
for (i in 1:dim(z.st.m)[1]) {
  if (fb[i] != Inf) {
    z.st.m[i, (fb[i]:lb[i])] <- 7
  }
}

z.init.m[which(z.st.m == 7)] <- NA #need to get the between-breeder observations for inits too, not just all == 7

## recapture summary stats for manuscript ##
#i=1 lots of resights
#i=6 single resight
#i=2 no resights
# capt <- numeric()
# for (i in 1:dim(ch)[1]) {
#   capt[i] <- as.numeric(sum(ch[i,(fc[i]+1):n_occasions]<11)<1) #will be TRUE for inds never recapt
# }
# 
# #capt==1 for inds never resighted; 553/1322 == 41%
# sum(capt>0)/length(capt)
# 
# capt_m <- numeric()
# for (i in 1:dim(ch_m)[1]) {
#   capt_m[i] <- as.numeric(sum(ch_m[i,(fc_m[i]+1):n_occasions]<8)<1) #will be TRUE for inds never recapt
# }
# 
# #capt==1 for inds never resighted; 622/1330 == 47%
# sum(capt_m>0)/length(capt_m)
# 
# ## distribution of resights for females
# res_actual <- read.csv(here::here('SSL_CJS', 'Data', 'resights_actual.csv'), 
#                        header = T, stringsAsFactors = F)
# res_actual <- res_actual[,2:(n_occasions+1)]
# 
# capt_freq <- capt_sd <- numeric()
# for (i in 1:dim(res_actual)[1]) { 
# 
#   cols <- which(res_actual[i,]!=0)
#   capt_freq[i] <- mean(as.numeric(res_actual[i,cols[which(cols>fc[i])]])) #average per ind across yrs
#   capt_sd[i] <- sd(as.numeric(res_actual[i,cols[which(cols>fc[i])]])) #variability across yrs
# }

#individuals recaptured an average of 6 times per year
# capt_freq_avg <- mean(capt_freq, na.rm = T)
# #variability in recaptures across individuals: 7.1
# capt_sd_avg <- sd(capt_freq, na.rm = T) 

```

```{r stable age discrete uniform}

###??### cleanup notes
#I think this is the right code that is needed? pasted from archive 2/2023
### stable age code
## Females and males
ests <- data.frame(phiP = 0.6, phi1 = 0.7, phi2 = 0.8, phi3 = 0.92, phi4 = 0.95, phi5 = 0.95,
                   phiB = 0.95, phiNB = 0.8, psi3 = 0.15, psi4 = 0.75, psi5 = 0.15,
                   psiB = 0.9, psiNB = 0.3,
                   phiPM = 0.6, phi1M = 0.7, phi2M = 0.75, phi3M = 0.92, phi4M = 0.9,
                   phi5M = 0.9, phiBM = 0.85)

les_mat <- matrix(0, nrow = 15, ncol = 15)

les_mat[1,4] <- (ests$phi3*(ests$psi3))/2
les_mat[1,5] <- (ests$phi4*(ests$psi4))/2
les_mat[1,6] <- (ests$phi5*(ests$psi5))/2
les_mat[1,7] <- (ests$phiB*(ests$psiB))/2
les_mat[1,8] <- (ests$phiNB*(ests$psiNB))/2
les_mat[2,1] <- ests$phiP
les_mat[3,2] <- ests$phi1
les_mat[4,3] <- ests$phi2
les_mat[5,4] <- ests$phi3*(1-ests$psi3)
les_mat[6,5] <- ests$phi4*(1-ests$psi4)
les_mat[7,4] <- ests$phi3*(ests$psi3)
les_mat[7,5] <- ests$phi4*(ests$psi4)
les_mat[7,6] <- ests$phi5*(ests$psi5)
les_mat[7,7] <- ests$phiB*(ests$psiB)
les_mat[7,8] <- ests$phiNB*(ests$psiNB)
les_mat[8,6] <- ests$phi5*(1-ests$psi5)
les_mat[8,7] <- ests$phiB*(1-ests$psiB)
les_mat[8,8] <- ests$phiNB*(1-ests$psiNB)
les_mat[9,4] <- (ests$phi3*(ests$psi3))/2
les_mat[9,5] <- (ests$phi4*(ests$psi4))/2
les_mat[9,6] <- (ests$phi5*(ests$psi5))/2
les_mat[9,7] <- (ests$phiB*(ests$psiB))/2
les_mat[9,8] <- (ests$phiNB*(ests$psiNB))/2
les_mat[10,9] <- ests$phiPM
les_mat[11,10] <- ests$phi1M
les_mat[12,11] <- ests$phi2M
les_mat[13,12] <- ests$phi3M
les_mat[14,13] <- ests$phi4M
les_mat[15,14] <- ests$phi5M
les_mat[15,15] <- ests$phiBM

# ea <- demogR::eigen.analysis(les_mat)
ea <- popbio::eigen.analysis(les_mat)
stable <- ea$stable.stage

stableAge <- stable[1:8]/sum(stable[1:8])
stableAgeM <- stable[9:15]/sum(stable[9:15])

###??### #end cleanup notes

#for pups
v1 <- dUnif(c(pups_reg_med[1,1]/2*0.9, pups_reg_med[1,2]/2*0.9,
                                  pups_reg_med[1,3]/2*0.9, pups_reg_med[1,4]/2*0.9,
                                  pups_reg_med[1,5]/2*0.9, pups_reg_med[1,6]/2*0.9), 
                c(pups_reg_med[1,1]/2*1.1, pups_reg_med[1,2]/2*1.1,
                                  pups_reg_med[1,3]/2*1.1, pups_reg_med[1,4]/2*1.1,
                                  pups_reg_med[1,5]/2*1.1, pups_reg_med[1,6]/2*1.1))
len_v1 <- dim(v1)[2]

# breeders
vB <- dUnif(c(pups_reg_med[1,1]/2*0.75, pups_reg_med[1,2]/2*0.75,
                                  pups_reg_med[1,3]/2*0.75, pups_reg_med[1,4]/2*0.75,
                                  pups_reg_med[1,5]/2*0.75, pups_reg_med[1,6]/2*0.75), 
                c(pups_reg_med[1,1]/2*1.25, pups_reg_med[1,2]/2*1.25,
                                  pups_reg_med[1,3]/2*1.25, pups_reg_med[1,4]/2*1.25,
                                  pups_reg_med[1,5]/2*1.25, pups_reg_med[1,6]/2*1.25))
len_vB <- dim(vB)[2]

#ages
v2 <- dUnif(c(np_reg_med[1,1]/2*0.75*stableAge[2], np_reg_med[1,2]/2*0.75*stableAge[2],
                                  np_reg_med[1,3]/2*0.75*stableAge[2], np_reg_med[1,4]/2*0.75*stableAge[2],
                                  np_reg_med[1,5]/2*0.75*stableAge[2], np_reg_med[1,6]/2*0.75*stableAge[2]), 
                c(np_reg_med[1,1]/2*1.25*stableAge[2], np_reg_med[1,2]/2*1.25*stableAge[2],
                                  np_reg_med[1,3]/2*1.25*stableAge[2], np_reg_med[1,4]/2*1.25*stableAge[2],
                                  np_reg_med[1,5]/2*1.25*stableAge[2], np_reg_med[1,6]/2*1.25*stableAge[2]))
len_v2 <- dim(v2)[2]

v3 <- dUnif(c(np_reg_med[1,1]/2*0.75*stableAge[3], np_reg_med[1,2]/2*0.75*stableAge[3],
                                  np_reg_med[1,3]/2*0.75*stableAge[3], np_reg_med[1,4]/2*0.75*stableAge[3],
                                  np_reg_med[1,5]/2*0.75*stableAge[3], np_reg_med[1,6]/2*0.75*stableAge[3]), 
                c(np_reg_med[1,1]/2*1.25*stableAge[3], np_reg_med[1,2]/2*1.25*stableAge[3],
                                  np_reg_med[1,3]/2*1.25*stableAge[3], np_reg_med[1,4]/2*1.25*stableAge[3],
                                  np_reg_med[1,5]/2*1.25*stableAge[3], np_reg_med[1,6]/2*1.25*stableAge[3]))
len_v3 <- dim(v3)[2]

v4 <- dUnif(c(np_reg_med[1,1]/2*0.75*stableAge[4], np_reg_med[1,2]/2*0.75*stableAge[4],
                                  np_reg_med[1,3]/2*0.75*stableAge[4], np_reg_med[1,4]/2*0.75*stableAge[4],
                                  np_reg_med[1,5]/2*0.75*stableAge[4], np_reg_med[1,6]/2*0.75*stableAge[4]), 
                c(np_reg_med[1,1]/2*1.25*stableAge[4], np_reg_med[1,2]/2*1.25*stableAge[4],
                                  np_reg_med[1,3]/2*1.25*stableAge[4], np_reg_med[1,4]/2*1.25*stableAge[4],
                                  np_reg_med[1,5]/2*1.25*stableAge[4], np_reg_med[1,6]/2*1.25*stableAge[4]))
len_v4 <- dim(v4)[2]

v5 <- dUnif(c(np_reg_med[1,1]/2*0.75*stableAge[5], np_reg_med[1,2]/2*0.75*stableAge[5],
                                  np_reg_med[1,3]/2*0.75*stableAge[5], np_reg_med[1,4]/2*0.75*stableAge[5],
                                  np_reg_med[1,5]/2*0.75*stableAge[5], np_reg_med[1,6]/2*0.75*stableAge[5]), 
                c(np_reg_med[1,1]/2*1.25*stableAge[5], np_reg_med[1,2]/2*1.25*stableAge[5],
                                  np_reg_med[1,3]/2*1.25*stableAge[5], np_reg_med[1,4]/2*1.25*stableAge[5],
                                  np_reg_med[1,5]/2*1.25*stableAge[5], np_reg_med[1,6]/2*1.25*stableAge[5]))
len_v5 <- dim(v5)[2]

v6 <- dUnif(c(np_reg_med[1,1]/2*0.75*stableAge[6], np_reg_med[1,2]/2*0.75*stableAge[6],
                                  np_reg_med[1,3]/2*0.75*stableAge[6], np_reg_med[1,4]/2*0.75*stableAge[6],
                                  np_reg_med[1,5]/2*0.75*stableAge[6], np_reg_med[1,6]/2*0.75*stableAge[6]), 
                c(np_reg_med[1,1]/2*1.25*stableAge[6], np_reg_med[1,2]/2*1.25*stableAge[6],
                                  np_reg_med[1,3]/2*1.25*stableAge[6], np_reg_med[1,4]/2*1.25*stableAge[6],
                                  np_reg_med[1,5]/2*1.25*stableAge[6], np_reg_med[1,6]/2*1.25*stableAge[6]))
len_v6 <- dim(v6)[2]

v8 <- dUnif(c(np_reg_med[1,1]/2*0.75*stableAge[8], np_reg_med[1,2]/2*0.75*stableAge[8],
                                  np_reg_med[1,3]/2*0.75*stableAge[8], np_reg_med[1,4]/2*0.75*stableAge[8],
                                  np_reg_med[1,5]/2*0.75*stableAge[8], np_reg_med[1,6]/2*0.75*stableAge[8]), 
                c(np_reg_med[1,1]/2*1.25*stableAge[8], np_reg_med[1,2]/2*1.25*stableAge[8],
                                  np_reg_med[1,3]/2*1.25*stableAge[8], np_reg_med[1,4]/2*1.25*stableAge[8],
                                  np_reg_med[1,5]/2*1.25*stableAge[8], np_reg_med[1,6]/2*1.25*stableAge[8]))
len_v8 <- dim(v8)[2]

#males
v2m <- dUnif(c(np_reg_med[1,1]/2*0.75*stableAgeM[2], np_reg_med[1,2]/2*0.75*stableAgeM[2],
                                  np_reg_med[1,3]/2*0.75*stableAgeM[2], np_reg_med[1,4]/2*0.75*stableAgeM[2],
                                  np_reg_med[1,5]/2*0.75*stableAgeM[2], np_reg_med[1,6]/2*0.75*stableAgeM[2]), 
                c(np_reg_med[1,1]/2*1.25*stableAgeM[2], np_reg_med[1,2]/2*1.25*stableAgeM[2],
                                  np_reg_med[1,3]/2*1.25*stableAgeM[2], np_reg_med[1,4]/2*1.25*stableAgeM[2],
                                  np_reg_med[1,5]/2*1.25*stableAgeM[2], np_reg_med[1,6]/2*1.25*stableAgeM[2]))
len_v2m <- dim(v2m)[2]

v3m <- dUnif(c(np_reg_med[1,1]/2*0.75*stableAgeM[3], np_reg_med[1,2]/2*0.75*stableAgeM[3],
                                  np_reg_med[1,3]/2*0.75*stableAgeM[3], np_reg_med[1,4]/2*0.75*stableAgeM[3],
                                  np_reg_med[1,5]/2*0.75*stableAgeM[3], np_reg_med[1,6]/2*0.75*stableAgeM[3]), 
                c(np_reg_med[1,1]/2*1.25*stableAgeM[3], np_reg_med[1,2]/2*1.25*stableAgeM[3],
                                  np_reg_med[1,3]/2*1.25*stableAgeM[3], np_reg_med[1,4]/2*1.25*stableAgeM[3],
                                  np_reg_med[1,5]/2*1.25*stableAgeM[3], np_reg_med[1,6]/2*1.25*stableAgeM[3]))
len_v3m <- dim(v3m)[2]

v4m <- dUnif(c(np_reg_med[1,1]/2*0.75*stableAgeM[4], np_reg_med[1,2]/2*0.75*stableAgeM[4],
                                  np_reg_med[1,3]/2*0.75*stableAgeM[4], np_reg_med[1,4]/2*0.75*stableAgeM[4],
                                  np_reg_med[1,5]/2*0.75*stableAgeM[4], np_reg_med[1,6]/2*0.75*stableAgeM[4]), 
                c(np_reg_med[1,1]/2*1.25*stableAgeM[4], np_reg_med[1,2]/2*1.25*stableAgeM[4],
                                  np_reg_med[1,3]/2*1.25*stableAgeM[4], np_reg_med[1,4]/2*1.25*stableAgeM[4],
                                  np_reg_med[1,5]/2*1.25*stableAgeM[4], np_reg_med[1,6]/2*1.25*stableAgeM[4]))
len_v4m <- dim(v4m)[2]

v5m <- dUnif(c(np_reg_med[1,1]/2*0.75*stableAgeM[5], np_reg_med[1,2]/2*0.75*stableAgeM[5],
                                  np_reg_med[1,3]/2*0.75*stableAgeM[5], np_reg_med[1,4]/2*0.75*stableAgeM[5],
                                  np_reg_med[1,5]/2*0.75*stableAgeM[5], np_reg_med[1,6]/2*0.75*stableAgeM[5]), 
                c(np_reg_med[1,1]/2*1.25*stableAgeM[5], np_reg_med[1,2]/2*1.25*stableAgeM[5],
                                  np_reg_med[1,3]/2*1.25*stableAgeM[5], np_reg_med[1,4]/2*1.25*stableAgeM[5],
                                  np_reg_med[1,5]/2*1.25*stableAgeM[5], np_reg_med[1,6]/2*1.25*stableAgeM[5]))
len_v5m <- dim(v5m)[2]

v6m <- dUnif(c(np_reg_med[1,1]/2*0.75*stableAgeM[6], np_reg_med[1,2]/2*0.75*stableAgeM[6],
                                  np_reg_med[1,3]/2*0.75*stableAgeM[6], np_reg_med[1,4]/2*0.75*stableAgeM[6],
                                  np_reg_med[1,5]/2*0.75*stableAgeM[6], np_reg_med[1,6]/2*0.75*stableAgeM[6]), 
                c(np_reg_med[1,1]/2*1.25*stableAgeM[6], np_reg_med[1,2]/2*1.25*stableAgeM[6],
                                  np_reg_med[1,3]/2*1.25*stableAgeM[6], np_reg_med[1,4]/2*1.25*stableAgeM[6],
                                  np_reg_med[1,5]/2*1.25*stableAgeM[6], np_reg_med[1,6]/2*1.25*stableAgeM[6]))
len_v6m <- dim(v6m)[2]

v7m <- dUnif(c(np_reg_med[1,1]/2*0.75*stableAgeM[7], np_reg_med[1,2]/2*0.75*stableAgeM[7],
                                  np_reg_med[1,3]/2*0.75*stableAgeM[7], np_reg_med[1,4]/2*0.75*stableAgeM[7],
                                  np_reg_med[1,5]/2*0.75*stableAgeM[7], np_reg_med[1,6]/2*0.75*stableAgeM[7]), 
                c(np_reg_med[1,1]/2*1.25*stableAgeM[7], np_reg_med[1,2]/2*1.25*stableAgeM[7],
                                  np_reg_med[1,3]/2*1.25*stableAgeM[7], np_reg_med[1,4]/2*1.25*stableAgeM[7],
                                  np_reg_med[1,5]/2*1.25*stableAgeM[7], np_reg_med[1,6]/2*1.25*stableAgeM[7]))
len_v7m <- dim(v7m)[2]

```

```{r option null}

SSL_IPM <- nimbleCode({
  
  # Priors and constraints
  for (i in 1:n_fem) { #females
    for (t in 1:(n_occasions - 1)) {
      logit(phiP[i,t]) <- mu.P #+ b.massP*mass_f[i] + b.regP[reg_f[i]] + epsP[reg_f[i],t]   
      logit(phi1[i,t]) <- mu.1 #+ b.mass1*mass_f[i] + b.reg1[reg_f[i]] + eps1[reg_f[i],t]  
      logit(phi2[i,t]) <- mu.2 #+ b.mass1*mass_f[i] + b.reg2[reg_f[i]] + eps2[reg_f[i],t] 
      logit(phi3[i,t]) <- mu.3 #+ b.regPB[reg_fb[i]] + epsPB[reg_fb[i],t] 
      logit(phi4[i,t]) <- mu.4 #+ b.regPB[reg_fb[i]] + epsPB[reg_fb[i],t]
      logit(phi5[i,t]) <- mu.5 #+ b.regPB[reg_fb[i]] + epsPB[reg_fb[i],t] 
      logit(phiB[i,t]) <- mu.B #+ b.regB[reg_fb[i]] + epsB[reg_f[i],t]
      logit(phiNB[i,t]) <- mu.NB 
      
      logit(psi3[i,t]) <- mu.psi3# + b.reg.psi3[reg_f[i]] #+ eps.psiPB[reg_fb[i],t] 
      logit(psi4[i,t]) <- mu.psi4 #+ b.reg.psi4[reg_f[i]] + eps.psiPB[reg_fb[i],t]  
      logit(psi5[i,t]) <- mu.psi5 #+ b.reg.psi5[reg_f[i]] #+ eps.psiPB[reg_fb[i],t] 
      logit(psiB[i,t]) <- mu.psiB #+ b.reg.psiB[reg_f[i]] + eps.psiB[reg_fb[i],t]   
      logit(psiNB[i,t]) <- mu.psiNB #+ b.reg.psiNB[reg_f[i]] #+ eps.psiNB[reg_fb[i],t] 
      
      logit(p1[i,t]) <- mu.p1 + b.eff[eff[t]] #+ eps.p[t] 
      logit(p2[i,t]) <- mu.p2 + b.eff[eff[t]] #+ eps.p[t]
      logit(p3[i,t]) <- mu.p3 + b.eff[eff[t]] #+ eps.p[t]
      logit(p4[i,t]) <- mu.p4 + b.eff[eff[t]] #+ eps.p[t]
      logit(p5[i,t]) <- mu.p5 + b.eff[eff[t]] #+ eps.p[t]
      logit(pB[i,t]) <- mu.pB + b.eff[eff[t]] #+ eps.p[t]
      logit(pNB[i,t]) <- mu.pNB + b.eff[eff[t]] #+ eps.p[t]
      logit(delB[i,t]) <- b.delB[resights[i,t]]
    } #t 
  } #i fem
  
  for (i in 1:n_m) { #males
    for (t in 1:(n_occasions - 1)) {
      logit(phiPM[i,t]) <- mu.PM #+ b.massPM*mass_m[i] + b.regP[reg_m[i]] + epsP[reg_m[i],t]    
      logit(phi1M[i,t]) <- mu.1M #+ b.mass1M*mass_m[i] + b.reg1[reg_m[i]] + eps1[reg_m[i],t]    
      logit(phi2M[i,t]) <- mu.2M #+ b.mass1M*mass_m[i] + b.reg2[reg_m[i]] + eps2[reg_m[i],t]   
      logit(phi3M[i,t]) <- mu.3M #+ b.regPB[reg_mb[i]] + epsPB[reg_mb[i],t] 
      logit(phi4M[i,t]) <- mu.4M #+ b.regPB[reg_mb[i]] + epsPB[reg_mb[i],t] 
      logit(phi5M[i,t]) <- mu.5M #+ b.regPB[reg_mb[i]] + epsPB[reg_mb[i],t] 
      logit(phiBM[i,t]) <- mu.BM #+ b.regB[reg_mb[i]] + epsB[reg_mb[i],t]
      
      logit(p1M[i,t]) <- mu.p1M + b.eff[eff[t]] #+ eps.p[t]
      logit(p2M[i,t]) <- mu.p2M + b.eff[eff[t]] #+ eps.p[t]
      logit(p3M[i,t]) <- mu.p3M + b.eff[eff[t]] #+ eps.p[t]
      logit(p4M[i,t]) <- mu.p4M + b.eff[eff[t]] #+ eps.p[t]
      logit(p5M[i,t]) <- mu.p5M + b.eff[eff[t]] #+ eps.p[t]
      logit(pBM[i,t]) <- mu.pBM + b.eff[eff[t]] #+ eps.p[t]
    } #t male
  } #i male
  
  ### Priors
  #fixed categorical effect of natal region
  # b.regP[2] <- 0
  # b.reg1[2] <- 0
  # b.reg2[2] <- 0
  # b.regPB[1] <- 0
  # b.regB[1] <- 0
  # b.reg.psi3[2] <- 0
  # b.reg.psi4[2] <- 0
  # b.reg.psi5[2] <- 0
  # b.reg.psiB[2] <- 0
  # b.reg.psiNB[2] <- 0
  # 
  # for (r in c(1,3,4,5,6)) {
  # b.regP[r] ~ dnorm(0, sd = s.regP)
  # b.reg1[r] ~ dnorm(0, sd = s.reg1)
  # b.reg2[r] ~ dnorm(0, sd = s.reg2)
  
  # b.reg.psi3[r] ~ dnorm(0, sd = s.psiPB)
  # b.reg.psi4[r] ~ dnorm(0, sd = s.psiPB)
  # b.reg.psi5[r] ~ dnorm(0, sd = s.psiPB)
  # b.reg.psiB[r] ~ dnorm(0, sd = s.psiB)
  # b.reg.psiNB[r] ~ dnorm(0, sd = s.psiB)
  # }
  # 
  # b.regPB[2] ~ dnorm(0, sd = s.regPB)
  # b.regB[2] ~ dnorm(0, sd = s.regB)
  
  # s.regP ~ dexp(1)
  # s.reg1 ~ dexp(1)
  # s.reg2 ~ dexp(1)
  # s.regPB ~ dexp(1)
  # s.regB ~ dexp(1)
  # # s.regNB ~ dexp(1)
  # s.psiPB ~ dexp(1)
  # s.psiB ~ dexp(1)
  # # s.eps.reg ~ dexp(1)
 
  #  for (j in 1:4) {
  #   epsP[j,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.epsP, c)
  #   eps1[j,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.eps1, c)
  #   eps2[j,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.eps2, c)
  #   epsB[j,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.epsB, c)
  # } 
  # 
  # epsP[5:6,1:(n_occasions-1)] <- 0
  # eps1[5:6,1:(n_occasions-1)] <- 0
  # eps2[5:6,1:(n_occasions-1)] <- 0
  # epsB[5:6,1:(n_occasions-1)] <- 0
  
  # epsPB[1,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.epsPB, c)
  # epsPB[2,1:(n_occasions-1)] <- 0
  # 
  # eps.psiPB[1,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.eps.psi, c)
  # eps.psiB[1,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.eps.psi, c)
  # 
  # eps.psiPB[2,1:(n_occasions-1)] <- 0
  # eps.psiB[2,1:(n_occasions-1)] <- 0
  
  # t.epsP <- 1/(s.epsP*s.epsP) #precision
  # s.epsP ~ dexp(1) #standard deviation
  # t.eps1 <- 1/(s.eps1*s.eps1)
  # s.eps1 ~ dexp(1)
  # t.eps2 <- 1/(s.eps2*s.eps2)
  # s.eps2 ~ dexp(1)
  # t.epsPB <- 1/(s.epsPB*s.epsPB)
  # s.epsPB ~ dexp(1)
  # t.epsB <- 1/(s.epsB*s.epsB)
  # s.epsB ~ dexp(1)
  # t.eps.psi <- 1/(s.eps.psi*s.eps.psi)
  # s.eps.psi ~ dexp(1)
    
    # for (t in 1:(n_occasions)) {
    #   eps.p[t] ~ dnorm(0, sd = sigma.p)
    # }
    # sigma.p ~ dexp(1)
  
  #intercepts  
  mu.psi3 <- log(int.psi3/(1-int.psi3))
  mu.psi4 <- log(int.psi4/(1-int.psi4))
  mu.psi5 <- log(int.psi5/(1-int.psi5))
  mu.psiB <- log(int.psiB/(1-int.psiB))
  mu.psiNB <- log(int.psiNB/(1-int.psiNB))
  int.psi3 ~ T(dnorm(psi_ests[1,1], sd = psi_ests[1,2]),0,1)
  int.psi4 ~ T(dnorm(psi_ests[2,1], sd = psi_ests[2,2]),0,1)
  int.psi5 ~ T(dnorm(psi_ests[3,1], sd = psi_ests[3,2]),0,1)
  int.psiB ~ T(dnorm(psi_ests[4,1], sd = psi_ests[4,2]),0,1)
  int.psiNB ~ T(dnorm(psi_ests[5,1], sd = psi_ests[5,2]),0,1)
  mu.p1 <- log(int.p1/(1 - int.p1))
  mu.p2 <- log(int.p2/(1 - int.p2))
  mu.p3 <- log(int.p3/(1 - int.p3))
  mu.p4 <- log(int.p4/(1 - int.p4))
  mu.p5 <- log(int.p5/(1 - int.p5))
  mu.pB <- log(int.pB/(1 - int.pB))
  mu.pNB <- log(int.pNB/(1 - int.pNB))
  mu.p1M <- log(int.p1M/(1 - int.p1M))
  mu.p2M <- log(int.p2M/(1 - int.p2M))
  mu.p3M <- log(int.p3M/(1 - int.p3M))
  mu.p4M <- log(int.p4M/(1 - int.p4M))
  mu.p5M <- log(int.p5M/(1 - int.p5M))
  mu.pBM <- log(int.pBM/(1 - int.pBM))
  int.p1 ~ dunif(0,1)
  int.p2 ~ dunif(0,1)
  int.p3 ~ dunif(0,1)
  int.p4 ~ dunif(0,1)
  int.p5 ~ dunif(0,1)
  int.pB ~ dunif(0,1)
  int.pNB ~ dunif(0,1)
  int.p1M ~ dunif(0,1)
  int.p2M ~ dunif(0,1)
  int.p3M ~ dunif(0,1)
  int.p4M ~ dunif(0,1)
  int.p5M ~ dunif(0,1)
  int.pBM ~ dunif(0,1)
  #phi
  mu.P <- log(int.phiP/(1 - int.phiP))
  mu.1 <- log(int.phi1/(1 - int.phi1))
  mu.2 <- log(int.phi2/(1 - int.phi2))
  mu.3 <- log(int.phi3/(1 - int.phi3))
  mu.4 <- log(int.phi4/(1 - int.phi4))
  mu.5 <- log(int.phi5/(1 - int.phi5))
  mu.B <- log(int.phiB/(1 - int.phiB))
  mu.NB <- log(int.phiNB/(1 - int.phiNB))
  mu.PM <- log(int.phiPM/(1 - int.phiPM))
  mu.1M <- log(int.phi1M/(1 - int.phi1M))
  mu.2M <- log(int.phi2M/(1 - int.phi2M))
  mu.3M <- log(int.phi3M/(1 - int.phi3M))
  mu.4M <- log(int.phi4M/(1 - int.phi4M))
  mu.5M <- log(int.phi5M/(1 - int.phi5M))
  mu.BM <- log(int.phiBM/(1 - int.phiBM)) 
  int.phiP ~ T(dnorm(phi_ests[1,1], sd = phi_ests[1,2]),0,1)
  int.phi1 ~ T(dnorm(phi_ests[2,1], sd = phi_ests[2,2]),0,1)
  int.phi2 ~ T(dnorm(phi_ests[3,1], sd = phi_ests[3,2]),0,1)
  int.phi3 ~ T(dnorm(phi_ests[4,1], sd = phi_ests[4,2]),0,1)
  int.phi4 ~ T(dnorm(phi_ests[5,1], sd = phi_ests[5,2]),0,1)
  int.phi5 ~ T(dnorm(phi_ests[6,1], sd = phi_ests[6,2]),0,1)
  int.phiB ~ T(dnorm(phi_ests[7,1], sd = phi_ests[7,2]),0,1)
  int.phiNB ~ T(dnorm(phi_ests[7,1], sd = phi_ests[7,2]),0,1)
  int.phiPM ~ T(dnorm(phi_ests[8,1], sd = phi_ests[8,2]),0,1)
  int.phi1M ~ T(dnorm(phi_ests[9,1], sd = phi_ests[9,2]),0,1)
  int.phi2M ~ T(dnorm(phi_ests[10,1], sd = phi_ests[10,2]),0,1)
  int.phi3M ~ T(dnorm(phi_ests[11,1], sd = phi_ests[11,2]),0,1)
  int.phi4M ~ T(dnorm(phi_ests[12,1], sd = phi_ests[12,2]),0,1)
  int.phi5M ~ T(dnorm(phi_ests[13,1], sd = phi_ests[13,2]),0,1)
  int.phiBM ~ T(dnorm(phi_ests[14,1], sd = phi_ests[14,2]),0,1)
  
  p.delB[1] ~ dunif(0,1)
  b.delB[1] <- log(p.delB[1]/(1-p.delB[1]))
  p.delB[2] ~ dunif(0,1)
  b.delB[2] <- log(p.delB[2]/(1-p.delB[2]))
  p.delB[3] ~ dunif(0,1)
  b.delB[3] <- log(p.delB[3]/(1-p.delB[3]))
  b.delB[4] <- -5 #0 on probability scale
  
  b.eff[1] <- 0
  b.eff[2] ~ dnorm(0, 0.001)
    
    #back-transform everything
       for (t in 1:(n_occasions-1)){
    for (r in 1:6) {
      phiP.prob[r,t] <- 1/(1+exp(-(mu.P)))
      phiPM.prob[r,t] <- 1/(1+exp(-(mu.PM)))
      phi1.prob[r,t] <- 1/(1+exp(-(mu.1)))
      phi1M.prob[r,t] <- 1/(1+exp(-(mu.1M)))
      phi2.prob[r,t] <- 1/(1+exp(-(mu.2)))
      phi2M.prob[r,t] <- 1/(1+exp(-(mu.2M)))
      phiB.prob[r,t] <- 1/(1+exp(-(mu.B)))
    }

      for (r in 1:4) {
      phi3.prob[r,t] <- 1/(1+exp(-(mu.3)))
      phi3M.prob[r,t] <- 1/(1+exp(-(mu.3M)))
      phi4.prob[r,t] <- 1/(1+exp(-(mu.4)))
      phi4M.prob[r,t] <- 1/(1+exp(-(mu.4M)))
      phi5.prob[r,t] <- 1/(1+exp(-(mu.5)))
      phi5M.prob[r,t] <- 1/(1+exp(-(mu.5M)))
      
      phiNB.prob[r,t] <- 1/(1+exp(-(mu.NB)))
      phiBM.prob[r,t] <- 1/(1+exp(-(mu.BM)))
      psi3.prob[r,t] <- 1/(1+exp(-(mu.psi3)))
      psi4.prob[r,t] <- 1/(1+exp(-(mu.psi4)))
      psi5.prob[r,t] <- 1/(1+exp(-(mu.psi5)))
      psiB.prob[r,t] <- 1/(1+exp(-(mu.psiB)))
      psiNB.prob[r,t] <- 1/(1+exp(-(mu.psiNB)))
      }
      for (r in 5:6) {
      phi3.prob[r,t] <- 1/(1+exp(-(mu.3)))
      phi3M.prob[r,t] <- 1/(1+exp(-(mu.3M)))
      phi4.prob[r,t] <- 1/(1+exp(-(mu.4)))
      phi4M.prob[r,t] <- 1/(1+exp(-(mu.4M)))
      phi5.prob[r,t] <- 1/(1+exp(-(mu.5)))
      phi5M.prob[r,t] <- 1/(1+exp(-(mu.5M)))
      phiNB.prob[r,t] <- 1/(1+exp(-(mu.NB)))
      psi3.prob[r,t] <- 1/(1+exp(-(mu.psi3)))
      psi4.prob[r,t] <- 1/(1+exp(-(mu.psi4)))
      psi5.prob[r,t] <- 1/(1+exp(-(mu.psi5)))
      psiB.prob[r,t] <- 1/(1+exp(-(mu.psiB)))
      psiNB.prob[r,t] <- 1/(1+exp(-(mu.psiNB)))
      }
         
    } #t
    
    #likelihood
for (i in 1:n_fem) { #females
    z[i, fc[i]:fc[i]] <- 1 #pups at first capture
for (t in (fc[i] + 1):n_occasions) {
      z[i,t] ~ dcat(state_probs[i,t-1,1:12])
      y[i,t] ~ dcat(event_probs[i,t,1:11])
      
    state_probs[i,t-1,1:12] <- getPHI_f(z = z[i,t-1], 
                                      phiP = phiP[i,t-1], phi1 = phi1[i,t-1], phi2 = phi2[i,t-1], 
                                      phi3 = phi3[i,t-1], phi4 = phi4[i,t-1], phi5 = phi5[i,t-1], 
                                      phiB = phiB[i,t-1], phiNB = phiNB[i,t-1],
                                      psi3 = psi3[i,t-1], psi4 = psi4[i,t-1],
                                      psi5 = psi5[i,t-1], psiB = psiB[i,t-1], psiNB = psiNB[i,t-1])
    
    event_probs[i,t,1:11] <- getP_f(z = z[i,t], 
                                    p1 = p1[i,t-1], p2 = p2[i,t-1], p3 = p3[i,t-1], 
                                    p4 = p4[i,t-1], p5 = p5[i,t-1],
                                    pB = pB[i,t-1], pNB = pNB[i,t-1], delB = delB[i,t-1])
    } #t likelihood fem
} #i likelihood fem
    
   for (i in 1:n_m) { #males
    zm[i, fc_m[i]:fc_m[i]] <- 1
  for (t in (fc_m[i] + 1):n_occasions) {
    zm[i,t] ~ dcat(state_probs_m[i, t-1, 1:8])
    ym[i,t] ~ dcat(event_probs_m[i,t,1:8])
    
    state_probs_m[i,t-1,1:8] <- getPHI_m(z = zm[i,t-1], 
                                      phiPM = phiPM[i,t-1], phi1M = phi1M[i,t-1], phi2M = phi2M[i,t-1], 
                                      phi3M = phi3M[i,t-1], phi4M = phi4M[i,t-1], phi5M = phi5M[i,t-1], 
                                      phiBM = phiBM[i,t-1])
    event_probs_m[i,t,1:8] <- getP_m(z = zm[i,t], 
                                    p1M = p1M[i,t-1], p2M = p2M[i,t-1], p3M = p3M[i,t-1], 
                                    p4M = p4M[i,t-1], p5M = p5M[i,t-1], pBM = pBM[i,t-1])
    } # likelihood t male
   } #likelihood i male
    
########################### population model ################################  

    # sigma.popInit ~ dexp(1)
    
    for (j in 1:n_r) {
   # total females
   # Ntot_f[1,j] ~ dpois(round(np_reg_med[1,j]*prop_f))
   # lNtot_f[j] ~ dlnorm(meanlog = log(np_reg_med[1,j]*prop_f), sdlog = log(sigma.popInit))
   # Ntot_f[1,j] <- round(exp(lNtot_f[j]))
   
   # Ntot_f[1,j] ~ dnorm(np_reg_med[1,j]*prop_f, sd = sigma.popInit)
   # Ntot_f[1,j] <- round(np_reg_med[1,j]*prop_f)
      
  # establish first year of population using conditional binomials
   # N_f[1,1,j] <- round(pups_reg_med[1,j]/2) #pups in 2000
      
      N_f[1,1,j] ~ dcat(v1[j,1:len_v1])
      N_f[2,1,j] ~ dcat(v2[j,1:len_v2])
      N_f[3,1,j] ~ dcat(v3[j,1:len_v3])
      N_f[4,1,j] ~ dcat(v4[j,1:len_v4])
      N_f[5,1,j] ~ dcat(v5[j,1:len_v5])
      N_f[6,1,j] ~ dcat(v6[j,1:len_v6])
      N_f[7,1,j] ~ dcat(vB[j,1:len_vB])
      N_f[8,1,j] ~ dcat(v8[j,1:len_v8])
      Ntot_f[1,j] <- sum(N_f[1:8,1,j])
 
      N_m[1,1,j] ~ dcat(v1[j,1:len_v1])
      N_m[2,1,j] ~ dcat(v2m[j,1:len_v2m])
      N_m[3,1,j] ~ dcat(v3m[j,1:len_v3m])
      N_m[4,1,j] ~ dcat(v4m[j,1:len_v4m])
      N_m[5,1,j] ~ dcat(v5m[j,1:len_v5m])
      N_m[6,1,j] ~ dcat(v6m[j,1:len_v6m])
      N_m[7,1,j] ~ dcat(v7m[j,1:len_v7m])
      Ntot_m[1,j] <- sum(N_m[1:7,1,j])
   
   # for(g in 2:(G-1)){
   #  N_f[g,1,j] ~ dbin(stableAge[g]/(1-sum(stableAge[1:(g-1)])), Ntot_f[1,j] - sum(N_f[1:(g-1),1,j]) )
   # }
   # 
   # # group G: deterministic
   # N_f[G,1,j] <- Ntot_f[1,j] - sum(N_f[1:(G-1),1,j])
      
   #  #total breeders and non-breeders
    N_B[1,j] <-  N_f[7,1,j]  # total breeders
    N_NB[1,j] <- N_f[8,1,j] # total NB
    
    ###MALES
    # Ntot_m[1,j] ~ dpois(np_reg_med[1,j]*(1-prop_f)) #total males
    # lNtot_m[j] ~ dlnorm(meanlog = log(np_reg_med[1,j]*(1-prop_f)), sdlog = log(sigma.popInit)) 
    # Ntot_m[1,j] <- round(exp(lNtot_m[j]))
    
     # Ntot_m[1,j] ~ dnorm(np_reg_med[1,j]*(1-prop_f), sd = sigma.popInit)
   #  Ntot_m[1,j] <- round(np_reg_med[1,j]*(1-prop_f))
   # 
   #  N_m[1,1,j] <- round(pups_reg_med[1,j]/2) #pups
   # 
   #  for(h in 2:(H-1)){
   #  N_m[h,1,j] ~ dbin(stableAgeM[h]/(1-sum(stableAgeM[1:(h-1)])), Ntot_m[1,j] - sum(N_m[1:(h-1),1,j]) )
   #  }
   # 
   # # group H: deterministic
   # N_m[H,1,j] <- Ntot_m[1,j] - sum(N_m[1:(H-1),1,j])
    N_A1[1,j] <- N_m[6,1,j] #new adults from 5yos
    N_Aplus[1,j] <- N_m[7,1,j]  #repeat adults 7+
    Ntot[1,j] <- Ntot_f[1,j] + Ntot_m[1,j]
    
    for (t in 1:(n_occasions-1)) { #t = 1 fills t+1 == Ntot[2001]; t = 18 fills t+1 == Ntot[2018]
    pups_reg_med[t+1,j] ~ dnorm(N_f[1,t+1,j]+N_m[1,t+1,j], sd = pups_reg_sd[t+1,j])

    ###FEMALES
    N_f[1,t+1,j] ~ dbin(0.5, N_f[7,t+1,j]) # or deterministic N_f[1,t+1,j] <- N_f[7,t+1,j]*0.5
    N_f[2,t+1,j] ~ dpois(phiP.prob[j,t]*neo_mort*N_f[1,t,j]) #yearlings
    N_f[3,t+1,j] ~ dpois(phi1.prob[j,t]*N_f[2,t,j]) #2yos
    N_f[4,t+1,j] ~ dpois(phi2.prob[j,t]*N_f[3,t,j]) #3yos
    N_f[5,t+1,j] ~ dpois(phi3.prob[j,t]*(1-psi3.prob[j,t])*N_f[4,t,j]) #4yo PB
    N_f[6,t+1,j] ~ dpois(phi4.prob[j,t]*(1-psi4.prob[j,t])*N_f[5,t,j]) #5yo PB
    N_4B[t+1,j] ~ dpois(phi3.prob[j,t]*psi3.prob[j,t]*N_f[4,t,j]) #4yo breeders
    N_5B[t+1,j] ~ dpois(phi4.prob[j,t]*psi4.prob[j,t]*N_f[5,t,j]) #5yo first-B
    N_6B[t+1,j] ~ dpois(phi5.prob[j,t]*psi5.prob[j,t]*N_f[6,t,j]) #6yo first-B
    N_6NB[t+1,j] ~ dpois(phi5.prob[j,t]*(1-psi5.prob[j,t])*N_f[6,t,j]) #6yo NB that was PB at 5

    ## Plus groups
    #breeders
    N_BB[t+1,j] ~ dpois(phiB.prob[j,t]*psiB.prob[j,t]*N_B[t,j]) # plus grp B given B
    N_BNB[t+1,j] ~ dpois(phiNB.prob[j,t]*psiNB.prob[j,t]*N_NB[t,j]) # plus grp B given NB
    #non breeders
    N_NBNB[t+1,j] ~ dpois(phiNB.prob[j,t]*(1-psiNB.prob[j,t])*N_NB[t,j]) # plus grp NB given NB
    N_NBB[t+1,j] ~ dpois(phiB.prob[j,t]*(1-psiB.prob[j,t])*N_B[t,j]) # plus grp NB given B

    #total breeders and non-breeders
    N_B[t+1,j] <- N_4B[t+1,j]+N_5B[t+1,j]+N_6B[t+1,j]+N_BB[t+1,j]+N_BNB[t+1,j] # total breeders
    N_NB[t+1,j] <- N_6NB[t+1,j]+N_NBB[t+1,j]+N_NBNB[t+1,j] # total breeders
    N_f[7,t+1,j] <- N_B[t+1,j]   #B
    N_f[8,t+1,j] <- N_NB[t+1,j]  #NB
     Ntot_f[t+1,j] <- sum(N_f[1:8,t+1,j])

    ###MALES
    N_m[1,t+1,j] ~ dbin(0.5, N_f[7,t+1,j]) #pups
    N_m[2,t+1,j] ~ dpois(phiPM.prob[j,t]*neo_mort*N_m[1,t,j]) #yearlings
    N_m[3,t+1,j] ~ dpois(phi1M.prob[j,t]*N_m[2,t,j]) #2yos
    N_m[4,t+1,j] ~ dpois(phi2M.prob[j,t]*N_m[3,t,j]) #3yos
    N_m[5,t+1,j] ~ dpois(phi3M.prob[j,t]*N_m[4,t,j]) #4yos
    N_m[6,t+1,j] ~ dpois(phi4M.prob[j,t]*N_m[5,t,j]) #5yos
    N_A1[t+1,j] ~ dpois(phi5M.prob[j,t]*N_m[6,t,j]) #new adults from 5yos
    N_Aplus[t+1,j] ~ dpois(phiBM.prob[j,t]*N_m[7,t,j]) #repeat adults 7+
    N_m[7,t+1,j] <- N_A1[t+1,j] + N_Aplus[t+1,j]
    Ntot_m[t+1,j] <- sum(N_m[1:7,t+1,j])
    Ntot[t+1,j] <- Ntot_f[t+1,j] + Ntot_m[t+1,j]
  } #t

    #fill up to aerial survey data in 2021
        for (t in n_occasions:(n_occasions+2)) { #t = 19 fills t+1 == Ntot[2019]; t = 21 fills t+1 == Ntot[2021]
    pups_reg_med[t+1,j] ~ dnorm(N_f[1,t+1,j]+N_m[1,t+1,j], sd = pups_reg_sd[t+1,j])

    ###FEMALES
    N_f[1,t+1,j] ~ dbin(0.5, N_f[7,t+1,j]) # or deterministic N_f[1,t+1,j] <- N_f[7,t+1,j]*0.5
    N_f[2,t+1,j] ~ dpois(mean(phiP.prob[j,1:(n_occasions-1)])*neo_mort*N_f[1,t,j]) #yearlings
    N_f[3,t+1,j] ~ dpois(mean(phi1.prob[j,1:(n_occasions-1)])*N_f[2,t,j]) #2yos
    N_f[4,t+1,j] ~ dpois(mean(phi2.prob[j,1:(n_occasions-1)])*N_f[3,t,j]) #3yos
    N_f[5,t+1,j] ~ dpois(mean(phi3.prob[j,1:(n_occasions-1)])*(1-mean(psi3.prob[j,1:(n_occasions-1)]))*N_f[4,t,j]) #4yo PB
    N_f[6,t+1,j] ~ dpois(mean(phi4.prob[j,1:(n_occasions-1)])*(1-mean(psi4.prob[j,1:(n_occasions-1)]))*N_f[5,t,j]) #5yo PB
    N_4B[t+1,j] ~ dpois(mean(phi3.prob[j,1:(n_occasions-1)])*mean(psi3.prob[j,1:(n_occasions-1)])*N_f[4,t,j]) #4yo breeders
    N_5B[t+1,j] ~ dpois(mean(phi4.prob[j,1:(n_occasions-1)])*mean(psi4.prob[j,1:(n_occasions-1)])*N_f[5,t,j]) #5yo first-B
    N_6B[t+1,j] ~ dpois(mean(phi5.prob[j,1:(n_occasions-1)])*mean(psi5.prob[j,1:(n_occasions-1)])*N_f[6,t,j]) #6yo first-B
    N_6NB[t+1,j] ~ dpois(mean(phi5.prob[j,1:(n_occasions-1)])*(1-mean(psi5.prob[j,1:(n_occasions-1)]))*N_f[6,t,j]) #6yo NB that was PB at 5
    ## Plus groups
    #breeders
    N_BB[t+1,j] ~ dpois(mean(phiB.prob[j,1:(n_occasions-1)])*mean(psiB.prob[j,1:(n_occasions-1)])*N_B[t,j]) # plus grp B given B
    N_BNB[t+1,j] ~ dpois(mean(phiNB.prob[j,1:(n_occasions-1)])*mean(psiNB.prob[j,1:(n_occasions-1)])*N_NB[t,j]) # plus grp B given NB
    #non breeders
    N_NBNB[t+1,j] ~ dpois(mean(phiNB.prob[j,1:(n_occasions-1)])*(1-mean(psiNB.prob[j,1:(n_occasions-1)]))*N_NB[t,j]) # plus grp NB given NB
    N_NBB[t+1,j] ~ dpois(mean(phiB.prob[j,1:(n_occasions-1)])*(1-mean(psiB.prob[j,1:(n_occasions-1)]))*N_B[t,j]) # plus grp NB given B
    #total breeders and non-breeders
    N_B[t+1,j] <- N_4B[t+1,j]+N_5B[t+1,j]+N_6B[t+1,j]+N_BB[t+1,j]+N_BNB[t+1,j] # total breeders
    N_NB[t+1,j] <- N_6NB[t+1,j]+N_NBB[t+1,j]+N_NBNB[t+1,j] # total breeders
    N_f[7,t+1,j] <- N_B[t+1,j]   #B
    N_f[8,t+1,j] <- N_NB[t+1,j]  #NB
     Ntot_f[t+1,j] <- sum(N_f[1:8,t+1,j])
    ###MALES
    N_m[1,t+1,j] ~ dbin(0.5, N_f[7,t+1,j]) #pups
    N_m[2,t+1,j] ~ dpois(mean(phiPM.prob[j,1:(n_occasions-1)])*neo_mort*N_m[1,t,j]) #yearlings
    N_m[3,t+1,j] ~ dpois(mean(phi1M.prob[j,1:(n_occasions-1)])*N_m[2,t,j]) #2yos
    N_m[4,t+1,j] ~ dpois(mean(phi2M.prob[j,1:(n_occasions-1)])*N_m[3,t,j]) #3yos
    N_m[5,t+1,j] ~ dpois(mean(phi3M.prob[j,1:(n_occasions-1)])*N_m[4,t,j]) #4yos
    N_m[6,t+1,j] ~ dpois(mean(phi4M.prob[j,1:(n_occasions-1)])*N_m[5,t,j]) #5yos
    N_A1[t+1,j] ~ dpois(mean(phi5M.prob[j,1:(n_occasions-1)])*N_m[6,t,j]) #new adults from 5yos
    N_Aplus[t+1,j] ~ dpois(mean(phiBM.prob[j,1:(n_occasions-1)])*N_m[7,t,j]) #repeat adults 7+
    N_m[7,t+1,j] <- N_A1[t+1,j] + N_Aplus[t+1,j]
    Ntot_m[t+1,j] <- sum(N_m[1:7,t+1,j])
    Ntot[t+1,j] <- Ntot_f[t+1,j] + Ntot_m[t+1,j]
  } #t extra fill years
    
    for (t in 1:(n_occasions+2)) {
      lambda[t,j] <- Ntot[t+1,j]/Ntot[t,j]
    } #lambda
    
  } #region
    
}) # mod   


##### run model ####
Q_list <- iar.Q(n_occasions-1,2)

nim.data <- list(y = y, ym = ym, pups_reg_med = pups_reg_med, 
                 pups_reg_sd = pups_reg_sd, phi_ests = phi_ests, psi_ests = psi_ests,
                 stableAge = stableAge, stableAgeM = stableAgeM,
                 z = z.st, zm = z.st.m)

nim.constants <- list(n_fem = dim(ch_fem)[1], n_m = dim(ch_m)[1], 
                      n_occasions = n_occasions, n_r = 6, G = 8, H = 7,
                      resights = res_mat, eff = eff, neo_mort = 0.95,
                      mass_f = mass_f, mass_m = mass_m, 
                      reg_f = reg_f, reg_m = reg_m, reg_fb = reg_fb, reg_mb = reg_mb,
                      fc = fc, fc_m = fc_m, 
                      v1 = v1, v2 = v2, v3 = v3, v4 = v4, v5 = v5, v6 = v6, vB = vB, v8 = v8,
                      v2m = v2m, v3m = v3m, v4m = v4m, v5m = v5m, v6m = v6m, v7m = v7m, 
                      len_v1 = len_v1, len_v2 = len_v2, len_v3 = len_v3, len_v4 = len_v4, 
                      len_v5 = len_v5, len_v6 = len_v6, len_vB = len_vB, len_v8 = len_v8,
                      len_v2m = len_v2m, len_v3m = len_v3m, len_v4m = len_v4m, len_v5m = len_v5m, 
                      len_v6m = len_v6m, len_v7m = len_v7m,
                      L=Q_list$L, adj=Q_list$adj,
                      weights=Q_list$weights, num=Q_list$num, c=Q_list$c)

inits <- list(int.phiP = phi_ests[1,1], int.phiPM = phi_ests[8,1], 
              int.phi1 = phi_ests[2,1], int.phi1M = phi_ests[9,1],
              int.phi2 = phi_ests[3,1], int.phi2M = phi_ests[10,1], 
              int.phi3 = phi_ests[4,1], int.phi3M = phi_ests[11,1],
              int.phi4 = phi_ests[5,1], int.phi4M = phi_ests[12,1],
              int.phi5 = phi_ests[6,1], int.phi5M = phi_ests[13,1],
              int.phiB = phi_ests[7,1], int.phiNB = phi_ests[7,1], int.phiBM = phi_ests[14,1],
              int.psi3 = psi_ests[1,1], int.psi4 = psi_ests[2,1], int.psi5 = psi_ests[3,1], 
              int.psiB = psi_ests[4,1], int.psiNB = psi_ests[5,1],
              int.p1 = 0.7, int.p2 = 0.7, int.p3 = 0.7, int.p4 = 0.7, int.p5 = 0.7,
              int.pB = 0.9, int.pNB = 0.5, int.p1M = 0.7, int.p2M = 0.7, int.p3M = 0.7, int.p4M = 0.7, 
              int.p5M = 0.7, int.pBM = 0.7,
              eps.p = c(rep(0, n_occasions)), 
              epsP = array(0, dim = c(6, n_occasions-1)), 
              eps1 = array(0, dim = c(6, n_occasions-1)),
              eps2 = array(0, dim = c(6, n_occasions-1)),
              
              epsPB = array(0, dim = c(2, n_occasions-1)),
              epsB = array(0, dim = c(6, n_occasions-1)),
              eps.psiPB = array(0, dim = c(4, n_occasions-1)),
              eps.psiB = array(0, dim = c(4, n_occasions-1)),
              eps.psiNB = array(0, dim = c(4, n_occasions-1)),
              p.delB = c(0.4, 0.5, 0.75), 
              b.massP = 0, b.massPM = 0, 
              b.mass1 = 0, b.mass1M = 0, 
              b.regP = c(rep(0,6)), b.reg1 = c(rep(0,6)), b.reg2 = c(rep(0,6)), 
              b.regPB = c(rep(0,2)), 
              p.delB = c(0.4, 0.5, 0.75),
              z = z.init, zm = z.init.m)

### parameters
params <- c('phiP.prob', 'phi1.prob', 'phi2.prob', 'phi3.prob', 'phi4.prob', 'phi5.prob',
            'phiPM.prob', 'phi1M.prob', 'phi2M.prob', 'phi3M.prob', 'phi4M.prob', 'phi5M.prob',
            'phiB.prob', 'phiNB.prob', 'phiBM.prob',
            'psi3.prob', 'psi4.prob', 'psi5.prob', 'psiB.prob', 'psiNB.prob',
            'b.delB', 'p.delB', 'b.eff', 
            'Ntot', 'Ntot_f', 'N_f', 'Ntot_m', 'N_m')

### run model
ni = 35000; nc = 3; nb = 20000; nt = 2; adaptInterval = 100

t.start <- Sys.time() 

cores=detectCores() 
used.cores = min(nc, cores) 
cl <- makeCluster(nc, setup_strategy = "sequential") 
registerDoParallel(cl) 

foreach(i = 1:nc) %dopar% { 
  library(nimble)
  library(here)
  source(here("scripts", "nimbleFunctions.R"))
  
  Rmodel <- nimbleModel(code=SSL_IPM, constants=nim.constants, 
                        data=nim.data, calculate=F, check=F, inits=inits)
  
  conf <- configureMCMC(Rmodel,monitors=params,control = list(adaptInterval = adaptInterval), 
                        thin=nt, useConjugacy = FALSE, enableWAIC = T)
  Rmcmc <- buildMCMC(conf)  #produces an uncompiled R mcmc function
  Cmodel <- compileNimble(Rmodel)
  Cmcmc <- compileNimble(Rmcmc, project = Rmodel)
  
  out <- runMCMC(Cmcmc, niter = ni, nburnin = nb , nchains = 1, inits = inits,
                 setSeed = FALSE, progressBar = TRUE, samplesAsCodaMCMC = TRUE) 
  
  version <- 'null'
  saveRDS(out, here('results', 'best', paste("out.parallel-", version, "spStable-",i,".RDS", sep = ""))) 
  
} # closes parallel loop

stopCluster(cl)
t.end <- Sys.time() 
(runTime <- t.end - t.start)

version <- 'null'

out_1 <- readRDS(here::here('results', 'best', paste("out.parallel-", version, "spStable-1.RDS", sep = "")))
out_2 <- readRDS(here::here('results', 'best', paste("out.parallel-", version, "spStable-2.RDS", sep = "")))
out_3 <- readRDS(here::here('results', 'best', paste("out.parallel-", version, "spStable-3.RDS", sep = "")))

# combine them and make an mcmc object
library(coda)
out <- list(`out_1`, `out_2`, `out_3`) %>% as.mcmc.list()


```

```{r option 2.2}

SSL_IPM <- nimbleCode({
  
  # Priors and constraints
  for (i in 1:n_fem) { #females
    for (t in 1:(n_occasions - 1)) {
      logit(phiP[i,t]) <- mu.P + b.massP*mass_f[i] + b.regP[reg_f[i]] + epsP[reg_f[i],t]   
      logit(phi1[i,t]) <- mu.1 + b.mass1*mass_f[i] + b.reg1[reg_f[i]] + eps1[reg_f[i],t]  
      logit(phi2[i,t]) <- mu.2 + b.mass1*mass_f[i] + b.reg2[reg_f[i]] + eps2[reg_f[i],t] 
      logit(phi3[i,t]) <- mu.3 + b.regPB[reg_fb[i]] + epsPB[reg_fb[i],t] 
      logit(phi4[i,t]) <- mu.4 + b.regPB[reg_fb[i]] + epsPB[reg_fb[i],t]
      logit(phi5[i,t]) <- mu.5 + b.regPB[reg_fb[i]] + epsPB[reg_fb[i],t] 
      logit(phiB[i,t]) <- mu.B + b.regB[reg_fb[i]] + epsB[reg_f[i],t]
      logit(phiNB[i,t]) <- mu.NB 
      
      logit(psi3[i,t]) <- mu.psi3 + b.reg.psi3[reg_f[i]] #+ eps.psiPB[reg_fb[i],t] 
      logit(psi4[i,t]) <- mu.psi4 + b.reg.psi4[reg_f[i]] + eps.psiPB[reg_fb[i],t]  
      logit(psi5[i,t]) <- mu.psi5 + b.reg.psi5[reg_f[i]] #+ eps.psiPB[reg_fb[i],t] 
      logit(psiB[i,t]) <- mu.psiB + b.reg.psiB[reg_f[i]] + eps.psiB[reg_fb[i],t]   
      logit(psiNB[i,t]) <- mu.psiNB + b.reg.psiNB[reg_f[i]] #+ eps.psiNB[reg_fb[i],t] 
      
      logit(p1[i,t]) <- mu.p1 + b.eff[eff[t]] + eps.p[t] 
      logit(p2[i,t]) <- mu.p2 + b.eff[eff[t]] + eps.p[t]
      logit(p3[i,t]) <- mu.p3 + b.eff[eff[t]] + eps.p[t]
      logit(p4[i,t]) <- mu.p4 + b.eff[eff[t]] + eps.p[t]
      logit(p5[i,t]) <- mu.p5 + b.eff[eff[t]] + eps.p[t]
      logit(pB[i,t]) <- mu.pB + b.eff[eff[t]] + eps.p[t]
      logit(pNB[i,t]) <- mu.pNB + b.eff[eff[t]] + eps.p[t]
      logit(delB[i,t]) <- b.delB[resights[i,t]]
    } #t 
  } #i fem
  
  for (i in 1:n_m) { #males
    for (t in 1:(n_occasions - 1)) {
      logit(phiPM[i,t]) <- mu.PM + b.massPM*mass_m[i] + b.regP[reg_m[i]] + epsP[reg_m[i],t]    
      logit(phi1M[i,t]) <- mu.1M + b.mass1M*mass_m[i] + b.reg1[reg_m[i]] + eps1[reg_m[i],t]    
      logit(phi2M[i,t]) <- mu.2M + b.mass1M*mass_m[i] + b.reg2[reg_m[i]] + eps2[reg_m[i],t]   
      logit(phi3M[i,t]) <- mu.3M + b.regPB[reg_mb[i]] + epsPB[reg_mb[i],t] 
      logit(phi4M[i,t]) <- mu.4M + b.regPB[reg_mb[i]] + epsPB[reg_mb[i],t] 
      logit(phi5M[i,t]) <- mu.5M + b.regPB[reg_mb[i]] + epsPB[reg_mb[i],t] 
      logit(phiBM[i,t]) <- mu.BM + b.regB[reg_mb[i]] + epsB[reg_mb[i],t]
      
      logit(p1M[i,t]) <- mu.p1M + b.eff[eff[t]] + eps.p[t]
      logit(p2M[i,t]) <- mu.p2M + b.eff[eff[t]] + eps.p[t]
      logit(p3M[i,t]) <- mu.p3M + b.eff[eff[t]] + eps.p[t]
      logit(p4M[i,t]) <- mu.p4M + b.eff[eff[t]] + eps.p[t]
      logit(p5M[i,t]) <- mu.p5M + b.eff[eff[t]] + eps.p[t]
      logit(pBM[i,t]) <- mu.pBM + b.eff[eff[t]] + eps.p[t]
    } #t male
  } #i male
  
  ### Priors
  #fixed categorical effect of natal region
  b.regP[2] <- 0
  b.reg1[2] <- 0
  b.reg2[2] <- 0
  b.regPB[1] <- 0
  b.regB[1] <- 0
  b.reg.psi3[2] <- 0
  b.reg.psi4[2] <- 0
  b.reg.psi5[2] <- 0
  b.reg.psiB[2] <- 0
  b.reg.psiNB[2] <- 0
  
  for (r in c(1,3,4,5,6)) {
  b.regP[r] ~ dnorm(0, sd = s.regP)
  b.reg1[r] ~ dnorm(0, sd = s.reg1)
  b.reg2[r] ~ dnorm(0, sd = s.reg2)
  
  b.reg.psi3[r] ~ dnorm(0, sd = s.psiPB)
  b.reg.psi4[r] ~ dnorm(0, sd = s.psiPB)
  b.reg.psi5[r] ~ dnorm(0, sd = s.psiPB)
  b.reg.psiB[r] ~ dnorm(0, sd = s.psiB)
  b.reg.psiNB[r] ~ dnorm(0, sd = s.psiB)
  }
  
  b.regPB[2] ~ dnorm(0, sd = s.regPB)
  b.regB[2] ~ dnorm(0, sd = s.regB)
  
  s.regP ~ dexp(1)
  s.reg1 ~ dexp(1)
  s.reg2 ~ dexp(1)
  s.regPB ~ dexp(1)
  s.regB ~ dexp(1)
  # s.regNB ~ dexp(1)
  s.psiPB ~ dexp(1)
  s.psiB ~ dexp(1)
  # s.eps.reg ~ dexp(1)
 
   for (j in 1:4) {
    epsP[j,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.epsP, c)
    eps1[j,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.eps1, c)
    eps2[j,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.eps2, c)
    epsB[j,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.epsB, c)
  } 
  
  epsP[5:6,1:(n_occasions-1)] <- 0
  eps1[5:6,1:(n_occasions-1)] <- 0
  eps2[5:6,1:(n_occasions-1)] <- 0
  epsB[5:6,1:(n_occasions-1)] <- 0
  
  epsPB[1,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.epsPB, c)
  epsPB[2,1:(n_occasions-1)] <- 0
  
  eps.psiPB[1,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.eps.psi, c)
  eps.psiB[1,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.eps.psi, c)
  
  eps.psiPB[2,1:(n_occasions-1)] <- 0
  eps.psiB[2,1:(n_occasions-1)] <- 0
  
  t.epsP <- 1/(s.epsP*s.epsP) #precision
  s.epsP ~ dexp(1) #standard deviation
  t.eps1 <- 1/(s.eps1*s.eps1)
  s.eps1 ~ dexp(1)
  t.eps2 <- 1/(s.eps2*s.eps2)
  s.eps2 ~ dexp(1)
  t.epsPB <- 1/(s.epsPB*s.epsPB)
  s.epsPB ~ dexp(1)
  t.epsB <- 1/(s.epsB*s.epsB)
  s.epsB ~ dexp(1)
  t.eps.psi <- 1/(s.eps.psi*s.eps.psi)
  s.eps.psi ~ dexp(1)
    
    for (t in 1:(n_occasions)) {
      eps.p[t] ~ dnorm(0, sd = sigma.p)
    }
    sigma.p ~ dexp(1)
  
  #intercepts  
  mu.psi3 <- log(int.psi3/(1-int.psi3))
  mu.psi4 <- log(int.psi4/(1-int.psi4))
  mu.psi5 <- log(int.psi5/(1-int.psi5))
  mu.psiB <- log(int.psiB/(1-int.psiB))
  mu.psiNB <- log(int.psiNB/(1-int.psiNB))
  int.psi3 ~ T(dnorm(psi_ests[1,1], sd = psi_ests[1,2]),0,1)
  int.psi4 ~ T(dnorm(psi_ests[2,1], sd = psi_ests[2,2]),0,1)
  int.psi5 ~ T(dnorm(psi_ests[3,1], sd = psi_ests[3,2]),0,1)
  int.psiB ~ T(dnorm(psi_ests[4,1], sd = psi_ests[4,2]),0,1)
  int.psiNB ~ T(dnorm(psi_ests[5,1], sd = psi_ests[5,2]),0,1)
  mu.p1 <- log(int.p1/(1 - int.p1))
  mu.p2 <- log(int.p2/(1 - int.p2))
  mu.p3 <- log(int.p3/(1 - int.p3))
  mu.p4 <- log(int.p4/(1 - int.p4))
  mu.p5 <- log(int.p5/(1 - int.p5))
  mu.pB <- log(int.pB/(1 - int.pB))
  mu.pNB <- log(int.pNB/(1 - int.pNB))
  mu.p1M <- log(int.p1M/(1 - int.p1M))
  mu.p2M <- log(int.p2M/(1 - int.p2M))
  mu.p3M <- log(int.p3M/(1 - int.p3M))
  mu.p4M <- log(int.p4M/(1 - int.p4M))
  mu.p5M <- log(int.p5M/(1 - int.p5M))
  mu.pBM <- log(int.pBM/(1 - int.pBM))
  int.p1 ~ dunif(0,1)
  int.p2 ~ dunif(0,1)
  int.p3 ~ dunif(0,1)
  int.p4 ~ dunif(0,1)
  int.p5 ~ dunif(0,1)
  int.pB ~ dunif(0,1)
  int.pNB ~ dunif(0,1)
  int.p1M ~ dunif(0,1)
  int.p2M ~ dunif(0,1)
  int.p3M ~ dunif(0,1)
  int.p4M ~ dunif(0,1)
  int.p5M ~ dunif(0,1)
  int.pBM ~ dunif(0,1)
  #phi
  mu.P <- log(int.phiP/(1 - int.phiP))
  mu.1 <- log(int.phi1/(1 - int.phi1))
  mu.2 <- log(int.phi2/(1 - int.phi2))
  mu.3 <- log(int.phi3/(1 - int.phi3))
  mu.4 <- log(int.phi4/(1 - int.phi4))
  mu.5 <- log(int.phi5/(1 - int.phi5))
  mu.B <- log(int.phiB/(1 - int.phiB))
  mu.NB <- log(int.phiNB/(1 - int.phiNB))
  mu.PM <- log(int.phiPM/(1 - int.phiPM))
  mu.1M <- log(int.phi1M/(1 - int.phi1M))
  mu.2M <- log(int.phi2M/(1 - int.phi2M))
  mu.3M <- log(int.phi3M/(1 - int.phi3M))
  mu.4M <- log(int.phi4M/(1 - int.phi4M))
  mu.5M <- log(int.phi5M/(1 - int.phi5M))
  mu.BM <- log(int.phiBM/(1 - int.phiBM)) 
  int.phiP ~ T(dnorm(phi_ests[1,1], sd = phi_ests[1,2]),0,1)
  int.phi1 ~ T(dnorm(phi_ests[2,1], sd = phi_ests[2,2]),0,1)
  int.phi2 ~ T(dnorm(phi_ests[3,1], sd = phi_ests[3,2]),0,1)
  int.phi3 ~ T(dnorm(phi_ests[4,1], sd = phi_ests[4,2]),0,1)
  int.phi4 ~ T(dnorm(phi_ests[5,1], sd = phi_ests[5,2]),0,1)
  int.phi5 ~ T(dnorm(phi_ests[6,1], sd = phi_ests[6,2]),0,1)
  int.phiB ~ T(dnorm(phi_ests[7,1], sd = phi_ests[7,2]),0,1)
  int.phiNB ~ T(dnorm(phi_ests[7,1], sd = phi_ests[7,2]),0,1)
  int.phiPM ~ T(dnorm(phi_ests[8,1], sd = phi_ests[8,2]),0,1)
  int.phi1M ~ T(dnorm(phi_ests[9,1], sd = phi_ests[9,2]),0,1)
  int.phi2M ~ T(dnorm(phi_ests[10,1], sd = phi_ests[10,2]),0,1)
  int.phi3M ~ T(dnorm(phi_ests[11,1], sd = phi_ests[11,2]),0,1)
  int.phi4M ~ T(dnorm(phi_ests[12,1], sd = phi_ests[12,2]),0,1)
  int.phi5M ~ T(dnorm(phi_ests[13,1], sd = phi_ests[13,2]),0,1)
  int.phiBM ~ T(dnorm(phi_ests[14,1], sd = phi_ests[14,2]),0,1)
  
  p.delB[1] ~ dunif(0,1)
  b.delB[1] <- log(p.delB[1]/(1-p.delB[1]))
  p.delB[2] ~ dunif(0,1)
  b.delB[2] <- log(p.delB[2]/(1-p.delB[2]))
  p.delB[3] ~ dunif(0,1)
  b.delB[3] <- log(p.delB[3]/(1-p.delB[3]))
  b.delB[4] <- -5 #0 on probability scale
  
  b.eff[1] <- 0
  b.eff[2] ~ dnorm(0, 0.001)
    
    #back-transform everything
       for (t in 1:(n_occasions-1)){
    for (r in 1:6) {
      phiP.prob[r,t] <- 1/(1+exp(-(mu.P + epsP[r,t] + b.regP[r])))
      phiPM.prob[r,t] <- 1/(1+exp(-(mu.PM + epsP[r,t] + b.regP[r])))
      phi1.prob[r,t] <- 1/(1+exp(-(mu.1 + eps1[r,t] + b.reg1[r])))
      phi1M.prob[r,t] <- 1/(1+exp(-(mu.1M + eps1[r,t] + b.reg1[r])))
      phi2.prob[r,t] <- 1/(1+exp(-(mu.2 + eps2[r,t] + b.reg2[r])))
      phi2M.prob[r,t] <- 1/(1+exp(-(mu.2M + eps2[r,t] + b.reg2[r])))
      
    }

      for (r in 1:4) {
      phi3.prob[r,t] <- 1/(1+exp(-(mu.3 + epsPB[1,t] + b.regPB[1])))
      phi3M.prob[r,t] <- 1/(1+exp(-(mu.3M + epsPB[1,t] + b.regPB[1])))
      phi4.prob[r,t] <- 1/(1+exp(-(mu.4 + epsPB[1,t] + b.regPB[1])))
      phi4M.prob[r,t] <- 1/(1+exp(-(mu.4M + epsPB[1,t] + b.regPB[1])))
      phi5.prob[r,t] <- 1/(1+exp(-(mu.5 + epsPB[1,t] + b.regPB[1])))
      phi5M.prob[r,t] <- 1/(1+exp(-(mu.5M + epsPB[1,t] + b.regPB[1])))
      phiB.prob[r,t] <- 1/(1+exp(-(mu.B + epsB[r,t] + b.regB[1])))
      
      phiNB.prob[r,t] <- 1/(1+exp(-(mu.NB)))
      phiBM.prob[r,t] <- 1/(1+exp(-(mu.BM + b.regB[1] + epsB[1,t])))
      psi3.prob[r,t] <- 1/(1+exp(-(mu.psi3 + b.reg.psi3[r])))
      psi4.prob[r,t] <- 1/(1+exp(-(mu.psi4 + b.reg.psi4[r] + eps.psiPB[1,t])))
      psi5.prob[r,t] <- 1/(1+exp(-(mu.psi5 + b.reg.psi5[r])))
      psiB.prob[r,t] <- 1/(1+exp(-(mu.psiB + b.reg.psiB[r] + eps.psiB[1,t])))
      psiNB.prob[r,t] <- 1/(1+exp(-(mu.psiNB + b.reg.psiNB[r])))
      }
      for (r in 5:6) {
      phi3.prob[r,t] <- 1/(1+exp(-(mu.3 + epsPB[2,t] + b.regPB[2])))
      phi3M.prob[r,t] <- 1/(1+exp(-(mu.3M + epsPB[2,t] + b.regPB[2])))
      phi4.prob[r,t] <- 1/(1+exp(-(mu.4 + epsPB[2,t] + b.regPB[2])))
      phi4M.prob[r,t] <- 1/(1+exp(-(mu.4M + epsPB[2,t] + b.regPB[2])))
      phi5.prob[r,t] <- 1/(1+exp(-(mu.5 + epsPB[2,t] + b.regPB[2])))
      phi5M.prob[r,t] <- 1/(1+exp(-(mu.5M + epsPB[2,t] + b.regPB[2])))
      phiB.prob[r,t] <- 1/(1+exp(-(mu.B + epsB[r,t] + b.regB[2])))
      phiNB.prob[r,t] <- 1/(1+exp(-(mu.NB)))
      psi3.prob[r,t] <- 1/(1+exp(-(mu.psi3 + b.reg.psi3[r])))
      psi4.prob[r,t] <- 1/(1+exp(-(mu.psi4 + b.reg.psi4[r] + eps.psiPB[2,t])))
      psi5.prob[r,t] <- 1/(1+exp(-(mu.psi5 + b.reg.psi5[r])))
      psiB.prob[r,t] <- 1/(1+exp(-(mu.psiB + b.reg.psiB[r] + eps.psiB[2,t])))
      psiNB.prob[r,t] <- 1/(1+exp(-(mu.psiNB + b.reg.psiNB[r])))
      }
         
    } #t
  
    #covs - phi
    b.massP ~ dnorm(0, sd = s.massP)
    s.massP ~ dexp(1)
    b.massPM ~ dnorm(0, sd = s.massPM)
    s.massPM ~ dexp(1)
    b.mass1 ~ dnorm(0, sd = s.mass1)
    s.mass1 ~ dexp(1)
    b.mass1M ~ dnorm(0, sd = s.mass1M)
    s.mass1M ~ dexp(1)
    
    #likelihood
for (i in 1:n_fem) { #females
    z[i, fc[i]:fc[i]] <- 1 #pups at first capture
for (t in (fc[i] + 1):n_occasions) {
      z[i,t] ~ dcat(state_probs[i,t-1,1:12])
      y[i,t] ~ dcat(event_probs[i,t,1:11])
      
    state_probs[i,t-1,1:12] <- getPHI_f(z = z[i,t-1], 
                                      phiP = phiP[i,t-1], phi1 = phi1[i,t-1], phi2 = phi2[i,t-1], 
                                      phi3 = phi3[i,t-1], phi4 = phi4[i,t-1], phi5 = phi5[i,t-1], 
                                      phiB = phiB[i,t-1], phiNB = phiNB[i,t-1],
                                      psi3 = psi3[i,t-1], psi4 = psi4[i,t-1],
                                      psi5 = psi5[i,t-1], psiB = psiB[i,t-1], psiNB = psiNB[i,t-1])
    
    event_probs[i,t,1:11] <- getP_f(z = z[i,t], 
                                    p1 = p1[i,t-1], p2 = p2[i,t-1], p3 = p3[i,t-1], 
                                    p4 = p4[i,t-1], p5 = p5[i,t-1],
                                    pB = pB[i,t-1], pNB = pNB[i,t-1], delB = delB[i,t-1])
    } #t likelihood fem
} #i likelihood fem
    
   for (i in 1:n_m) { #males
    zm[i, fc_m[i]:fc_m[i]] <- 1
  for (t in (fc_m[i] + 1):n_occasions) {
    zm[i,t] ~ dcat(state_probs_m[i, t-1, 1:8])
    ym[i,t] ~ dcat(event_probs_m[i,t,1:8])
    
    state_probs_m[i,t-1,1:8] <- getPHI_m(z = zm[i,t-1], 
                                      phiPM = phiPM[i,t-1], phi1M = phi1M[i,t-1], phi2M = phi2M[i,t-1], 
                                      phi3M = phi3M[i,t-1], phi4M = phi4M[i,t-1], phi5M = phi5M[i,t-1], 
                                      phiBM = phiBM[i,t-1])
    event_probs_m[i,t,1:8] <- getP_m(z = zm[i,t], 
                                    p1M = p1M[i,t-1], p2M = p2M[i,t-1], p3M = p3M[i,t-1], 
                                    p4M = p4M[i,t-1], p5M = p5M[i,t-1], pBM = pBM[i,t-1])
    } # likelihood t male
   } #likelihood i male
    
########################### population model ################################  

    # sigma.popInit ~ dexp(1)
    
    for (j in 1:n_r) {
   # total females
   # Ntot_f[1,j] ~ dpois(round(np_reg_med[1,j]*prop_f))
   # lNtot_f[j] ~ dlnorm(meanlog = log(np_reg_med[1,j]*prop_f), sdlog = log(sigma.popInit))
   # Ntot_f[1,j] <- round(exp(lNtot_f[j]))
   
   # Ntot_f[1,j] ~ dnorm(np_reg_med[1,j]*prop_f, sd = sigma.popInit)
   # Ntot_f[1,j] <- round(np_reg_med[1,j]*prop_f)
      
  # establish first year of population using conditional binomials
   # N_f[1,1,j] <- round(pups_reg_med[1,j]/2) #pups in 2000
      
      N_f[1,1,j] ~ dcat(v1[j,1:len_v1])
      N_f[2,1,j] ~ dcat(v2[j,1:len_v2])
      N_f[3,1,j] ~ dcat(v3[j,1:len_v3])
      N_f[4,1,j] ~ dcat(v4[j,1:len_v4])
      N_f[5,1,j] ~ dcat(v5[j,1:len_v5])
      N_f[6,1,j] ~ dcat(v6[j,1:len_v6])
      N_f[7,1,j] ~ dcat(vB[j,1:len_vB])
      N_f[8,1,j] ~ dcat(v8[j,1:len_v8])
      Ntot_f[1,j] <- sum(N_f[1:8,1,j])
 
      N_m[1,1,j] ~ dcat(v1[j,1:len_v1])
      N_m[2,1,j] ~ dcat(v2m[j,1:len_v2m])
      N_m[3,1,j] ~ dcat(v3m[j,1:len_v3m])
      N_m[4,1,j] ~ dcat(v4m[j,1:len_v4m])
      N_m[5,1,j] ~ dcat(v5m[j,1:len_v5m])
      N_m[6,1,j] ~ dcat(v6m[j,1:len_v6m])
      N_m[7,1,j] ~ dcat(v7m[j,1:len_v7m])
      Ntot_m[1,j] <- sum(N_m[1:7,1,j])
   
   # for(g in 2:(G-1)){
   #  N_f[g,1,j] ~ dbin(stableAge[g]/(1-sum(stableAge[1:(g-1)])), Ntot_f[1,j] - sum(N_f[1:(g-1),1,j]) )
   # }
   # 
   # # group G: deterministic
   # N_f[G,1,j] <- Ntot_f[1,j] - sum(N_f[1:(G-1),1,j])
      
   #  #total breeders and non-breeders
    N_B[1,j] <-  N_f[7,1,j]  # total breeders
    N_NB[1,j] <- N_f[8,1,j] # total NB
    
    ###MALES
    # Ntot_m[1,j] ~ dpois(np_reg_med[1,j]*(1-prop_f)) #total males
    # lNtot_m[j] ~ dlnorm(meanlog = log(np_reg_med[1,j]*(1-prop_f)), sdlog = log(sigma.popInit)) 
    # Ntot_m[1,j] <- round(exp(lNtot_m[j]))
    
     # Ntot_m[1,j] ~ dnorm(np_reg_med[1,j]*(1-prop_f), sd = sigma.popInit)
   #  Ntot_m[1,j] <- round(np_reg_med[1,j]*(1-prop_f))
   # 
   #  N_m[1,1,j] <- round(pups_reg_med[1,j]/2) #pups
   # 
   #  for(h in 2:(H-1)){
   #  N_m[h,1,j] ~ dbin(stableAgeM[h]/(1-sum(stableAgeM[1:(h-1)])), Ntot_m[1,j] - sum(N_m[1:(h-1),1,j]) )
   #  }
   # 
   # # group H: deterministic
   # N_m[H,1,j] <- Ntot_m[1,j] - sum(N_m[1:(H-1),1,j])
    N_A1[1,j] <- N_m[6,1,j] #new adults from 5yos
    N_Aplus[1,j] <- N_m[7,1,j]  #repeat adults 7+
    Ntot[1,j] <- Ntot_f[1,j] + Ntot_m[1,j]
    
    for (t in 1:(n_occasions-1)) { #t = 1 fills t+1 == Ntot[2001]; t = 18 fills t+1 == Ntot[2018]
    pups_reg_med[t+1,j] ~ dnorm(N_f[1,t+1,j]+N_m[1,t+1,j], sd = pups_reg_sd[t+1,j])

    ###FEMALES
    N_f[1,t+1,j] ~ dbin(0.5, N_f[7,t+1,j]) # or deterministic N_f[1,t+1,j] <- N_f[7,t+1,j]*0.5
    N_f[2,t+1,j] ~ dpois(phiP.prob[j,t]*neo_mort*N_f[1,t,j]) #yearlings
    N_f[3,t+1,j] ~ dpois(phi1.prob[j,t]*N_f[2,t,j]) #2yos
    N_f[4,t+1,j] ~ dpois(phi2.prob[j,t]*N_f[3,t,j]) #3yos
    N_f[5,t+1,j] ~ dpois(phi3.prob[j,t]*(1-psi3.prob[j,t])*N_f[4,t,j]) #4yo PB
    N_f[6,t+1,j] ~ dpois(phi4.prob[j,t]*(1-psi4.prob[j,t])*N_f[5,t,j]) #5yo PB
    N_4B[t+1,j] ~ dpois(phi3.prob[j,t]*psi3.prob[j,t]*N_f[4,t,j]) #4yo breeders
    N_5B[t+1,j] ~ dpois(phi4.prob[j,t]*psi4.prob[j,t]*N_f[5,t,j]) #5yo first-B
    N_6B[t+1,j] ~ dpois(phi5.prob[j,t]*psi5.prob[j,t]*N_f[6,t,j]) #6yo first-B
    N_6NB[t+1,j] ~ dpois(phi5.prob[j,t]*(1-psi5.prob[j,t])*N_f[6,t,j]) #6yo NB that was PB at 5

    ## Plus groups
    #breeders
    N_BB[t+1,j] ~ dpois(phiB.prob[j,t]*psiB.prob[j,t]*N_B[t,j]) # plus grp B given B
    N_BNB[t+1,j] ~ dpois(phiNB.prob[j,t]*psiNB.prob[j,t]*N_NB[t,j]) # plus grp B given NB
    #non breeders
    N_NBNB[t+1,j] ~ dpois(phiNB.prob[j,t]*(1-psiNB.prob[j,t])*N_NB[t,j]) # plus grp NB given NB
    N_NBB[t+1,j] ~ dpois(phiB.prob[j,t]*(1-psiB.prob[j,t])*N_B[t,j]) # plus grp NB given B

    #total breeders and non-breeders
    N_B[t+1,j] <- N_4B[t+1,j]+N_5B[t+1,j]+N_6B[t+1,j]+N_BB[t+1,j]+N_BNB[t+1,j] # total breeders
    N_NB[t+1,j] <- N_6NB[t+1,j]+N_NBB[t+1,j]+N_NBNB[t+1,j] # total breeders
    N_f[7,t+1,j] <- N_B[t+1,j]   #B
    N_f[8,t+1,j] <- N_NB[t+1,j]  #NB
     Ntot_f[t+1,j] <- sum(N_f[1:8,t+1,j])

    ###MALES
    N_m[1,t+1,j] ~ dbin(0.5, N_f[7,t+1,j]) #pups
    N_m[2,t+1,j] ~ dpois(phiPM.prob[j,t]*neo_mort*N_m[1,t,j]) #yearlings
    N_m[3,t+1,j] ~ dpois(phi1M.prob[j,t]*N_m[2,t,j]) #2yos
    N_m[4,t+1,j] ~ dpois(phi2M.prob[j,t]*N_m[3,t,j]) #3yos
    N_m[5,t+1,j] ~ dpois(phi3M.prob[j,t]*N_m[4,t,j]) #4yos
    N_m[6,t+1,j] ~ dpois(phi4M.prob[j,t]*N_m[5,t,j]) #5yos
    N_A1[t+1,j] ~ dpois(phi5M.prob[j,t]*N_m[6,t,j]) #new adults from 5yos
    N_Aplus[t+1,j] ~ dpois(phiBM.prob[j,t]*N_m[7,t,j]) #repeat adults 7+
    N_m[7,t+1,j] <- N_A1[t+1,j] + N_Aplus[t+1,j]
    Ntot_m[t+1,j] <- sum(N_m[1:7,t+1,j])
    Ntot[t+1,j] <- Ntot_f[t+1,j] + Ntot_m[t+1,j]
  } #t

    #fill up to aerial survey data in 2021
        for (t in n_occasions:(n_occasions+2)) { #t = 19 fills t+1 == Ntot[2019]; t = 21 fills t+1 == Ntot[2021]
    pups_reg_med[t+1,j] ~ dnorm(N_f[1,t+1,j]+N_m[1,t+1,j], sd = pups_reg_sd[t+1,j])

    ###FEMALES
    N_f[1,t+1,j] ~ dbin(0.5, N_f[7,t+1,j]) # or deterministic N_f[1,t+1,j] <- N_f[7,t+1,j]*0.5
    N_f[2,t+1,j] ~ dpois(mean(phiP.prob[j,1:(n_occasions-1)])*neo_mort*N_f[1,t,j]) #yearlings
    N_f[3,t+1,j] ~ dpois(mean(phi1.prob[j,1:(n_occasions-1)])*N_f[2,t,j]) #2yos
    N_f[4,t+1,j] ~ dpois(mean(phi2.prob[j,1:(n_occasions-1)])*N_f[3,t,j]) #3yos
    N_f[5,t+1,j] ~ dpois(mean(phi3.prob[j,1:(n_occasions-1)])*(1-mean(psi3.prob[j,1:(n_occasions-1)]))*N_f[4,t,j]) #4yo PB
    N_f[6,t+1,j] ~ dpois(mean(phi4.prob[j,1:(n_occasions-1)])*(1-mean(psi4.prob[j,1:(n_occasions-1)]))*N_f[5,t,j]) #5yo PB
    N_4B[t+1,j] ~ dpois(mean(phi3.prob[j,1:(n_occasions-1)])*mean(psi3.prob[j,1:(n_occasions-1)])*N_f[4,t,j]) #4yo breeders
    N_5B[t+1,j] ~ dpois(mean(phi4.prob[j,1:(n_occasions-1)])*mean(psi4.prob[j,1:(n_occasions-1)])*N_f[5,t,j]) #5yo first-B
    N_6B[t+1,j] ~ dpois(mean(phi5.prob[j,1:(n_occasions-1)])*mean(psi5.prob[j,1:(n_occasions-1)])*N_f[6,t,j]) #6yo first-B
    N_6NB[t+1,j] ~ dpois(mean(phi5.prob[j,1:(n_occasions-1)])*(1-mean(psi5.prob[j,1:(n_occasions-1)]))*N_f[6,t,j]) #6yo NB that was PB at 5
    ## Plus groups
    #breeders
    N_BB[t+1,j] ~ dpois(mean(phiB.prob[j,1:(n_occasions-1)])*mean(psiB.prob[j,1:(n_occasions-1)])*N_B[t,j]) # plus grp B given B
    N_BNB[t+1,j] ~ dpois(mean(phiNB.prob[j,1:(n_occasions-1)])*mean(psiNB.prob[j,1:(n_occasions-1)])*N_NB[t,j]) # plus grp B given NB
    #non breeders
    N_NBNB[t+1,j] ~ dpois(mean(phiNB.prob[j,1:(n_occasions-1)])*(1-mean(psiNB.prob[j,1:(n_occasions-1)]))*N_NB[t,j]) # plus grp NB given NB
    N_NBB[t+1,j] ~ dpois(mean(phiB.prob[j,1:(n_occasions-1)])*(1-mean(psiB.prob[j,1:(n_occasions-1)]))*N_B[t,j]) # plus grp NB given B
    #total breeders and non-breeders
    N_B[t+1,j] <- N_4B[t+1,j]+N_5B[t+1,j]+N_6B[t+1,j]+N_BB[t+1,j]+N_BNB[t+1,j] # total breeders
    N_NB[t+1,j] <- N_6NB[t+1,j]+N_NBB[t+1,j]+N_NBNB[t+1,j] # total breeders
    N_f[7,t+1,j] <- N_B[t+1,j]   #B
    N_f[8,t+1,j] <- N_NB[t+1,j]  #NB
     Ntot_f[t+1,j] <- sum(N_f[1:8,t+1,j])
    ###MALES
    N_m[1,t+1,j] ~ dbin(0.5, N_f[7,t+1,j]) #pups
    N_m[2,t+1,j] ~ dpois(mean(phiPM.prob[j,1:(n_occasions-1)])*neo_mort*N_m[1,t,j]) #yearlings
    N_m[3,t+1,j] ~ dpois(mean(phi1M.prob[j,1:(n_occasions-1)])*N_m[2,t,j]) #2yos
    N_m[4,t+1,j] ~ dpois(mean(phi2M.prob[j,1:(n_occasions-1)])*N_m[3,t,j]) #3yos
    N_m[5,t+1,j] ~ dpois(mean(phi3M.prob[j,1:(n_occasions-1)])*N_m[4,t,j]) #4yos
    N_m[6,t+1,j] ~ dpois(mean(phi4M.prob[j,1:(n_occasions-1)])*N_m[5,t,j]) #5yos
    N_A1[t+1,j] ~ dpois(mean(phi5M.prob[j,1:(n_occasions-1)])*N_m[6,t,j]) #new adults from 5yos
    N_Aplus[t+1,j] ~ dpois(mean(phiBM.prob[j,1:(n_occasions-1)])*N_m[7,t,j]) #repeat adults 7+
    N_m[7,t+1,j] <- N_A1[t+1,j] + N_Aplus[t+1,j]
    Ntot_m[t+1,j] <- sum(N_m[1:7,t+1,j])
    Ntot[t+1,j] <- Ntot_f[t+1,j] + Ntot_m[t+1,j]
  } #t extra fill years
    
    for (t in 1:(n_occasions+2)) {
      lambda[t,j] <- Ntot[t+1,j]/Ntot[t,j]
    } #lambda
    
  } #region
    
}) # mod   


##### run model ####
Q_list <- iar.Q(n_occasions-1,2)

nim.data <- list(y = y, ym = ym, pups_reg_med = pups_reg_med, #np_reg_med = np_reg_med,
                 pups_reg_sd = pups_reg_sd, phi_ests = phi_ests, psi_ests = psi_ests,
                 stableAge = stableAge, stableAgeM = stableAgeM,
                 z = z.st, zm = z.st.m)

nim.constants <- list(n_fem = dim(ch_fem)[1], n_m = dim(ch_m)[1], 
                      # prop_f = class_dat$prop_f_mean[1:6], prop_f_sd = class_dat$prop_f_sd[1:6],
                      n_occasions = n_occasions, n_r = 6, G = 8, H = 7,
                      resights = res_mat, eff = eff, neo_mort = 0.95,
                      mass_f = mass_f, mass_m = mass_m, 
                      reg_f = reg_f, reg_m = reg_m, reg_fb = reg_fb, reg_mb = reg_mb,
                      fc = fc, fc_m = fc_m, 
                      v1 = v1, v2 = v2, v3 = v3, v4 = v4, v5 = v5, v6 = v6, vB = vB, v8 = v8,
                      v2m = v2m, v3m = v3m, v4m = v4m, v5m = v5m, v6m = v6m, v7m = v7m, 
                      len_v1 = len_v1, len_v2 = len_v2, len_v3 = len_v3, len_v4 = len_v4, 
                      len_v5 = len_v5, len_v6 = len_v6, len_vB = len_vB, len_v8 = len_v8,
                      len_v2m = len_v2m, len_v3m = len_v3m, len_v4m = len_v4m, len_v5m = len_v5m, 
                      len_v6m = len_v6m, len_v7m = len_v7m,
                      L=Q_list$L, adj=Q_list$adj,
                      weights=Q_list$weights, num=Q_list$num, c=Q_list$c)

inits <- list(int.phiP = phi_ests[1,1], int.phiPM = phi_ests[8,1], 
              int.phi1 = phi_ests[2,1], int.phi1M = phi_ests[9,1],
              int.phi2 = phi_ests[3,1], int.phi2M = phi_ests[10,1], 
              int.phi3 = phi_ests[4,1], int.phi3M = phi_ests[11,1],
              int.phi4 = phi_ests[5,1], int.phi4M = phi_ests[12,1],
              int.phi5 = phi_ests[6,1], int.phi5M = phi_ests[13,1],
              int.phiB = phi_ests[7,1], int.phiNB = phi_ests[7,1], int.phiBM = phi_ests[14,1],
              int.psi3 = psi_ests[1,1], int.psi4 = psi_ests[2,1], int.psi5 = psi_ests[3,1], 
              int.psiB = psi_ests[4,1], int.psiNB = psi_ests[5,1],
              int.p1 = 0.7, int.p2 = 0.7, int.p3 = 0.7, int.p4 = 0.7, int.p5 = 0.7,
              int.pB = 0.9, int.pNB = 0.5, int.p1M = 0.7, int.p2M = 0.7, int.p3M = 0.7, int.p4M = 0.7, 
              int.p5M = 0.7, int.pBM = 0.7,
              eps.p = c(rep(0, n_occasions)), 
              epsP = array(0, dim = c(6, n_occasions-1)), 
              eps1 = array(0, dim = c(6, n_occasions-1)),
              eps2 = array(0, dim = c(6, n_occasions-1)),
              
              epsPB = array(0, dim = c(2, n_occasions-1)),
              epsB = array(0, dim = c(6, n_occasions-1)),
              eps.psiPB = array(0, dim = c(4, n_occasions-1)),
              eps.psiB = array(0, dim = c(4, n_occasions-1)),
              eps.psiNB = array(0, dim = c(4, n_occasions-1)),
              
              # epsPB = rep(0, n_occasions-1),
              # epsB = rep(0, n_occasions-1),
              # epsP = rep(0, n_occasions-1), eps1 = rep(0, n_occasions-1), eps2 = rep(0, n_occasions-1),
              # epsPB = rep(0, n_occasions-1), epsB = rep(0, n_occasions-1),
              # epsNB = rep(0, n_occasions-1), epsBM = rep(0, n_occasions-1),
              # eps.psiPB = rep(0, n_occasions-1),
              # eps.psiB = rep(0, n_occasions-1),
              # sigmaPB = 1, sigmaP = 1, sigmaB = 1, sigma2 = 1, sigma1 = 1, 
              p.delB = c(0.4, 0.5, 0.75), 
              b.massP = 0, b.massPM = 0, 
              b.mass1 = 0, b.mass1M = 0, 
              b.regP = c(rep(0,6)), b.reg1 = c(rep(0,6)), b.reg2 = c(rep(0,6)), 
              b.regPB = c(rep(0,2)), #b.regB = c(rep(0,6)), b.regNB = c(rep(0,6)),
              p.delB = c(0.4, 0.5, 0.75),
              z = z.init, zm = z.init.m)

### parameters
params <- c('phiP.prob', 'phi1.prob', 'phi2.prob', 'phi3.prob', 'phi4.prob', 'phi5.prob',
            'phiPM.prob', 'phi1M.prob', 'phi2M.prob', 'phi3M.prob', 'phi4M.prob', 'phi5M.prob',
            'phiB.prob', 'phiNB.prob', 'phiBM.prob',
            'psi3.prob', 'psi4.prob', 'psi5.prob', 'psiB.prob', 'psiNB.prob',
            'epsP', 'eps1', 'eps2', 'epsPB','epsB', 'eps.psiPB', 'eps.psiB', #'eps.psiNB',
            'b.delB', 'p.delB', 'b.eff', 'eps.p', 
             # 'sigmaP', 'sigma1', 'sigma2', 'sigmaPB', 'sigmaB',
            # 'sigma.psiPB', 'sigma.psiB', 
            'sigma.p', 
            'b.massP', 'b.mass1', 'b.massPM', 'b.mass1M', 
            'Ntot', 'Ntot_f', 'N_f', 'Ntot_m', 'N_m', #'lNtot_f', 'lNtot_m', 
            # 'sigma.popInit',
            'b.regP', 'b.reg1', 'b.reg2', 'b.regPB', 'b.regB', #'b.regNB',
            'b.reg.psi3', 'b.reg.psi4', 'b.reg.psi5', 'b.reg.psiB', 'b.reg.psiNB')

### run model
ni = 35000; nc = 3; nb = 20000; nt = 2; adaptInterval = 100

## PARALLEL STUFF 
t.start <- Sys.time() # start clock for whole process

cores=detectCores() # how many cores are available
# this line is essential on mac, not sure about pc
# does not impact performance though
used.cores = min(nc, cores) # good practice to not max out all available cores. 
# my general workflow is that in each instance of R I set up a script like this 
# that runs 3 chains in parallel (1 chain per core)
cl <- makeCluster(nc, setup_strategy = "sequential") # make cluster of cores
registerDoParallel(cl) 

foreach(i = 1:nc) %dopar% { # parallel version of for loop
  # my understanding is that each core can access your environment but not workspace 
  # i.e. you can reference data objects but you have to reload packages and functions
  library(nimble)
  library(here)
  source(here("scripts", "nimbleFunctions.R"))
  
  Rmodel <- nimbleModel(code=SSL_IPM, constants=nim.constants, 
                        data=nim.data, calculate=F, check=F, inits=inits)
  
  conf <- configureMCMC(Rmodel,monitors=params,control = list(adaptInterval = adaptInterval), 
                        thin=nt, useConjugacy = FALSE, enableWAIC = T)
  Rmcmc <- buildMCMC(conf)  #produces an uncompiled R mcmc function
  Cmodel <- compileNimble(Rmodel)
  Cmcmc <- compileNimble(Rmcmc, project = Rmodel)
  

  # NOTE HERE: nchains is 1 when running chains in parallel 
  out <- runMCMC(Cmcmc, niter = ni, nburnin = nb , nchains = 1, inits = inits,
                 setSeed = FALSE, progressBar = TRUE, samplesAsCodaMCMC = TRUE) 
  
  version <- '2.2_NADO'
  saveRDS(out, here('results', 'best', paste("out.parallel-", version, "spStable-",i,".RDS", sep = ""))) # save each chain with a diff name
  
  
} # closes parallel loop
stopCluster(cl) # important to do this to stop running things in parallel

t.end <- Sys.time() # end clock
(runTime <- t.end - t.start)

version <- '2.2_NADO'

out_1 <- readRDS(here::here('results', 'best', paste("out.parallel-", version, "spStable-1.RDS", sep = "")))
out_2 <- readRDS(here::here('results', 'best', paste("out.parallel-", version, "spStable-2.RDS", sep = "")))
out_3 <- readRDS(here::here('results', 'best', paste("out.parallel-", version, "spStable-3.RDS", sep = "")))

# combine them and make an mcmc object
library(coda)
out <- list(`out_1`, `out_2`, `out_3`) %>% as.mcmc.list()


```

```{r option 2.2 env}

SSL_IPM <- nimbleCode({
  
  # Priors and constraints
  for (i in 1:n_fem) { #females
    for (t in 1:(n_occasions - 1)) {
      logit(phiP[i,t]) <- mu.P + b.massP*mass_f[i] + b.regP[reg_f[i]] + epsP[reg_f[i],t] + b.npgoP*npgo[t] + b.sstP*sst[t]
      logit(phi1[i,t]) <- mu.1 + b.mass1*mass_f[i] + b.reg1[reg_f[i]] + eps1[reg_f[i],t] + b.npgo1*npgo[t] + b.sst1*sst[t]
      logit(phi2[i,t]) <- mu.2 + b.mass1*mass_f[i] + b.reg2[reg_f[i]] + eps2[reg_f[i],t] + b.npgo1*npgo[t] + b.sst1*sst[t]
      logit(phi3[i,t]) <- mu.3 + b.regPB[reg_fb[i]] + epsPB[reg_fb[i],t] 
      logit(phi4[i,t]) <- mu.4 + b.regPB[reg_fb[i]] + epsPB[reg_fb[i],t]
      logit(phi5[i,t]) <- mu.5 + b.regPB[reg_fb[i]] + epsPB[reg_fb[i],t] 
      logit(phiB[i,t]) <- mu.B + b.regB[reg_fb[i]] + epsB[reg_f[i],t] + b.npgoB*npgo[t] + b.sstB*sst[t]
      logit(phiNB[i,t]) <- mu.NB 
      
      logit(psi3[i,t]) <- mu.psi3 + b.reg.psi3[reg_f[i]] + b.npgo.psi*npgo[t] + b.sst.psi*sst[t]#+ eps.psiPB[reg_fb[i],t] 
      logit(psi4[i,t]) <- mu.psi4 + b.reg.psi4[reg_f[i]] + eps.psiPB[reg_fb[i],t] + b.npgo.psi*npgo[t] + b.sst.psi*sst[t]
      logit(psi5[i,t]) <- mu.psi5 + b.reg.psi5[reg_f[i]] + b.npgo.psi*npgo[t] + b.sst.psi*sst[t]#+ eps.psiPB[reg_fb[i],t] 
      logit(psiB[i,t]) <- mu.psiB + b.reg.psiB[reg_f[i]] + eps.psiB[reg_fb[i],t] + b.npgo.psi*npgo[t] + b.sst.psi*sst[t]
      logit(psiNB[i,t]) <- mu.psiNB + b.reg.psiNB[reg_f[i]] #+ eps.psiNB[reg_fb[i],t] 
      
      logit(p1[i,t]) <- mu.p1 + b.eff[eff[t]] + eps.p[t] 
      logit(p2[i,t]) <- mu.p2 + b.eff[eff[t]] + eps.p[t]
      logit(p3[i,t]) <- mu.p3 + b.eff[eff[t]] + eps.p[t]
      logit(p4[i,t]) <- mu.p4 + b.eff[eff[t]] + eps.p[t]
      logit(p5[i,t]) <- mu.p5 + b.eff[eff[t]] + eps.p[t]
      logit(pB[i,t]) <- mu.pB + b.eff[eff[t]] + eps.p[t]
      logit(pNB[i,t]) <- mu.pNB + b.eff[eff[t]] + eps.p[t]
      logit(delB[i,t]) <- b.delB[resights[i,t]]
    } #t 
  } #i fem
  
  for (i in 1:n_m) { #males
    for (t in 1:(n_occasions - 1)) {
      logit(phiPM[i,t]) <- mu.PM + b.massPM*mass_m[i] + b.regP[reg_m[i]] + epsP[reg_m[i],t] + b.npgoP*npgo[t] + b.sstP*sst[t]
      logit(phi1M[i,t]) <- mu.1M + b.mass1M*mass_m[i] + b.reg1[reg_m[i]] + eps1[reg_m[i],t] + b.npgo1*npgo[t] + b.sst1*sst[t]
      logit(phi2M[i,t]) <- mu.2M + b.mass1M*mass_m[i] + b.reg2[reg_m[i]] + eps2[reg_m[i],t] + b.npgo1*npgo[t] + b.sst1*sst[t]
      logit(phi3M[i,t]) <- mu.3M + b.regPB[reg_mb[i]] + epsPB[reg_mb[i],t] 
      logit(phi4M[i,t]) <- mu.4M + b.regPB[reg_mb[i]] + epsPB[reg_mb[i],t] 
      logit(phi5M[i,t]) <- mu.5M + b.regPB[reg_mb[i]] + epsPB[reg_mb[i],t] 
      logit(phiBM[i,t]) <- mu.BM + b.regB[reg_mb[i]] + epsB[reg_mb[i],t]
      
      logit(p1M[i,t]) <- mu.p1M + b.eff[eff[t]] + eps.p[t]
      logit(p2M[i,t]) <- mu.p2M + b.eff[eff[t]] + eps.p[t]
      logit(p3M[i,t]) <- mu.p3M + b.eff[eff[t]] + eps.p[t]
      logit(p4M[i,t]) <- mu.p4M + b.eff[eff[t]] + eps.p[t]
      logit(p5M[i,t]) <- mu.p5M + b.eff[eff[t]] + eps.p[t]
      logit(pBM[i,t]) <- mu.pBM + b.eff[eff[t]] + eps.p[t]
    } #t male
  } #i male
  
  ### Priors
  #fixed categorical effect of natal region
  b.regP[2] <- 0
  b.reg1[2] <- 0
  b.reg2[2] <- 0
  b.regPB[1] <- 0
  b.regB[1] <- 0
  b.reg.psi3[2] <- 0
  b.reg.psi4[2] <- 0
  b.reg.psi5[2] <- 0
  b.reg.psiB[2] <- 0
  b.reg.psiNB[2] <- 0
  
  for (r in c(1,3,4,5,6)) {
  b.regP[r] ~ dnorm(0, sd = s.regP)
  b.reg1[r] ~ dnorm(0, sd = s.reg1)
  b.reg2[r] ~ dnorm(0, sd = s.reg2)
  
  b.reg.psi3[r] ~ dnorm(0, sd = s.psiPB)
  b.reg.psi4[r] ~ dnorm(0, sd = s.psiPB)
  b.reg.psi5[r] ~ dnorm(0, sd = s.psiPB)
  b.reg.psiB[r] ~ dnorm(0, sd = s.psiB)
  b.reg.psiNB[r] ~ dnorm(0, sd = s.psiB)
  }
  
  b.regPB[2] ~ dnorm(0, sd = s.regPB)
  b.regB[2] ~ dnorm(0, sd = s.regB)
  
  s.regP ~ dexp(1)
  s.reg1 ~ dexp(1)
  s.reg2 ~ dexp(1)
  s.regPB ~ dexp(1)
  s.regB ~ dexp(1)
  s.psiPB ~ dexp(1)
  s.psiB ~ dexp(1)

   for (j in 1:4) {
    epsP[j,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.epsP, c)
    eps1[j,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.eps1, c)
    eps2[j,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.eps2, c)
    epsB[j,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.epsB, c)
  } 
  
  epsP[5:6,1:(n_occasions-1)] <- 0
  eps1[5:6,1:(n_occasions-1)] <- 0
  eps2[5:6,1:(n_occasions-1)] <- 0
  epsB[5:6,1:(n_occasions-1)] <- 0
  
  epsPB[1,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.epsPB, c)
  epsPB[2,1:(n_occasions-1)] <- 0
  
  eps.psiPB[1,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.eps.psi, c)
  eps.psiB[1,1:(n_occasions-1)] ~ dcar_normal(adj[1:L], weights[1:L], num[1:(n_occasions - 1)], t.eps.psi, c)
  
  eps.psiPB[2,1:(n_occasions-1)] <- 0
  eps.psiB[2,1:(n_occasions-1)] <- 0
  
  t.epsP <- 1/(s.epsP*s.epsP) #precision
  s.epsP ~ dexp(1) #standard deviation
  t.eps1 <- 1/(s.eps1*s.eps1)
  s.eps1 ~ dexp(1)
  t.eps2 <- 1/(s.eps2*s.eps2)
  s.eps2 ~ dexp(1)
  t.epsPB <- 1/(s.epsPB*s.epsPB)
  s.epsPB ~ dexp(1)
  t.epsB <- 1/(s.epsB*s.epsB)
  s.epsB ~ dexp(1)
  t.eps.psi <- 1/(s.eps.psi*s.eps.psi)
  s.eps.psi ~ dexp(1)
    
    for (t in 1:(n_occasions)) {
      eps.p[t] ~ dnorm(0, sd = sigma.p)
    }
    sigma.p ~ dexp(1)
    
    b.npgoP ~ dnorm(0, sd = s.npgoP)
    b.npgo1 ~ dnorm(0, sd = s.npgo1)
    b.npgoB ~ dnorm(0, sd = s.npgo1)
    b.npgo.psi ~ dnorm(0, sd = s.npgo.psi)
    s.npgo.psi ~ dexp(1)
    s.npgoP ~ dexp(1)
    s.npgo1 ~ dexp(1)
    
    b.sstP ~ dnorm(0, sd = s.sstP)
    b.sst1 ~ dnorm(0, sd = s.sst1)
    b.sstB ~ dnorm(0, sd = s.sst1)
    b.sst.psi ~ dnorm(0, sd = s.sst.psi)
    s.sst.psi ~ dexp(1)
    s.sstP ~ dexp(1)
    s.sst1 ~ dexp(1)
  
  #intercepts  
  mu.psi3 <- log(int.psi3/(1-int.psi3))
  mu.psi4 <- log(int.psi4/(1-int.psi4))
  mu.psi5 <- log(int.psi5/(1-int.psi5))
  mu.psiB <- log(int.psiB/(1-int.psiB))
  mu.psiNB <- log(int.psiNB/(1-int.psiNB))
  int.psi3 ~ T(dnorm(psi_ests[1,1], sd = psi_ests[1,2]),0,1)
  int.psi4 ~ T(dnorm(psi_ests[2,1], sd = psi_ests[2,2]),0,1)
  int.psi5 ~ T(dnorm(psi_ests[3,1], sd = psi_ests[3,2]),0,1)
  int.psiB ~ T(dnorm(psi_ests[4,1], sd = psi_ests[4,2]),0,1)
  int.psiNB ~ T(dnorm(psi_ests[5,1], sd = psi_ests[5,2]),0,1)
  mu.p1 <- log(int.p1/(1 - int.p1))
  mu.p2 <- log(int.p2/(1 - int.p2))
  mu.p3 <- log(int.p3/(1 - int.p3))
  mu.p4 <- log(int.p4/(1 - int.p4))
  mu.p5 <- log(int.p5/(1 - int.p5))
  mu.pB <- log(int.pB/(1 - int.pB))
  mu.pNB <- log(int.pNB/(1 - int.pNB))
  mu.p1M <- log(int.p1M/(1 - int.p1M))
  mu.p2M <- log(int.p2M/(1 - int.p2M))
  mu.p3M <- log(int.p3M/(1 - int.p3M))
  mu.p4M <- log(int.p4M/(1 - int.p4M))
  mu.p5M <- log(int.p5M/(1 - int.p5M))
  mu.pBM <- log(int.pBM/(1 - int.pBM))
  int.p1 ~ dunif(0,1)
  int.p2 ~ dunif(0,1)
  int.p3 ~ dunif(0,1)
  int.p4 ~ dunif(0,1)
  int.p5 ~ dunif(0,1)
  int.pB ~ dunif(0,1)
  int.pNB ~ dunif(0,1)
  int.p1M ~ dunif(0,1)
  int.p2M ~ dunif(0,1)
  int.p3M ~ dunif(0,1)
  int.p4M ~ dunif(0,1)
  int.p5M ~ dunif(0,1)
  int.pBM ~ dunif(0,1)
  #phi
  mu.P <- log(int.phiP/(1 - int.phiP))
  mu.1 <- log(int.phi1/(1 - int.phi1))
  mu.2 <- log(int.phi2/(1 - int.phi2))
  mu.3 <- log(int.phi3/(1 - int.phi3))
  mu.4 <- log(int.phi4/(1 - int.phi4))
  mu.5 <- log(int.phi5/(1 - int.phi5))
  mu.B <- log(int.phiB/(1 - int.phiB))
  mu.NB <- log(int.phiNB/(1 - int.phiNB))
  mu.PM <- log(int.phiPM/(1 - int.phiPM))
  mu.1M <- log(int.phi1M/(1 - int.phi1M))
  mu.2M <- log(int.phi2M/(1 - int.phi2M))
  mu.3M <- log(int.phi3M/(1 - int.phi3M))
  mu.4M <- log(int.phi4M/(1 - int.phi4M))
  mu.5M <- log(int.phi5M/(1 - int.phi5M))
  mu.BM <- log(int.phiBM/(1 - int.phiBM)) 
  int.phiP ~ T(dnorm(phi_ests[1,1], sd = phi_ests[1,2]),0,1)
  int.phi1 ~ T(dnorm(phi_ests[2,1], sd = phi_ests[2,2]),0,1)
  int.phi2 ~ T(dnorm(phi_ests[3,1], sd = phi_ests[3,2]),0,1)
  int.phi3 ~ T(dnorm(phi_ests[4,1], sd = phi_ests[4,2]),0,1)
  int.phi4 ~ T(dnorm(phi_ests[5,1], sd = phi_ests[5,2]),0,1)
  int.phi5 ~ T(dnorm(phi_ests[6,1], sd = phi_ests[6,2]),0,1)
  int.phiB ~ T(dnorm(phi_ests[7,1], sd = phi_ests[7,2]),0,1)
  int.phiNB ~ T(dnorm(phi_ests[7,1], sd = phi_ests[7,2]),0,1)
  int.phiPM ~ T(dnorm(phi_ests[8,1], sd = phi_ests[8,2]),0,1)
  int.phi1M ~ T(dnorm(phi_ests[9,1], sd = phi_ests[9,2]),0,1)
  int.phi2M ~ T(dnorm(phi_ests[10,1], sd = phi_ests[10,2]),0,1)
  int.phi3M ~ T(dnorm(phi_ests[11,1], sd = phi_ests[11,2]),0,1)
  int.phi4M ~ T(dnorm(phi_ests[12,1], sd = phi_ests[12,2]),0,1)
  int.phi5M ~ T(dnorm(phi_ests[13,1], sd = phi_ests[13,2]),0,1)
  int.phiBM ~ T(dnorm(phi_ests[14,1], sd = phi_ests[14,2]),0,1)
  
  p.delB[1] ~ dunif(0,1)
  b.delB[1] <- log(p.delB[1]/(1-p.delB[1]))
  p.delB[2] ~ dunif(0,1)
  b.delB[2] <- log(p.delB[2]/(1-p.delB[2]))
  p.delB[3] ~ dunif(0,1)
  b.delB[3] <- log(p.delB[3]/(1-p.delB[3]))
  b.delB[4] <- -5 #0 on probability scale
  
  b.eff[1] <- 0
  b.eff[2] ~ dnorm(0, 0.001)
    
    #back-transform everything
       for (t in 1:(n_occasions-1)){
    for (r in 1:6) {
      phiP.prob[r,t] <- 1/(1+exp(-(mu.P + epsP[r,t] + b.regP[r])))
      phiPM.prob[r,t] <- 1/(1+exp(-(mu.PM + epsP[r,t] + b.regP[r])))
      phi1.prob[r,t] <- 1/(1+exp(-(mu.1 + eps1[r,t] + b.reg1[r])))
      phi1M.prob[r,t] <- 1/(1+exp(-(mu.1M + eps1[r,t] + b.reg1[r])))
      phi2.prob[r,t] <- 1/(1+exp(-(mu.2 + eps2[r,t] + b.reg2[r])))
      phi2M.prob[r,t] <- 1/(1+exp(-(mu.2M + eps2[r,t] + b.reg2[r])))
      
    }

      for (r in 1:4) {
      phi3.prob[r,t] <- 1/(1+exp(-(mu.3 + epsPB[1,t] + b.regPB[1])))
      phi3M.prob[r,t] <- 1/(1+exp(-(mu.3M + epsPB[1,t] + b.regPB[1])))
      phi4.prob[r,t] <- 1/(1+exp(-(mu.4 + epsPB[1,t] + b.regPB[1])))
      phi4M.prob[r,t] <- 1/(1+exp(-(mu.4M + epsPB[1,t] + b.regPB[1])))
      phi5.prob[r,t] <- 1/(1+exp(-(mu.5 + epsPB[1,t] + b.regPB[1])))
      phi5M.prob[r,t] <- 1/(1+exp(-(mu.5M + epsPB[1,t] + b.regPB[1])))
      phiB.prob[r,t] <- 1/(1+exp(-(mu.B + epsB[r,t] + b.regB[1])))
      
      phiNB.prob[r,t] <- 1/(1+exp(-(mu.NB)))
      phiBM.prob[r,t] <- 1/(1+exp(-(mu.BM + b.regB[1] + epsB[1,t])))
      psi3.prob[r,t] <- 1/(1+exp(-(mu.psi3 + b.reg.psi3[r])))
      psi4.prob[r,t] <- 1/(1+exp(-(mu.psi4 + b.reg.psi4[r] + eps.psiPB[1,t])))
      psi5.prob[r,t] <- 1/(1+exp(-(mu.psi5 + b.reg.psi5[r])))
      psiB.prob[r,t] <- 1/(1+exp(-(mu.psiB + b.reg.psiB[r] + eps.psiB[1,t])))
      psiNB.prob[r,t] <- 1/(1+exp(-(mu.psiNB + b.reg.psiNB[r])))
      }
      for (r in 5:6) {
      phi3.prob[r,t] <- 1/(1+exp(-(mu.3 + epsPB[2,t] + b.regPB[2])))
      phi3M.prob[r,t] <- 1/(1+exp(-(mu.3M + epsPB[2,t] + b.regPB[2])))
      phi4.prob[r,t] <- 1/(1+exp(-(mu.4 + epsPB[2,t] + b.regPB[2])))
      phi4M.prob[r,t] <- 1/(1+exp(-(mu.4M + epsPB[2,t] + b.regPB[2])))
      phi5.prob[r,t] <- 1/(1+exp(-(mu.5 + epsPB[2,t] + b.regPB[2])))
      phi5M.prob[r,t] <- 1/(1+exp(-(mu.5M + epsPB[2,t] + b.regPB[2])))
      phiB.prob[r,t] <- 1/(1+exp(-(mu.B + epsB[r,t] + b.regB[2])))
      phiNB.prob[r,t] <- 1/(1+exp(-(mu.NB)))
      phiBM.prob[r,t] <- 1/(1+exp(-(mu.BM + b.regB[2] + epsB[2,t])))
      psi3.prob[r,t] <- 1/(1+exp(-(mu.psi3 + b.reg.psi3[r])))
      psi4.prob[r,t] <- 1/(1+exp(-(mu.psi4 + b.reg.psi4[r] + eps.psiPB[2,t])))
      psi5.prob[r,t] <- 1/(1+exp(-(mu.psi5 + b.reg.psi5[r])))
      psiB.prob[r,t] <- 1/(1+exp(-(mu.psiB + b.reg.psiB[r] + eps.psiB[2,t])))
      psiNB.prob[r,t] <- 1/(1+exp(-(mu.psiNB + b.reg.psiNB[r])))
      }
         
    } #t
  
    #covs - phi
    b.massP ~ dnorm(0, sd = s.massP)
    s.massP ~ dexp(1)
    b.massPM ~ dnorm(0, sd = s.massPM)
    s.massPM ~ dexp(1)
    b.mass1 ~ dnorm(0, sd = s.mass1)
    s.mass1 ~ dexp(1)
    b.mass1M ~ dnorm(0, sd = s.mass1M)
    s.mass1M ~ dexp(1)
    
    #likelihood
for (i in 1:n_fem) { #females
    z[i, fc[i]:fc[i]] <- 1 #pups at first capture
for (t in (fc[i] + 1):n_occasions) {
      z[i,t] ~ dcat(state_probs[i,t-1,1:12])
      y[i,t] ~ dcat(event_probs[i,t,1:11])
      
    state_probs[i,t-1,1:12] <- getPHI_f(z = z[i,t-1], 
                                      phiP = phiP[i,t-1], phi1 = phi1[i,t-1], phi2 = phi2[i,t-1], 
                                      phi3 = phi3[i,t-1], phi4 = phi4[i,t-1], phi5 = phi5[i,t-1], 
                                      phiB = phiB[i,t-1], phiNB = phiNB[i,t-1],
                                      psi3 = psi3[i,t-1], psi4 = psi4[i,t-1],
                                      psi5 = psi5[i,t-1], psiB = psiB[i,t-1], psiNB = psiNB[i,t-1])
    
    event_probs[i,t,1:11] <- getP_f(z = z[i,t], 
                                    p1 = p1[i,t-1], p2 = p2[i,t-1], p3 = p3[i,t-1], 
                                    p4 = p4[i,t-1], p5 = p5[i,t-1],
                                    pB = pB[i,t-1], pNB = pNB[i,t-1], delB = delB[i,t-1])
    } #t likelihood fem
} #i likelihood fem
    
   for (i in 1:n_m) { #males
    zm[i, fc_m[i]:fc_m[i]] <- 1
  for (t in (fc_m[i] + 1):n_occasions) {
    zm[i,t] ~ dcat(state_probs_m[i, t-1, 1:8])
    ym[i,t] ~ dcat(event_probs_m[i,t,1:8])
    
    state_probs_m[i,t-1,1:8] <- getPHI_m(z = zm[i,t-1], 
                                      phiPM = phiPM[i,t-1], phi1M = phi1M[i,t-1], phi2M = phi2M[i,t-1], 
                                      phi3M = phi3M[i,t-1], phi4M = phi4M[i,t-1], phi5M = phi5M[i,t-1], 
                                      phiBM = phiBM[i,t-1])
    event_probs_m[i,t,1:8] <- getP_m(z = zm[i,t], 
                                    p1M = p1M[i,t-1], p2M = p2M[i,t-1], p3M = p3M[i,t-1], 
                                    p4M = p4M[i,t-1], p5M = p5M[i,t-1], pBM = pBM[i,t-1])
    } # likelihood t male
   } #likelihood i male
    
########################### population model ################################  

    # sigma.popInit ~ dexp(1)
    
    for (j in 1:n_r) {
   # total females
   # Ntot_f[1,j] ~ dpois(round(np_reg_med[1,j]*prop_f))
   # lNtot_f[j] ~ dlnorm(meanlog = log(np_reg_med[1,j]*prop_f), sdlog = log(sigma.popInit))
   # Ntot_f[1,j] <- round(exp(lNtot_f[j]))
   
   # Ntot_f[1,j] ~ dnorm(np_reg_med[1,j]*prop_f, sd = sigma.popInit)
   # Ntot_f[1,j] <- round(np_reg_med[1,j]*prop_f)
      
  # establish first year of population using conditional binomials
   # N_f[1,1,j] <- round(pups_reg_med[1,j]/2) #pups in 2000
      
      N_f[1,1,j] ~ dcat(v1[j,1:len_v1])
      N_f[2,1,j] ~ dcat(v2[j,1:len_v2])
      N_f[3,1,j] ~ dcat(v3[j,1:len_v3])
      N_f[4,1,j] ~ dcat(v4[j,1:len_v4])
      N_f[5,1,j] ~ dcat(v5[j,1:len_v5])
      N_f[6,1,j] ~ dcat(v6[j,1:len_v6])
      N_f[7,1,j] ~ dcat(vB[j,1:len_vB])
      N_f[8,1,j] ~ dcat(v8[j,1:len_v8])
      Ntot_f[1,j] <- sum(N_f[1:8,1,j])
 
      N_m[1,1,j] ~ dcat(v1[j,1:len_v1])
      N_m[2,1,j] ~ dcat(v2m[j,1:len_v2m])
      N_m[3,1,j] ~ dcat(v3m[j,1:len_v3m])
      N_m[4,1,j] ~ dcat(v4m[j,1:len_v4m])
      N_m[5,1,j] ~ dcat(v5m[j,1:len_v5m])
      N_m[6,1,j] ~ dcat(v6m[j,1:len_v6m])
      N_m[7,1,j] ~ dcat(v7m[j,1:len_v7m])
      Ntot_m[1,j] <- sum(N_m[1:7,1,j])
   
   # for(g in 2:(G-1)){
   #  N_f[g,1,j] ~ dbin(stableAge[g]/(1-sum(stableAge[1:(g-1)])), Ntot_f[1,j] - sum(N_f[1:(g-1),1,j]) )
   # }
   # 
   # # group G: deterministic
   # N_f[G,1,j] <- Ntot_f[1,j] - sum(N_f[1:(G-1),1,j])
      
   #  #total breeders and non-breeders
    N_B[1,j] <-  N_f[7,1,j]  # total breeders
    N_NB[1,j] <- N_f[8,1,j] # total NB
    
    ###MALES
    # Ntot_m[1,j] ~ dpois(np_reg_med[1,j]*(1-prop_f)) #total males
    # lNtot_m[j] ~ dlnorm(meanlog = log(np_reg_med[1,j]*(1-prop_f)), sdlog = log(sigma.popInit)) 
    # Ntot_m[1,j] <- round(exp(lNtot_m[j]))
    
     # Ntot_m[1,j] ~ dnorm(np_reg_med[1,j]*(1-prop_f), sd = sigma.popInit)
   #  Ntot_m[1,j] <- round(np_reg_med[1,j]*(1-prop_f))
   # 
   #  N_m[1,1,j] <- round(pups_reg_med[1,j]/2) #pups
   # 
   #  for(h in 2:(H-1)){
   #  N_m[h,1,j] ~ dbin(stableAgeM[h]/(1-sum(stableAgeM[1:(h-1)])), Ntot_m[1,j] - sum(N_m[1:(h-1),1,j]) )
   #  }
   # 
   # # group H: deterministic
   # N_m[H,1,j] <- Ntot_m[1,j] - sum(N_m[1:(H-1),1,j])
    N_A1[1,j] <- N_m[6,1,j] #new adults from 5yos
    N_Aplus[1,j] <- N_m[7,1,j]  #repeat adults 7+
    Ntot[1,j] <- Ntot_f[1,j] + Ntot_m[1,j]
    
    for (t in 1:(n_occasions-1)) { #t = 1 fills t+1 == Ntot[2001]; t = 18 fills t+1 == Ntot[2018]
    pups_reg_med[t+1,j] ~ dnorm(N_f[1,t+1,j]+N_m[1,t+1,j], sd = pups_reg_sd[t+1,j])

    ###FEMALES
    N_f[1,t+1,j] ~ dbin(0.5, N_f[7,t+1,j]) # or deterministic N_f[1,t+1,j] <- N_f[7,t+1,j]*0.5
    N_f[2,t+1,j] ~ dpois(phiP.prob[j,t]*neo_mort*N_f[1,t,j]) #yearlings
    N_f[3,t+1,j] ~ dpois(phi1.prob[j,t]*N_f[2,t,j]) #2yos
    N_f[4,t+1,j] ~ dpois(phi2.prob[j,t]*N_f[3,t,j]) #3yos
    N_f[5,t+1,j] ~ dpois(phi3.prob[j,t]*(1-psi3.prob[j,t])*N_f[4,t,j]) #4yo PB
    N_f[6,t+1,j] ~ dpois(phi4.prob[j,t]*(1-psi4.prob[j,t])*N_f[5,t,j]) #5yo PB
    N_4B[t+1,j] ~ dpois(phi3.prob[j,t]*psi3.prob[j,t]*N_f[4,t,j]) #4yo breeders
    N_5B[t+1,j] ~ dpois(phi4.prob[j,t]*psi4.prob[j,t]*N_f[5,t,j]) #5yo first-B
    N_6B[t+1,j] ~ dpois(phi5.prob[j,t]*psi5.prob[j,t]*N_f[6,t,j]) #6yo first-B
    N_6NB[t+1,j] ~ dpois(phi5.prob[j,t]*(1-psi5.prob[j,t])*N_f[6,t,j]) #6yo NB that was PB at 5

    ## Plus groups
    #breeders
    N_BB[t+1,j] ~ dpois(phiB.prob[j,t]*psiB.prob[j,t]*N_B[t,j]) # plus grp B given B
    N_BNB[t+1,j] ~ dpois(phiNB.prob[j,t]*psiNB.prob[j,t]*N_NB[t,j]) # plus grp B given NB
    #non breeders
    N_NBNB[t+1,j] ~ dpois(phiNB.prob[j,t]*(1-psiNB.prob[j,t])*N_NB[t,j]) # plus grp NB given NB
    N_NBB[t+1,j] ~ dpois(phiB.prob[j,t]*(1-psiB.prob[j,t])*N_B[t,j]) # plus grp NB given B

    #total breeders and non-breeders
    N_B[t+1,j] <- N_4B[t+1,j]+N_5B[t+1,j]+N_6B[t+1,j]+N_BB[t+1,j]+N_BNB[t+1,j] # total breeders
    N_NB[t+1,j] <- N_6NB[t+1,j]+N_NBB[t+1,j]+N_NBNB[t+1,j] # total breeders
    N_f[7,t+1,j] <- N_B[t+1,j]   #B
    N_f[8,t+1,j] <- N_NB[t+1,j]  #NB
     Ntot_f[t+1,j] <- sum(N_f[1:8,t+1,j])

    ###MALES
    N_m[1,t+1,j] ~ dbin(0.5, N_f[7,t+1,j]) #pups
    N_m[2,t+1,j] ~ dpois(phiPM.prob[j,t]*neo_mort*N_m[1,t,j]) #yearlings
    N_m[3,t+1,j] ~ dpois(phi1M.prob[j,t]*N_m[2,t,j]) #2yos
    N_m[4,t+1,j] ~ dpois(phi2M.prob[j,t]*N_m[3,t,j]) #3yos
    N_m[5,t+1,j] ~ dpois(phi3M.prob[j,t]*N_m[4,t,j]) #4yos
    N_m[6,t+1,j] ~ dpois(phi4M.prob[j,t]*N_m[5,t,j]) #5yos
    N_A1[t+1,j] ~ dpois(phi5M.prob[j,t]*N_m[6,t,j]) #new adults from 5yos
    N_Aplus[t+1,j] ~ dpois(phiBM.prob[j,t]*N_m[7,t,j]) #repeat adults 7+
    N_m[7,t+1,j] <- N_A1[t+1,j] + N_Aplus[t+1,j]
    Ntot_m[t+1,j] <- sum(N_m[1:7,t+1,j])
    Ntot[t+1,j] <- Ntot_f[t+1,j] + Ntot_m[t+1,j]
  } #t

    #fill up to aerial survey data in 2021
        for (t in n_occasions:(n_occasions+2)) { #t = 19 fills t+1 == Ntot[2019]; t = 21 fills t+1 == Ntot[2021]
    pups_reg_med[t+1,j] ~ dnorm(N_f[1,t+1,j]+N_m[1,t+1,j], sd = pups_reg_sd[t+1,j])

    ###FEMALES
    N_f[1,t+1,j] ~ dbin(0.5, N_f[7,t+1,j]) # or deterministic N_f[1,t+1,j] <- N_f[7,t+1,j]*0.5
    N_f[2,t+1,j] ~ dpois(mean(phiP.prob[j,1:(n_occasions-1)])*neo_mort*N_f[1,t,j]) #yearlings
    N_f[3,t+1,j] ~ dpois(mean(phi1.prob[j,1:(n_occasions-1)])*N_f[2,t,j]) #2yos
    N_f[4,t+1,j] ~ dpois(mean(phi2.prob[j,1:(n_occasions-1)])*N_f[3,t,j]) #3yos
    N_f[5,t+1,j] ~ dpois(mean(phi3.prob[j,1:(n_occasions-1)])*(1-mean(psi3.prob[j,1:(n_occasions-1)]))*N_f[4,t,j]) #4yo PB
    N_f[6,t+1,j] ~ dpois(mean(phi4.prob[j,1:(n_occasions-1)])*(1-mean(psi4.prob[j,1:(n_occasions-1)]))*N_f[5,t,j]) #5yo PB
    N_4B[t+1,j] ~ dpois(mean(phi3.prob[j,1:(n_occasions-1)])*mean(psi3.prob[j,1:(n_occasions-1)])*N_f[4,t,j]) #4yo breeders
    N_5B[t+1,j] ~ dpois(mean(phi4.prob[j,1:(n_occasions-1)])*mean(psi4.prob[j,1:(n_occasions-1)])*N_f[5,t,j]) #5yo first-B
    N_6B[t+1,j] ~ dpois(mean(phi5.prob[j,1:(n_occasions-1)])*mean(psi5.prob[j,1:(n_occasions-1)])*N_f[6,t,j]) #6yo first-B
    N_6NB[t+1,j] ~ dpois(mean(phi5.prob[j,1:(n_occasions-1)])*(1-mean(psi5.prob[j,1:(n_occasions-1)]))*N_f[6,t,j]) #6yo NB that was PB at 5
    ## Plus groups
    #breeders
    N_BB[t+1,j] ~ dpois(mean(phiB.prob[j,1:(n_occasions-1)])*mean(psiB.prob[j,1:(n_occasions-1)])*N_B[t,j]) # plus grp B given B
    N_BNB[t+1,j] ~ dpois(mean(phiNB.prob[j,1:(n_occasions-1)])*mean(psiNB.prob[j,1:(n_occasions-1)])*N_NB[t,j]) # plus grp B given NB
    #non breeders
    N_NBNB[t+1,j] ~ dpois(mean(phiNB.prob[j,1:(n_occasions-1)])*(1-mean(psiNB.prob[j,1:(n_occasions-1)]))*N_NB[t,j]) # plus grp NB given NB
    N_NBB[t+1,j] ~ dpois(mean(phiB.prob[j,1:(n_occasions-1)])*(1-mean(psiB.prob[j,1:(n_occasions-1)]))*N_B[t,j]) # plus grp NB given B
    #total breeders and non-breeders
    N_B[t+1,j] <- N_4B[t+1,j]+N_5B[t+1,j]+N_6B[t+1,j]+N_BB[t+1,j]+N_BNB[t+1,j] # total breeders
    N_NB[t+1,j] <- N_6NB[t+1,j]+N_NBB[t+1,j]+N_NBNB[t+1,j] # total breeders
    N_f[7,t+1,j] <- N_B[t+1,j]   #B
    N_f[8,t+1,j] <- N_NB[t+1,j]  #NB
     Ntot_f[t+1,j] <- sum(N_f[1:8,t+1,j])
    ###MALES
    N_m[1,t+1,j] ~ dbin(0.5, N_f[7,t+1,j]) #pups
    N_m[2,t+1,j] ~ dpois(mean(phiPM.prob[j,1:(n_occasions-1)])*neo_mort*N_m[1,t,j]) #yearlings
    N_m[3,t+1,j] ~ dpois(mean(phi1M.prob[j,1:(n_occasions-1)])*N_m[2,t,j]) #2yos
    N_m[4,t+1,j] ~ dpois(mean(phi2M.prob[j,1:(n_occasions-1)])*N_m[3,t,j]) #3yos
    N_m[5,t+1,j] ~ dpois(mean(phi3M.prob[j,1:(n_occasions-1)])*N_m[4,t,j]) #4yos
    N_m[6,t+1,j] ~ dpois(mean(phi4M.prob[j,1:(n_occasions-1)])*N_m[5,t,j]) #5yos
    N_A1[t+1,j] ~ dpois(mean(phi5M.prob[j,1:(n_occasions-1)])*N_m[6,t,j]) #new adults from 5yos
    N_Aplus[t+1,j] ~ dpois(mean(phiBM.prob[j,1:(n_occasions-1)])*N_m[7,t,j]) #repeat adults 7+
    N_m[7,t+1,j] <- N_A1[t+1,j] + N_Aplus[t+1,j]
    Ntot_m[t+1,j] <- sum(N_m[1:7,t+1,j])
    Ntot[t+1,j] <- Ntot_f[t+1,j] + Ntot_m[t+1,j]
  } #t extra fill years
    
    for (t in 1:(n_occasions+2)) {
      lambda[t,j] <- Ntot[t+1,j]/Ntot[t,j]
    } #lambda
    
  } #region
    
}) # mod   


##### run model ####
Q_list <- iar.Q(n_occasions-1,2)

nim.data <- list(y = y, ym = ym, pups_reg_med = pups_reg_med, 
                 pups_reg_sd = pups_reg_sd, phi_ests = phi_ests, psi_ests = psi_ests,
                 stableAge = stableAge, stableAgeM = stableAgeM, sst = sst, npgo = npgo,
                 z = z.st, zm = z.st.m)

nim.constants <- list(n_fem = dim(ch_fem)[1], n_m = dim(ch_m)[1], 
                      n_occasions = n_occasions, n_r = 6, G = 8, H = 7,
                      resights = res_mat, eff = eff, neo_mort = 0.95,
                      mass_f = mass_f, mass_m = mass_m, 
                      reg_f = reg_f, reg_m = reg_m, reg_fb = reg_fb, reg_mb = reg_mb,
                      fc = fc, fc_m = fc_m, 
                      v1 = v1, v2 = v2, v3 = v3, v4 = v4, v5 = v5, v6 = v6, vB = vB, v8 = v8,
                      v2m = v2m, v3m = v3m, v4m = v4m, v5m = v5m, v6m = v6m, v7m = v7m, 
                      len_v1 = len_v1, len_v2 = len_v2, len_v3 = len_v3, len_v4 = len_v4, 
                      len_v5 = len_v5, len_v6 = len_v6, len_vB = len_vB, len_v8 = len_v8,
                      len_v2m = len_v2m, len_v3m = len_v3m, len_v4m = len_v4m, len_v5m = len_v5m, 
                      len_v6m = len_v6m, len_v7m = len_v7m,
                      L=Q_list$L, adj=Q_list$adj,
                      weights=Q_list$weights, num=Q_list$num, c=Q_list$c)

inits <- list(int.phiP = phi_ests[1,1], int.phiPM = phi_ests[8,1], 
              int.phi1 = phi_ests[2,1], int.phi1M = phi_ests[9,1],
              int.phi2 = phi_ests[3,1], int.phi2M = phi_ests[10,1], 
              int.phi3 = phi_ests[4,1], int.phi3M = phi_ests[11,1],
              int.phi4 = phi_ests[5,1], int.phi4M = phi_ests[12,1],
              int.phi5 = phi_ests[6,1], int.phi5M = phi_ests[13,1],
              int.phiB = phi_ests[7,1], int.phiNB = phi_ests[7,1], int.phiBM = phi_ests[14,1],
              int.psi3 = psi_ests[1,1], int.psi4 = psi_ests[2,1], int.psi5 = psi_ests[3,1], 
              int.psiB = psi_ests[4,1], int.psiNB = psi_ests[5,1],
              int.p1 = 0.7, int.p2 = 0.7, int.p3 = 0.7, int.p4 = 0.7, int.p5 = 0.7,
              int.pB = 0.9, int.pNB = 0.5, int.p1M = 0.7, int.p2M = 0.7, int.p3M = 0.7, int.p4M = 0.7, 
              int.p5M = 0.7, int.pBM = 0.7, 
              b.sstP = 0, b.sst1 = 0, b.sst.psi = 0, b.sstB = 0, 
              b.npgoP = 0, b.npgo1 = 0, b.npgo.psi = 0, b.npgoB = 0,
              eps.p = c(rep(0, n_occasions)), 
              epsP = array(0, dim = c(6, n_occasions-1)), 
              eps1 = array(0, dim = c(6, n_occasions-1)),
              eps2 = array(0, dim = c(6, n_occasions-1)),
              epsPB = array(0, dim = c(2, n_occasions-1)),
              epsB = array(0, dim = c(6, n_occasions-1)),
              eps.psiPB = array(0, dim = c(4, n_occasions-1)),
              eps.psiB = array(0, dim = c(4, n_occasions-1)),
              eps.psiNB = array(0, dim = c(4, n_occasions-1)),
              p.delB = c(0.4, 0.5, 0.75), 
              b.massP = 0, b.massPM = 0, 
              b.mass1 = 0, b.mass1M = 0, 
              b.regP = c(rep(0,6)), b.reg1 = c(rep(0,6)), b.reg2 = c(rep(0,6)), 
              b.regPB = c(rep(0,2)),  
              p.delB = c(0.4, 0.5, 0.75),
              z = z.init, zm = z.init.m)

### parameters
params <- c('mu.P', 'mu.1', 'mu.2', 'mu.3', 'mu.4', 'mu.5', 'mu.B', 'mu.NB',
            'mu.PM', 'mu.1M', 'mu.2M', 'mu.3M', 'mu.4M', 'mu.5M', 'mu.BM', 
            'mu.psi3', 'mu.psi4', 'mu.psi5', 'mu.psiB', 'mu.psiNB',
  'phiP.prob', 'phi1.prob', 'phi2.prob', 'phi3.prob', 'phi4.prob', 'phi5.prob',
            'phiPM.prob', 'phi1M.prob', 'phi2M.prob', 'phi3M.prob', 'phi4M.prob', 'phi5M.prob',
            'phiB.prob', 'phiNB.prob', 'phiBM.prob',
            'psi3.prob', 'psi4.prob', 'psi5.prob', 'psiB.prob', 'psiNB.prob',
            'epsP', 'eps1', 'eps2', 'epsPB','epsB', 'eps.psiPB', 'eps.psiB',  
            'b.delB', 'p.delB', 'b.eff', 'eps.p', 
            'b.sstP', 'b.sst1', 'b.sst.psi', 'b.sstB', 'b.npgoP', 'b.npgo1', 'b.npgo.psi', 'b.npgoB',
            'sigma.p', 
            'b.massP', 'b.mass1', 'b.massPM', 'b.mass1M', 
            'Ntot', 'Ntot_f', 'N_f', 'Ntot_m', 'N_m',   
            'b.regP', 'b.reg1', 'b.reg2', 'b.regPB', 'b.regB',  
            'b.reg.psi3', 'b.reg.psi4', 'b.reg.psi5', 'b.reg.psiB', 'b.reg.psiNB')

### run model
ni = 35000; nc = 3; nb = 20000; nt = 2; adaptInterval = 100

t.start <- Sys.time() 
cores=detectCores() 
used.cores = min(nc, cores) 
cl <- makeCluster(nc, setup_strategy = "sequential") 
registerDoParallel(cl) 

foreach(i = 1:nc) %dopar% { 
  library(nimble)
  library(here)
  source(here("scripts", "nimbleFunctions.R"))
  
  Rmodel <- nimbleModel(code=SSL_IPM, constants=nim.constants, 
                        data=nim.data, calculate=F, check=F, inits=inits)
  
  conf <- configureMCMC(Rmodel,monitors=params,control = list(adaptInterval = adaptInterval), 
                        thin=nt, useConjugacy = FALSE, enableWAIC = T)
  Rmcmc <- buildMCMC(conf)  
  Cmodel <- compileNimble(Rmodel)
  Cmcmc <- compileNimble(Rmcmc, project = Rmodel)
  
  out <- runMCMC(Cmcmc, niter = ni, nburnin = nb , nchains = 1, inits = inits,
                 setSeed = FALSE, progressBar = TRUE, samplesAsCodaMCMC = TRUE) 
  
  version <- '2.2_env_track_'
  saveRDS(out, here('results', 'best', paste("out.parallel-", version, "spStable-",i,".RDS", sep = ""))) 
  
} # parallel loop

stopCluster(cl) 

t.end <- Sys.time() 
(runTime <- t.end - t.start)

version <- '2.2_env_track_'

out_1 <- readRDS(here::here('results', 'best', paste("out.parallel-", version, "spStable-1.RDS", sep = "")))
out_2 <- readRDS(here::here('results', 'best', paste("out.parallel-", version, "spStable-2.RDS", sep = "")))
out_3 <- readRDS(here::here('results', 'best', paste("out.parallel-", version, "spStable-3.RDS", sep = "")))

# combine them and make an mcmc object
library(coda)
out <- list(`out_1`, `out_2`, `out_3`) %>% as.mcmc.list()


```



```{r sensitivity}

    out_1 <- readRDS(here::here('results', 'march', paste("out.parallel-2.2spStable-1.RDS", sep = "")))
    out_2 <- readRDS(here::here('results', 'march', paste("out.parallel-2.2spStable-2.RDS", sep = "")))
    out_3 <- readRDS(here::here('results', 'march', paste("out.parallel-2.2spStable-3.RDS", sep = "")))

    post <- list(`out_1`, `out_2`, `out_3`) %>% as.mcmc.list()
    post <- as.matrix(post)
#     
#from parallel run
nSamples <- dim(post)[1]
n_occasions <- 19
# nyears.burnin <- 8
nyears.burnin <- 0

#get full posteriors rather than just summary stats
Ntot_post <- post[,grepl('Ntot', colnames(post)) & !grepl('_f', colnames(post))
                  & !grepl('_m', colnames(post))] %>% reshape2::melt() %>%
  transform(year = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+)\\].*$', '\\1',
                                                Var2)))) %>%
  transform(region = as.numeric(gsub('.+\\[([0-9]+), ([0-9]+)\\].*$', '\\2', Var2))) %>%
  transform(Ntot = value) %>% dplyr::select(-c(value, Var2))

phi_post <- post[,grepl('.prob', colnames(post))] %>% reshape2::melt() %>%
  transform(year = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+)\\].*$', '\\2',
                                                Var2)))) %>%
  transform(region = as.numeric(gsub('.+\\[([0-9]+), ([0-9]+)\\].*$', '\\1', Var2))) %>%
  transform(variable = sub("\\[.*", "", Var2)) %>%
  transform(variable = gsub('.prob', '', variable))

#### lambda array; want lambda from Ntot == 2000-2018
## Ntot[9,r] == 2000, so want growth rates starting from t = 9/2000 (t-1) to 10/2001 (t)
# t == 11/2002; t == 12/2003; t == 13/2004; t == 14/2005; t == 15/2006; t == 16/2007; t == 17/2008;
# t == 18/2009; t == 19/2010; t == 20/2011; t == 21/2012; t == 22/2013; t == 23/2014; t == 24/2015;
# t == 25/2016; t == 26/2017; t == 27/2018
# need to end with the numerator being 2018 (Ntot[27]) and denominator being 2017 (Ntot[26])
lambda <- array(NA, dim = c(nSamples, 6, n_occasions-1))
for (r in 1:6) {
  for (t in (nyears.burnin+2):(n_occasions+nyears.burnin)) {
  lambda[,r,(t-nyears.burnin-1)] <- Ntot_post[Ntot_post$region == r &
                               Ntot_post$year == (t), 'Ntot']/
        Ntot_post[Ntot_post$region == r &
                    Ntot_post$year == (t-1), 'Ntot']
  }
}

# phiP.corr <- phiPM.corr <- phi1.corr <- phi2.corr <- phi3.corr <- phi4.corr <- phi5.corr <- phiB.corr <- psi4.corr <- psiB.corr <- array(NA, dim = c(nSamples, 4, n_occasions-1))
# 
# 
# for (r in 1:4) {
#   for (t in (1):(n_occasions-1)) { #t = 1 == 2000-2001 rates
#   phiP.corr[,r,t] <- phi_post[phi_post$variable == 'phiP' & phi_post$region == r &
#                                phi_post$year == (t), 'value']
#   # phiPM.corr[,r,t] <- phi_post[phi_post$variable == 'phiPM' & phi_post$region == r &
#   #                              phi_post$year == (t), 'value']
#   # phi1M.corr[,r,t] <- phi_post[phi_post$variable == 'phi1M' & phi_post$region == r &
#   #                              phi_post$year == (t), 'value']
#   phi1.corr[,r,t] <- phi_post[phi_post$variable == 'phi1' & phi_post$region == r &
#                                phi_post$year == (t), 'value']
#   phi2.corr[,r,t] <- phi_post[phi_post$variable == 'phi2' & phi_post$region == r &
#                                phi_post$year == (t), 'value']
#   # phi2M.corr[,r,t] <- phi_post[phi_post$variable == 'phi2M' & phi_post$region == r &
#   #                              phi_post$year == (t), 'value']
#   phi3.corr[,r,t] <- phi_post[phi_post$variable == 'phi3' & phi_post$region == r &
#                                phi_post$year == (t), 'value']
#   phi4.corr[,r,t] <- phi_post[phi_post$variable == 'phi4' & phi_post$region == r &
#                                phi_post$year == (t), 'value']
#   phi5.corr[,r,t] <- phi_post[phi_post$variable == 'phi5' & phi_post$region == r &
#                                phi_post$year == (t), 'value']
#   phiB.corr[,r,t] <- phi_post[phi_post$variable == 'phiB' & phi_post$region == r &
#                                phi_post$year == (t), 'value']
#   # psi3.corr[,r,t] <- phi_post[phi_post$variable == 'psi3' & phi_post$region == r &
#   #                              phi_post$year == (t), 'value']
#   psi4.corr[,r,t] <- phi_post[phi_post$variable == 'psi4' & phi_post$region == r &
#                                phi_post$year == (t), 'value']
#   # psi5.corr[,r,t] <- phi_post[phi_post$variable == 'psi5' & phi_post$region == r &
#   #                              phi_post$year == (t), 'value']
#   psiB.corr[,r,t] <- phi_post[phi_post$variable == 'psiB' & phi_post$region == r &
#                                phi_post$year == (t), 'value']
# }
# }
# 
# 
# ## correlation coefficients
# #get posterior of correlations by calculating them at each mcmc sample for all years
# phiP.corr.vals <- phiPM.corr.vals <- phi1.corr.vals <- phi2.corr.vals <- phi3.corr.vals <- 
#   phi4.corr.vals <- phi5.corr.vals <- phiB.corr.vals <- psi4.corr.vals <- psiB.corr.vals <- array(NA, dim = c(nSamples,4))
# 
# for (r in 1:4) {
# for (i in 1:nSamples) {
#   phiP.corr.vals[i,r] <- cor(lambda[i,r,1:(n_occasions-1)], phiP.corr[i,r,1:(n_occasions-1)])
#   # phiPM.corr.vals[i,r] <- cor(lambda[i,r,1:(n_occasions-1)], phiPM.corr[i,r,1:(n_occasions-1)])
#   phi1.corr.vals[i,r] <- cor(lambda[i,r,1:(n_occasions-1)], phi1.corr[i,r,1:(n_occasions-1)])
#   # phi1M.corr.vals[i,r] <- cor(lambda[i,r,1:(n_occasions-1)], phi1M.corr[i,r,1:(n_occasions-1)])
#   phi2.corr.vals[i,r] <- cor(lambda[i,r,1:(n_occasions-1)], phi2.corr[i,r,1:(n_occasions-1)])
#   # phi2M.corr.vals[i,r] <- cor(lambda[i,r,1:(n_occasions-1)], phi2M.corr[i,r,1:(n_occasions-1)])
#   phi3.corr.vals[i,r] <- cor(lambda[i,r,1:(n_occasions-1)], phi3.corr[i,r,1:(n_occasions-1)])
#   phi4.corr.vals[i,r] <- cor(lambda[i,r,1:(n_occasions-1)], phi4.corr[i,r,1:(n_occasions-1)])
#   phi5.corr.vals[i,r] <- cor(lambda[i,r,1:(n_occasions-1)], phi5.corr[i,r,1:(n_occasions-1)])
#   phiB.corr.vals[i,r] <- cor(lambda[i,r,1:(n_occasions-1)], phiB.corr[i,r,1:(n_occasions-1)])
#   # psi3.corr.vals[i,r] <- cor(lambda[i,r,1:(n_occasions-1)], psi3.corr[i,r,1:(n_occasions-1)])
#   psi4.corr.vals[i,r] <- cor(lambda[i,r,1:(n_occasions-1)], psi4.corr[i,r,1:(n_occasions-1)])
#   # psi5.corr.vals[i,r] <- cor(lambda[i,r,1:(n_occasions-1)], psi5.corr[i,r,1:(n_occasions-1)])
#   psiB.corr.vals[i,r] <- cor(lambda[i,r,1:(n_occasions-1)], psiB.corr[i,r,1:(n_occasions-1)])
# }
# }
# 
# #quantiles of correlation coefficients
# corr.sum <- data.frame(region = 1:4,
#                        phiP.med = apply(phiP.corr.vals, 2, median),
#                             phiP.lower = apply(phiP.corr.vals, c(2), function(x) quantile(x, probs = 0.025)),
#                             phiP.upper = apply(phiP.corr.vals, c(2), function(x) quantile(x, probs = 0.975)),
#                        # phiPM.med = apply(phiPM.corr.vals, 2, median),
#                        #      phiPM.lower = apply(phiPM.corr.vals, c(2), function(x) quantile(x, probs = 0.025)),
#                        #      phiPM.upper = apply(phiPM.corr.vals, c(2), function(x) quantile(x, probs = 0.975)),
#                        phi1.med = apply(phi1.corr.vals, 2, median),
#                             phi1.lower = apply(phi1.corr.vals, c(2), function(x) quantile(x, probs = 0.025)),
#                             phi1.upper = apply(phi1.corr.vals, c(2), function(x) quantile(x, probs = 0.975)),
#                        # phi1M.med = apply(phi1M.corr.vals, 2, median),
#                        #      phi1M.lower = apply(phi1M.corr.vals, c(2), function(x) quantile(x, probs = 0.025)),
#                        #      phi1M.upper = apply(phi1M.corr.vals, c(2), function(x) quantile(x, probs = 0.975)),
#                        phi2.med = apply(phi2.corr.vals, 2, median),
#                             phi2.lower = apply(phi2.corr.vals, c(2), function(x) quantile(x, probs = 0.025)),
#                             phi2.upper = apply(phi2.corr.vals, c(2), function(x) quantile(x, probs = 0.975)),
#                        phi3.med = apply(phi3.corr.vals, 2, median),
#                             phi3.lower = apply(phi3.corr.vals, c(2), function(x) quantile(x, probs = 0.025)),
#                             phi3.upper = apply(phi3.corr.vals, c(2), function(x) quantile(x, probs = 0.975)),
#                        phi4.med = apply(phi4.corr.vals, 2, median),
#                             phi4.lower = apply(phi4.corr.vals, c(2), function(x) quantile(x, probs = 0.025)),
#                             phi4.upper = apply(phi4.corr.vals, c(2), function(x) quantile(x, probs = 0.975)),
#                        phi5.med = apply(phi5.corr.vals, 2, median),
#                             phi5.lower = apply(phi5.corr.vals, c(2), function(x) quantile(x, probs = 0.025)),
#                             phi5.upper = apply(phi5.corr.vals, c(2), function(x) quantile(x, probs = 0.975)),
#                        phiB.med = apply(phiB.corr.vals, 2, median),
#                             phiB.lower = apply(phiB.corr.vals, c(2), function(x) quantile(x, probs = 0.025)),
#                             phiB.upper = apply(phiB.corr.vals, c(2), function(x) quantile(x, probs = 0.975)),
#                        psi4.med = apply(psi4.corr.vals, 2, median),
#                             psi4.lower = apply(psi4.corr.vals, c(2), function(x) quantile(x, probs = 0.025)),
#                             psi4.upper = apply(psi4.corr.vals, c(2), function(x) quantile(x, probs = 0.975)),
#                        psiB.med = apply(psiB.corr.vals, 2, median),
#                             psiB.lower = apply(psiB.corr.vals, c(2), function(x) quantile(x, probs = 0.025)),
#                             psiB.upper = apply(psiB.corr.vals, c(2), function(x) quantile(x, probs = 0.975))) %>%
#   reshape2::melt(id.vars = 'region') %>%
#   transform(measure = ifelse(grepl('med', variable), 'median',
#                                    ifelse(grepl('lower', variable), 'lower', 'upper'))) %>%
#   transform(variable = gsub('.med', '', variable)) %>% transform(variable = gsub('.lower', '', variable)) %>%
#   transform(variable = gsub('.upper', '', variable)) %>%
#   transform(value = as.numeric(value)) %>%
#   reshape2::dcast(region+variable ~ measure, value.var = 'value') %>%
#   transform(variable = factor(variable, levels = c('phiP', 'phiPM', 'phi1', 'phi1M', 'phi2', 'phi2M', 'phi3',
#                                                    'phi4', 'phi5', 'phiB', 'psi3', 'psi4', 'psi5', 'psiB'),
#                               labels = c('Pup', 'Pup (M)', '1', '1 (M)', '2', '2 (M)', '3',
#                                                    '4', '5', 'B', 'psi3', 'psi4', 'psi5', 'psiB')))
# 
# write.csv(corr.sum, file = here::here('results', 'processed', 'corr.sum.csv'), row.names = F)

corr.sum <- read.csv(file = here::here('results', 'processed', 'corr.sum.csv'), header = T)

#plot of just correlation coefficients
#region colors
corr_sum_plot <- ggplot(corr.sum %>% filter(!grepl('M', variable)), 
                        aes(x = variable, y = median, group = factor(region), color = factor(region))) +
  geom_point(position = position_dodge(0.5)) +
  geom_errorbar(aes(x = variable, ymin = lower, ymax = upper), position = position_dodge(0.5)) +
  geom_hline(aes(yintercept = 0), color = 'red', linetype = 'dotted') +
  xlab('Parameter') + ylab('Correlation coefficient (median & 95% CI)') +
  plot_theme(panel.border = element_rect(fill = NA), legend.position = 'top') + 
  scale_color_manual(values = rainbow2[-c(1,4)], name = 'Region')

#for cross-hair plot
#derive quantiles of demographic rates
lambda_med <- apply(lambda, c(2,3), median)
lambda_lower <- apply(lambda, c(2,3), function(x) quantile(x, prob = 0.025, na.rm = T))
lambda_upper <- apply(lambda, c(2,3), function(x) quantile(x, prob = 0.975, na.rm = T))

lambda_long <- lambda_med %>% reshape2::melt(value.name = 'lambda_med') %>% 
  dplyr::rename(region = Var1, year = Var2) %>%
  merge(lambda_lower %>% reshape2::melt(value.name = 'lambda_lower') %>% 
  dplyr::rename(region = Var1, year = Var2), by = c('year', 'region')) %>%
  merge(lambda_upper %>% reshape2::melt(value.name = 'lambda_upper') %>% 
  dplyr::rename(region = Var1, year = Var2), by = c('year', 'region')) %>%
  transform(region = factor(region, levels = 1:6, labels = c("C.GULF", "E.ALEU", "E.GULF",
                                                        "W.GULF", "C.ALEU", "W.ALEU")))

corr_plot_vals <- bind_rows(phi_post_sum %>% filter(variable != 'phiNB'), 
                            psi_post_sum %>% filter(variable %nin% c('psiNB', 'psi3', 'psi5'))) %>%
  merge(lambda_long, by = c('region', 'year')) 

#make 'labels' df
# corr_labels <- data.frame(variable = c('Adult B survival', 'Adult NB survival', 
#                                   'Calf survival', 'YOY survival', 'Fecundity'),
#                      mean = round(c(phiB.corr.vals[2], phiN.corr.vals[2], phiC.corr.vals[2], 
#                               phiY.corr.vals[2], psiB.corr.vals[2]),2),
#                      lower = round(c(phiB.corr.vals[1], phiN.corr.vals[1], phiC.corr.vals[1], 
#                               phiY.corr.vals[1], psiB.corr.vals[1]),2),
#                      upper = round(c(phiB.corr.vals[3], phiN.corr.vals[3], phiC.corr.vals[3], 
#                               phiY.corr.vals[3], psiB.corr.vals[3]),2)) %>%
#   transform(variable = factor(variable, levels = c('Adult B survival', 'Adult NB survival', 
#                                                    'Calf survival', 
#                                                    'YOY survival', 'Fecundity')))

corr_plot <- ggplot(corr_plot_vals %>% filter(!grepl('M', variable)), 
       aes(med, lambda_med)) +
  geom_linerange(aes(x = med, ymin = lambda_lower, ymax = lambda_upper), col = 'grey') +
  geom_linerangeh(aes(y = lambda_med, xmin = lower, xmax = upper), col = 'grey') +
  geom_point(aes(fill = variable), col = 'black', shape = 21) +
  geom_smooth(method = 'lm', se = F, col = 'black', size = 0.6) +
  # geom_text(data = corr_labels, aes(label = paste0('r =', mean, ' ', '(', lower, '-', upper, ')'),
  #                              group = variable, y = rep(1.14,5),
  #                              x = c(0.90, 0.83, 0.47, 0.8, 0.19)),
  #             parse = F, inherit.aes = F, colour = "black", size = 3) +
  xlab('Parameter value') + ylab('Population growth rate') +
    facet_wrap(~variable, scales = 'free_x') +
  plot_theme(panel.border = element_rect(fill = NA), legend.position = 'none') + 
  # scale_fill_manual(values = rainbow2[-c(1,4)])
  scale_fill_manual(values=lacroix_palette("PeachPear",type = "continuous", n = 9)) 

```

```{r env covs}

version <- '2.2_env_track_'
out_1 <- readRDS(here::here('results', 'best', paste0("out.parallel-", version, "spStable-1.RDS")))
out_2 <- readRDS(here::here('results', 'best', paste0("out.parallel-", version, "spStable-2.RDS")))
out_3 <- readRDS(here::here('results', 'best', paste0("out.parallel-", version, "spStable-3.RDS")))

post <- list(`out_1`, `out_2`, `out_3`) %>% as.mcmc.list()
post <- as.matrix(post)

post_sum <- data.frame(
  med = apply(post, 2, function(x) quantile(x, probs = 0.5, na.rm = T, names = F)),
  lower = apply(post, 2, function(x) quantile(x, probs = 0.025, na.rm = T, names = F)),
  upper = apply(post, 2, function(x) quantile(x, probs = 0.975, na.rm = T, names = F)))
post_sum$variable <- row.names(post_sum)

covs <- post_sum %>% 
  filter(variable %in% c('b.npgoP', 'b.npgo1', 'b.npgo.psi', 'b.npgoB', 'b.sstP', 'b.sst1', 'b.sst.psi', 'b.sstB')) %>%
  transform(cov = ifelse(grepl('sst', variable), 'SST', 'NPGO')) %>%
  transform(rate = ifelse(grepl('P', variable), 'P', ifelse(grepl(1, variable), '1',
                                                            ifelse(grepl('B', variable), 'B', 'psi')))) %>%
  transform(rate = factor(rate, levels = c('P', '1', 'B', 'psi')))

ggplot(covs %>% filter(cov == 'NPGO'), aes(rate, med)) +
  geom_point() +
  geom_linerange(aes(ymin = lower, ymax = upper)) +
  geom_hline(aes(yintercept = 0), linetype = 'dotted', color = 'red') +
  ylab('Logit-scale effect') + xlab('Demographic rate') +
  facet_grid(~cov) +
  pres_theme_180() +
  scale_x_discrete(labels = c('P' = parse(text = TeX('$phi_P$')), 
                              '1' = parse(text = TeX('$phi_{1,2}$')),
                              'B' = parse(text = TeX('$phi_B$')), 
                              'psi' = parse(text = TeX('$psi$'))))

```

```{r base projection prep}

version <- '2.2'
out_1 <- readRDS(here::here('results', 'march', paste0("out.parallel-", version, "spStable-1.RDS")))
out_2 <- readRDS(here::here('results', 'march', paste0("out.parallel-", version, "spStable-2.RDS")))
out_3 <- readRDS(here::here('results', 'march', paste0("out.parallel-", version, "spStable-3.RDS")))

post <- list(`out_1`, `out_2`, `out_3`) %>% as.mcmc.list()
post <- as.matrix(post)

post_sum <- data.frame(
  med = apply(post, 2, function(x) quantile(x, probs = 0.5, na.rm = T, names = F)),
  lower = apply(post, 2, function(x) quantile(x, probs = 0.025, na.rm = T, names = F)),
  upper = apply(post, 2, function(x) quantile(x, probs = 0.975, na.rm = T, names = F)))
post_sum$variable <- row.names(post_sum)

all_pars <- colnames(post)
eps_pars <- all_pars[which(grepl('eps', all_pars))]

nSims <- 20
nSamples <- dim(post)[1]
nyears.proj <- 100
G_f <- 8
G_m <- 7
nSamp <- 2000
n_r <- 6
nyears.burnin <- 0
n_occasions <- 19

Ntot_post <- post[(nSamples-nSamp+1):nSamples,grepl('Ntot', colnames(post)) & !grepl('_f', colnames(post)) 
                  & !grepl('_m', colnames(post))] %>% 
  reshape2::melt() %>%
  transform(year = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+)\\].*$', '\\1', Var2)))) %>%
  transform(region = as.numeric(gsub('.+\\[([0-9]+), ([0-9]+)\\].*$', '\\2', Var2))) %>%
  transform(Ntot = value) %>% dplyr::select(-c(value, Var2))

phi_post <- post[(nSamples-nSamp+1):nSamples,grepl('.prob', colnames(post))] %>% reshape2::melt() %>%
  transform(year = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+)\\].*$', '\\2',
                                                Var2)))) %>%
  transform(region = as.numeric(gsub('.+\\[([0-9]+), ([0-9]+)\\].*$', '\\1', Var2))) %>%
  transform(variable = sub("\\[.*", "", Var2)) %>%
  transform(variable = gsub('.prob', '', variable))

mu_post <- post[(nSamples-nSamp+1):nSamples,grepl('mu.', colnames(post))] %>% reshape2::melt() 

reg_post <- post[(nSamples-nSamp+1):nSamples,grepl('reg.', colnames(post))] %>% reshape2::melt() %>%
    transform(region = as.numeric(gsub('.+\\[([0-9]+)\\].*$', '\\1', Var2))) %>%
  transform(variable = sub("\\[.*", "", Var2)) 

#get male and female populations; dim = c(age_class 1:8, t 1:27, r 1:6)
N_f_post <- post[(nSamples-nSamp+1):nSamples,grepl('N_f', colnames(post))] %>% reshape2::melt() %>%
  transform(Var2 = as.character(Var2)) %>%
  transform(age = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+), ([0-9]+)\\].*$', '\\1', Var2)))) %>%
  transform(year = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+), ([0-9]+)\\].*$', '\\2', Var2)))) %>%
  transform(region = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+), ([0-9]+)\\].*$', '\\3', Var2))))

N_m_post <- post[(nSamples-nSamp+1):nSamples,grepl('N_m', colnames(post))] %>% reshape2::melt() %>%
  transform(Var2 = as.character(Var2)) %>%
  transform(age = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+), ([0-9]+)\\].*$', '\\1', Var2)))) %>%
  transform(year = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+), ([0-9]+)\\].*$', '\\2', Var2)))) %>%
  transform(region = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+), ([0-9]+)\\].*$', '\\3', Var2))))


#rebuild in array format
N_f <- array(NA, dim = c(nSamp, G_f, (n_occasions+nyears.burnin), n_r))
for (r in 1:n_r) {
  for (a in 1:G_f) {
    for (t in 1:(n_occasions+nyears.burnin)) {
        N_f[,a,t,r] <- N_f_post[N_f_post$age == a & N_f_post$year == t & N_f_post$region == r, 'value']
    }
  }
}

N_m <- array(NA, dim = c(nSamp, G_m, (n_occasions+nyears.burnin), n_r))
for (r in 1:n_r) {
  for (a in 1:G_m) {
    for (t in 1:(n_occasions+nyears.burnin)) {
        N_m[,a,t,r] <- N_m_post[N_m_post$age == a & N_m_post$year == t & N_m_post$region == r, 'value']
    }
  }
}

Ntot_est <- array(NA, dim = c(nSamp, (n_occasions+nyears.burnin), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions+nyears.burnin)) {
        Ntot_est[,t,r] <- Ntot_post[Ntot_post$year == t & Ntot_post$region == r, 'Ntot']
  }
}

phiP_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        phiP_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'phiP', 'value']
    }
}
phiPM_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        phiPM_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'phiPM', 'value']
    }
}
phi1_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        phi1_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'phi1', 'value']
    }
}
phi1M_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        phi1M_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'phi1M', 'value']
    }
}
phi2_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        phi2_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'phi2', 'value']
    }
}
phi2M_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        phi2M_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'phi2M', 'value']
    }
}
phi3_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        phi3_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'phi3', 'value']
    }
}
phi3M_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        phi3M_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'phi3M', 'value']
    }
}
phi4_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        phi4_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'phi4', 'value']
    }
}
phi4M_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        phi4M_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'phi4M', 'value']
    }
}
phi5_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        phi5_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'phi5', 'value']
    }
}
phi5M_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        phi5M_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'phi5M', 'value']
    }
}
phiB_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        phiB_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'phiB', 'value']
    }
}
phiNB_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        phiNB_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'phiNB', 'value']
    }
}
phiBM_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        phiBM_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'phiBM', 'value']
    }
}
psi3_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        psi3_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'psi3', 'value']
    }
}
psi4_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        psi4_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'psi4', 'value']
    }
}
psi5_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        psi5_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'psi5', 'value']
    }
}
psiB_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        psiB_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'psiB', 'value']
    }
}
psiNB_arr <- array(NA, dim = c(nSamp, (n_occasions-1), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions-1)) {
        psiNB_arr[,t,r] <- phi_post[phi_post$year == t & phi_post$region == r & phi_post$variable == 'psiNB', 'value']
    }
  }

```

```{r base proj}

#storage for sim/region loop
Ntot.sim <- array(NA, dim = c(nSamp, n_occasions+nyears.burnin+nyears.proj, nSims, n_r))
p.ext.sim <- p.ad.ext.sim <- p.neg.sim <- lambda.mean.sim <- data.frame()
p.ext <- p.ad.ext <- p.neg <- array(NA, dim = c(nSims, n_r))
lambda.mean <- lambda.upper <- lambda.lower <- array(NA, dim = c(nSims, n_r))

picks <- sample(1:(n_occasions-1), nyears.proj, replace = T)

for (sim in 1:nSims) {
  for (r in 1:n_r) {
   
    #temp storage for population model objects; need a row for each of nSamples and columns for each projection year
    N_4B <- N_5B <- N_6B <- N_6NB <- N_BB <- N_BNB <- array(NA, dim = c(nSamp, nyears.proj)) 
    Ntot_f_proj <- Ntot_m_proj <- array(NA, dim = c(nSamp, nyears.proj))
    N_NBNB <- N_NBB <- N_B <- N_NB <- N_A1 <- N_Aplus <- array(NA, dim = c(nSamp, nyears.proj))
    
    #total population size for data period + projections (Ntot) and just projections (Ntot_proj)
    Ntot <- Ntot_f <- Ntot_m <- array(NA, dim = c(nSamp, n_occasions+nyears.burnin+nyears.proj)) 
    Ntot_proj <- array(NA, dim = c(nSamp, nyears.proj))
    N_f_proj <- array(NA, dim = c(nSamp, G_f, nyears.proj))
    N_m_proj <- array(NA, dim = c(nSamp, G_m, nyears.proj))
    
    #demographic rates
    phiP.prob.proj <- phi1.prob.proj <- phi2.prob.proj <- array(NA, dim = c(nSamp, nyears.proj-1))
    phi3.prob.proj <- phi4.prob.proj <- phi5.prob.proj <- array(NA, dim = c(nSamp, nyears.proj-1))
    phiB.prob.proj <- phiNB.prob.proj <- array(NA, dim = c(nSamp, nyears.proj-1))
    
    psi3.prob.proj <- psi4.prob.proj <- psi5.prob.proj <- array(NA, dim = c(nSamp, nyears.proj-1))
    psiB.prob.proj <- psiNB.prob.proj <- array(NA, dim = c(nSamp, nyears.proj-1))

    phiPM.prob.proj <- phi1M.prob.proj <- phi2M.prob.proj <- array(NA, dim = c(nSamp, nyears.proj-1))
    phi3M.prob.proj <- phi4M.prob.proj <- phi5M.prob.proj <- array(NA, dim = c(nSamp, nyears.proj-1))
    phiBM.prob.proj <- array(NA, dim = c(nSamp, nyears.proj-1))

    #grab last year from data period to initialize
    N_B[,1] <- N_f[,7,dim(N_f)[3],r]
    N_NB[,1] <- N_f[,8,dim(N_f)[3],r]
    N_A1[,1] <- N_m[,6,dim(N_f)[3],r]
    N_Aplus[,1] <- N_m[,7,dim(N_f)[3],r]
    
    Ntot[,1:(n_occasions+nyears.burnin)] <- Ntot_est[,1:(n_occasions+nyears.burnin),r] #fills up to Ntot[,26]
    Ntot_proj[,1] <- Ntot_est[,dim(Ntot_est)[2],r] #grab 19th year
    N_f_proj[,,1] <- N_f[,,dim(N_f)[3],r] # populate with last year from data period
    N_m_proj[,,1] <- N_m[,,dim(N_m)[3],r]

   ## projection; sigma == sd, sigma^2 == variance, 1/variance == precision
  for (t in (1:(nyears.proj-1))) {
    year_pick <- picks[t]
    
    phiP.prob.proj[,t] <- phiP_arr[,year_pick,r]
    phiPM.prob.proj[,t] <- phiPM_arr[,year_pick,r]
    phi1.prob.proj[,t] <- phi1_arr[,year_pick,r]
    phi1M.prob.proj[,t] <- phi1M_arr[,year_pick,r]
    phi2.prob.proj[,t] <- phi2_arr[,year_pick,r]
    phi2M.prob.proj[,t] <- phi2M_arr[,year_pick,r]
    phi3.prob.proj[,t] <- phi3_arr[,year_pick,r]
    phi3M.prob.proj[,t] <- phi3M_arr[,year_pick,r]
    phi4.prob.proj[,t] <- phi4_arr[,year_pick,r]
    phi4M.prob.proj[,t] <- phi4M_arr[,year_pick,r]
    phi5.prob.proj[,t] <- phi5_arr[,year_pick,r]
    phi5M.prob.proj[,t] <- phi5M_arr[,year_pick,r]
    phiB.prob.proj[,t] <- phiB_arr[,year_pick,r]
    phiNB.prob.proj[,t] <- phiNB_arr[,year_pick,r]
    phiBM.prob.proj[,t] <- phiBM_arr[,year_pick,r]
    psi3.prob.proj[,t] <- psi3_arr[,year_pick,r]
    psi4.prob.proj[,t] <- psi4_arr[,year_pick,r]
    psi5.prob.proj[,t] <- psi5_arr[,year_pick,r]
    psiB.prob.proj[,t] <- psiB_arr[,year_pick,r]
    psiNB.prob.proj[,t] <- psiNB_arr[,year_pick,r]
    
    ###FEMALES
    N_f_proj[,2,t+1] <- rbinom(nSamp, N_f_proj[,1,t], phiP.prob.proj[,t]) #yearlings
    N_f_proj[,3,t+1] <- rbinom(nSamp, N_f_proj[,2,t], phi1.prob.proj[,t]) #2yos
    N_f_proj[,4,t+1] <- rbinom(nSamp, N_f_proj[,3,t], phi2.prob.proj[,t]) #3yos
    N_f_proj[,5,t+1] <- rbinom(nSamp, N_f_proj[,4,t], phi3.prob.proj[,t]*(1-psi3.prob.proj[,t])) #4yo PB
    N_f_proj[,6,t+1] <- rbinom(nSamp, N_f_proj[,5,t], phi4.prob.proj[,t]*(1-psi4.prob.proj[,t])) #5yo PB 

    N_4B[,t+1] <- rbinom(nSamp, N_f_proj[,4,t], phi3.prob.proj[,t]*psi3.prob.proj[,t]) #4yo breeders 
    N_5B[,t+1] <- rbinom(nSamp, N_f_proj[,5,t], phi4.prob.proj[,t]*psi4.prob.proj[,t]) #5yo first-B  

    N_6B[,t+1] <- rbinom(nSamp, N_f_proj[,6,t], phi5.prob.proj[,t]*psi5.prob.proj[,t]) #6yo first-B 
    N_6NB[,t+1] <- rbinom(nSamp, N_f_proj[,6,t], phi5.prob.proj[,t]*(1-psi5.prob.proj[,t])) #6yo NB that was PB at 5 

    ## Plus groups
    #breeders
    N_BB[,t+1] <- rbinom(nSamp, N_B[,t], phiB.prob.proj[,t]*psiB.prob.proj[,t]) # plus grp B given B (#6)
    N_BNB[,t+1] <- rbinom(nSamp, N_NB[,t], phiNB.prob.proj[,t]*psiNB.prob.proj[,t]) # plus grp B given NB (#8)

    #non breeders
    N_NBNB[,t+1] <- rbinom(nSamp, N_NB[,t], phiNB.prob.proj[,t]*(1-psiNB.prob.proj[,t])) # plus grp NB given NB (#9)
    N_NBB[,t+1] <- rbinom(nSamp, N_B[,t], phiB.prob.proj[,t]*(1-psiB.prob.proj[,t])) # plus grp NB given B (#7)

    #total breeders and non-breeders
    N_B[,t+1] <- N_4B[,t+1]+N_5B[,t+1]+N_6B[,t+1]+N_BB[,t+1]+N_BNB[,t+1] # total breeders
    N_NB[,t+1] <- N_6NB[,t+1]+N_NBB[,t+1]+N_NBNB[,t+1] # total breeders

    N_f_proj[,7,t+1] <- N_B[,t+1]   #B
    N_f_proj[,8,t+1] <- N_NB[,t+1]  #NB
    N_f_proj[,1,t+1] <- round(N_B[,t+1]/2) #pups 

     Ntot_f_proj[,t+1] <- rowSums(N_f_proj[1:nSamp,1:8,t+1])

    ###MALES
    N_m_proj[,1,t+1] <- round(N_B[,t+1]/2) #pups
    N_m_proj[,2,t+1] <- rbinom(nSamp, N_m_proj[,1,t], phiPM.prob.proj[,t]) #yearlings
    N_m_proj[,3,t+1] <- rbinom(nSamp, N_m_proj[,2,t], phi1M.prob.proj[,t]) #2yos
    N_m_proj[,4,t+1] <- rbinom(nSamp, N_m_proj[,3,t], phi2M.prob.proj[,t]) #3yos
    N_m_proj[,5,t+1] <- rbinom(nSamp, N_m_proj[,4,t], phi3M.prob.proj[,t]) #4yos
    N_m_proj[,6,t+1] <- rbinom(nSamp, N_m_proj[,5,t], phi4M.prob.proj[,t]) #5yos
    N_A1[,t+1] <- rbinom(nSamp, N_m_proj[,6,t], phi5M.prob.proj[,t]) #new adults from 5yos
    N_Aplus[,t+1] <- rbinom(nSamp, N_m_proj[,7,t], phiBM.prob.proj[,t]) #repeat adults 7+

    N_m_proj[,7,t+1] <- N_A1[,t+1] + N_Aplus[,t+1]

    Ntot_m_proj[,t+1] <- rowSums(N_m_proj[1:nSamp,1:7,t+1])
    Ntot_proj[,t+1] <- Ntot_f_proj[,t+1] + Ntot_m_proj[,t+1]

  } #t

#fill space in Ntot with Ntot_proj projection years, essentially bind_cols()
Ntot[,((n_occasions+nyears.burnin+1):(n_occasions+nyears.burnin+nyears.proj))] <- Ntot_proj[,]

###### summarize objects over mcmc samples

#growth rate over the whole study period
lambda.yr.mean <- lambda.yr.lower <- lambda.yr.upper <- numeric(length = length(2:(n_occasions+nyears.burnin+nyears.proj)))
for (t in 2:(n_occasions+nyears.burnin+nyears.proj)) {
  #mean and quantiles per year across mcmc samples; leave na.rm for zero size pops in mcmc samples
  lambda.yr.mean[t] <- mean(Ntot[,t]/(Ntot[,t-1]), na.rm = T)
  lambda.yr.lower[t] <- quantile(Ntot[,t]/(Ntot[,t-1]), probs = 0.025, na.rm = T, names = F)
  lambda.yr.upper[t] <- quantile(Ntot[,t]/(Ntot[,t-1]), probs = 0.975, na.rm = T, names = F)
} #t lambda

#### derive and store values for each simulation

#geometric mean, and quantiles(?)
lambda.mean[sim,r] <- exp(mean(log(lambda.yr.mean[which(lambda.yr.mean>0)])))
lambda.lower[sim,r] <- exp(mean(log(lambda.yr.lower[which(lambda.yr.lower>0)])))
lambda.upper[sim,r] <- exp(mean(log(lambda.yr.upper[which(lambda.yr.upper>0)])))

#prob of having less than 2 individuals and less than 1 breeding age female at end
p.ext[sim,r] <- mean(Ntot[,(n_occasions+nyears.burnin+nyears.proj)]<2)
p.ad.ext[sim,r] <- mean(N_f_proj[,7,nyears.proj]<1)

#probability that have fewer individuals at end than start
p.neg[sim,r] <- mean(Ntot[,(n_occasions+nyears.burnin+nyears.proj)] < Ntot[,1])

#population size at end of projection
# end.size.sim[sim,1:3] <- quantile(Ntot[,(nyears.gap+nyears.ch+proj)], 
#                                 probs = c(0.025, 0.5, 0.975), names = F)

#Ntot
Ntot.sim[1:nSamp,,sim,r] <- as.matrix(Ntot)

# lambda.mean.sim <- bind_rows(lambda.mean, lambda.mean.sim)
# p.neg.sim <- bind_rows(p.neg, p.neg.sim)
# p.ad.ext.sim <- bind_rows(p.ad.ext, p.ad.ext.sim)
# p.neg.sim <- bind_rows(p.neg, p.neg.sim)

} #sim 
} #region

## save objects
saveRDS(Ntot.sim, file = here::here('results', 'projections', 'Ntot.rds'))
saveRDS(lambda.mean, file = here::here('results', 'projections', 'lambda.rds'))
saveRDS(p.ext, file = here::here('results', 'projections', 'p.ext.rds'))
saveRDS(p.ad.ext, file = here::here('results', 'projections', 'p.ad.ext.rds'))
saveRDS(p.neg, file = here::here('results', 'projections', 'p.neg.rds'))

#want mean and CI for each time step and region
Ntot_mean <- apply(Ntot.sim, c(4,2), median)
Ntot_q2.5 <- apply(Ntot.sim, c(4,2), function(x) quantile(x,0.025))
Ntot_q97.5 <- apply(Ntot.sim, c(4,2), function(x) quantile(x,0.975))

#Ntot figures
N_mean_long_sim <- Ntot_mean %>%
  reshape2::melt(value.name = 'mean') %>%
  dplyr::rename(reg = Var1, year = Var2) 

N_low_long_sim <- Ntot_q2.5 %>%
  reshape2::melt(value.name = 'lower') %>%
  dplyr::rename(reg = Var1, year = Var2) 

N_high_long_sim <- Ntot_q97.5 %>%
  reshape2::melt(value.name = 'upper') %>%
  dplyr::rename(reg = Var1, year = Var2) 

N_vals_sim <- N_mean_long_sim %>%
  merge(N_low_long_sim, by = c('reg', 'year')) %>%
  merge(N_high_long_sim, by = c('reg', 'year')) %>%
  arrange(reg, year) %>%
  transform(reg = factor(reg, levels = 1:n_r,
                            labels = c("C.GULF", "E.ALEU", "E.GULF",
                                       "W.GULF", "C.ALEU", "W.ALEU")))


#Ntot; mean trajectories for each region
ggplot(N_vals_sim,
       aes(year, mean, group = factor(reg), col = factor(reg))) +
  geom_line() +
  geom_ribbon(aes(year, ymin = lower, ymax = upper, col = factor(reg), fill = factor(reg), alpha = 0.5), 
              show.legend = F) +
  xlab('') + ylab('Population size') +
  facet_wrap(~reg, scales = 'free_y') +
  plot_theme(legend.position = 'top') +
    scale_x_continuous(limits = c(1,n_occasions+nyears.burnin+nyears.proj),
                     breaks = seq(2, n_occasions+nyears.burnin+nyears.proj, by = 10),
                     labels = seq(2000, (2000+n_occasions+nyears.burnin+nyears.proj), by = 10)) +
  scale_color_manual(values = rainbow2[-c(1,4)], name = '') +
  scale_fill_manual(values = rainbow2[-c(1,4)])

#####posterior summaries; boxplots of posterior means
lambda <- lambda.mean %>% reshape2::melt() %>% dplyr::rename(sim = Var1, reg = Var2)
a <- ggplot(lambda, aes(y=value, col = factor(reg), group = factor(reg))) +
  geom_boxplot(width = 0.5) +
  xlab('') + ylab('Population growth rate') +
  theme_classic() +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())

# p.ext.sim[1:nSamp, 1:n_r]
p.ext <- p.ext %>% reshape2::melt() %>% dplyr::rename(sim = Var1, reg = Var2)
b <- ggplot(p.ext, aes(y=value, group = factor(reg), color = factor(reg))) +
  geom_boxplot(width = 0.5) +
  xlab('') + ylab('Probability of extinction') +
  theme_classic() +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())

p.neg <- p.neg %>% reshape2::melt() %>% dplyr::rename(sim = Var1, reg = Var2)
c <- ggplot(p.neg, aes(y=value, group = factor(reg), color = factor(reg))) +
  geom_boxplot(width = 0.5) +
  xlab('') + ylab('Probability of negative trend') +
  theme_classic() +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())

```



```{r env projection prep}

version <- '2.2_env_track_'
out_1 <- readRDS(here::here('results', 'best', paste0("out.parallel-", version, "spStable-1.RDS")))
out_2 <- readRDS(here::here('results', 'best', paste0("out.parallel-", version, "spStable-2.RDS")))
out_3 <- readRDS(here::here('results', 'best', paste0("out.parallel-", version, "spStable-3.RDS")))

post <- list(`out_1`, `out_2`, `out_3`) %>% as.mcmc.list()
post <- as.matrix(post)

post_sum <- data.frame(
  med = apply(post, 2, function(x) quantile(x, probs = 0.5, na.rm = T, names = F)),
  lower = apply(post, 2, function(x) quantile(x, probs = 0.025, na.rm = T, names = F)),
  upper = apply(post, 2, function(x) quantile(x, probs = 0.975, na.rm = T, names = F)))
post_sum$variable <- row.names(post_sum)

all_pars <- colnames(post)
eps_pars <- all_pars[which(grepl('eps', all_pars))]

nSims <- 10
nSamples <- dim(post)[1]
nyears.proj <- 100
G_f <- 8
G_m <- 7
nSamp <- 2500
n_r <- 6
nyears.burnin <- 0
n_occasions <- 19

Ntot_post <- post[(nSamples-nSamp+1):nSamples,grepl('Ntot', colnames(post)) & !grepl('_f', colnames(post)) 
                  & !grepl('_m', colnames(post))] %>% 
  reshape2::melt() %>%
  transform(year = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+)\\].*$', '\\1', Var2)))) %>%
  transform(region = as.numeric(gsub('.+\\[([0-9]+), ([0-9]+)\\].*$', '\\2', Var2))) %>%
  transform(Ntot = value) %>% dplyr::select(-c(value, Var2))

phi_post <- post[(nSamples-nSamp+1):nSamples,grepl('.prob', colnames(post))] %>% reshape2::melt() %>%
  transform(year = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+)\\].*$', '\\2',
                                                Var2)))) %>%
  transform(region = as.numeric(gsub('.+\\[([0-9]+), ([0-9]+)\\].*$', '\\1', Var2))) %>%
  transform(variable = sub("\\[.*", "", Var2)) %>%
  transform(variable = gsub('.prob', '', variable))

mu_post <- post[(nSamples-nSamp+1):nSamples,grepl('mu.', colnames(post))] %>% reshape2::melt() 

reg_post <- post[(nSamples-nSamp+1):nSamples,grepl('reg.', colnames(post))] %>% reshape2::melt() %>%
    transform(region = as.numeric(gsub('.+\\[([0-9]+)\\].*$', '\\1', Var2))) %>%
  transform(variable = sub("\\[.*", "", Var2)) 

#get male and female populations; dim = c(age_class 1:8, t 1:27, r 1:6)
N_f_post <- post[(nSamples-nSamp+1):nSamples,grepl('N_f', colnames(post))] %>% reshape2::melt() %>%
  transform(Var2 = as.character(Var2)) %>%
  transform(age = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+), ([0-9]+)\\].*$', '\\1', Var2)))) %>%
  transform(year = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+), ([0-9]+)\\].*$', '\\2', Var2)))) %>%
  transform(region = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+), ([0-9]+)\\].*$', '\\3', Var2))))

N_m_post <- post[(nSamples-nSamp+1):nSamples,grepl('N_m', colnames(post))] %>% reshape2::melt() %>%
  transform(Var2 = as.character(Var2)) %>%
  transform(age = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+), ([0-9]+)\\].*$', '\\1', Var2)))) %>%
  transform(year = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+), ([0-9]+)\\].*$', '\\2', Var2)))) %>%
  transform(region = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+), ([0-9]+)\\].*$', '\\3', Var2))))


#rebuild in array format
N_f <- array(NA, dim = c(nSamp, G_f, (n_occasions+nyears.burnin), n_r))
for (r in 1:n_r) {
  for (a in 1:G_f) {
    for (t in 1:(n_occasions+nyears.burnin)) {
        N_f[,a,t,r] <- N_f_post[N_f_post$age == a & N_f_post$year == t & N_f_post$region == r, 'value']
    }
  }
}

N_m <- array(NA, dim = c(nSamp, G_m, (n_occasions+nyears.burnin), n_r))
for (r in 1:n_r) {
  for (a in 1:G_m) {
    for (t in 1:(n_occasions+nyears.burnin)) {
        N_m[,a,t,r] <- N_m_post[N_m_post$age == a & N_m_post$year == t & N_m_post$region == r, 'value']
    }
  }
}

Ntot_est <- array(NA, dim = c(nSamp, (n_occasions+nyears.burnin), n_r))
for (r in 1:n_r) {
    for (t in 1:(n_occasions+nyears.burnin)) {
        Ntot_est[,t,r] <- Ntot_post[Ntot_post$year == t & Ntot_post$region == r, 'Ntot']
  }
}

eps_post <- post[(nSamples-nSamp+1):nSamples, eps_pars[-c(1:19)]] %>% #not great subsetting
  reshape2::melt() %>%
  transform(region = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+)\\].*$', '\\1', Var2)))) %>%
  transform(year = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+)\\].*$', '\\2', Var2)))) %>%
  transform(variable = ifelse(grepl('epsPB', Var2), 'epsPB', 
                              ifelse(grepl('epsP', Var2), 'epsP',
                                     ifelse(grepl('eps1', Var2), 'eps1',
                                            ifelse(grepl('eps2', Var2), 'eps2', 
                                                   ifelse(grepl('epsB', Var2), 'epsB', 
                                                          ifelse(grepl('eps.psiPB', Var2), 'eps.psiPB', 
                                                                 ifelse(grepl('eps.psiB', Var2), 'eps.psiB', '100'))))))))

npgo_post <- post[(nSamples-nSamp+1):nSamples,grepl('npgo', colnames(post))] %>%
  reshape2::melt() 

sst_post <- post[(nSamples-nSamp+1):nSamples,grepl('sst', colnames(post))] %>%
  reshape2::melt() 

#years to sample
picks <- array(NA, dim = c(nSims, nyears.proj))  
for (n in 1:nSims) {
picks[n,] <- sample(1:(n_occasions-1), nyears.proj, replace = T)
}

#environmental scenarios
npgo_sd_obs <- sd(npgo_dat)
npgo_mean_obs <- mean(npgo_dat)

sst_sd_obs <- sd(sst_dat)
sst_mean_obs <- mean(sst_dat)

# pr <- 0.25
# pr_big <- 0.5

pr <- 0.75
pr_big <- 0.99

#1: mean and sd's equivalent to historical observation
npgo_preds1 <- array(NA, dim = c(nSims, nyears.proj))
sst_preds1 <- array(NA, dim = c(nSims, nyears.proj))
for (n in 1:nSims) {
  npgo_preds1[n,] <- rnorm(nyears.proj, npgo_mean_obs, npgo_sd_obs)
  sst_preds1[n,] <- scale(rnorm(nyears.proj, sst_mean_obs, sst_sd_obs), scale = F)
}

#2: mean same and sd's 25% smaller than historical observation
npgo_preds2 <- array(NA, dim = c(nSims, nyears.proj))
sst_preds2 <- array(NA, dim = c(nSims, nyears.proj))
for (n in 1:nSims) {
  npgo_preds2[n,] <- rnorm(nyears.proj, npgo_mean_obs, npgo_sd_obs-npgo_sd_obs*pr)
  sst_preds2[n,] <- scale(rnorm(nyears.proj, sst_mean_obs, sst_sd_obs-sst_sd_obs*pr), scale = F)
}

#3: mean same and sd's 25% larger than historical observation
npgo_preds3 <- array(NA, dim = c(nSims, nyears.proj))
sst_preds3 <- array(NA, dim = c(nSims, nyears.proj))
for (n in 1:nSims) {
  npgo_preds3[n,] <- rnorm(nyears.proj, npgo_mean_obs, npgo_sd_obs+npgo_sd_obs*pr)
  sst_preds3[n,] <- scale(rnorm(nyears.proj, sst_mean_obs, sst_sd_obs+sst_sd_obs*pr), scale = F)
}

#4: mean lower and sd's 25% smaller than historical observation
npgo_preds4 <- array(NA, dim = c(nSims, nyears.proj))
sst_preds4 <- array(NA, dim = c(nSims, nyears.proj))
for (n in 1:nSims) {
  npgo_preds4[n,] <- rnorm(nyears.proj, npgo_mean_obs-npgo_mean_obs*pr, npgo_sd_obs-npgo_sd_obs*pr)
  sst_preds4[n,] <- scale(rnorm(nyears.proj, sst_mean_obs-sst_mean_obs*pr, sst_sd_obs-sst_sd_obs*pr), scale = F)
}

#5: mean lower and sd's 25% larger than historical observation
npgo_preds5 <- array(NA, dim = c(nSims, nyears.proj))
sst_preds5 <- array(NA, dim = c(nSims, nyears.proj))
for (n in 1:nSims) {
  npgo_preds5[n,] <- rnorm(nyears.proj, npgo_mean_obs-npgo_mean_obs*pr, npgo_sd_obs+npgo_sd_obs*pr)
  sst_preds5[n,] <- scale(rnorm(nyears.proj, sst_mean_obs-sst_mean_obs*pr, sst_sd_obs+sst_sd_obs*pr), scale = F)
}

#6: mean higher and sd's 25% smaller than historical observation
npgo_preds6 <- array(NA, dim = c(nSims, nyears.proj))
sst_preds6 <- array(NA, dim = c(nSims, nyears.proj))
for (n in 1:nSims) {
  npgo_preds6[n,] <- rnorm(nyears.proj, npgo_mean_obs+npgo_mean_obs*pr, npgo_sd_obs-npgo_sd_obs*pr)
  sst_preds6[n,] <- scale(rnorm(nyears.proj, sst_mean_obs+sst_mean_obs*pr, sst_sd_obs-sst_sd_obs*pr), scale = F)
}

#7: mean higher and sd's 25% larger than historical observation
npgo_preds7 <- array(NA, dim = c(nSims, nyears.proj))
sst_preds7 <- array(NA, dim = c(nSims, nyears.proj))
for (n in 1:nSims) {
  npgo_preds7[n,] <- rnorm(nyears.proj, npgo_mean_obs+npgo_mean_obs*pr, npgo_sd_obs+npgo_sd_obs*pr)
  sst_preds7[n,] <- scale(rnorm(nyears.proj, sst_mean_obs+sst_mean_obs*pr, sst_sd_obs+sst_sd_obs*pr), scale = F)
}


#8: lower mean and sd's historical 
npgo_preds8 <- array(NA, dim = c(nSims, nyears.proj))
sst_preds8 <- array(NA, dim = c(nSims, nyears.proj))
for (n in 1:nSims) {
  npgo_preds8[n,] <- rnorm(nyears.proj, npgo_mean_obs-npgo_mean_obs*pr, npgo_sd_obs)
  sst_preds8[n,] <- scale(rnorm(nyears.proj, sst_mean_obs-sst_mean_obs*pr, sst_sd_obs), scale = F)
}

#9: higher mean and sd's historical
npgo_preds9 <- array(NA, dim = c(nSims, nyears.proj))
sst_preds9 <- array(NA, dim = c(nSims, nyears.proj))
for (n in 1:nSims) {
  npgo_preds9[n,] <- rnorm(nyears.proj, npgo_mean_obs+npgo_mean_obs*pr, npgo_sd_obs)
  sst_preds9[n,] <- scale(rnorm(nyears.proj, sst_mean_obs+sst_mean_obs*pr, sst_sd_obs), scale = F)
}

scenarios <- c(1:9)


```

```{r env proj -- npgo and sst scenarios}

Ntot.sim.cov <- lambda.mean.sim.cov <- p.ext.sim.cov <- p.ad.ext.sim.cov <- p.neg.sim.cov <- data.frame()

#storage for sim/region loop
Ntot.sim <- array(NA, dim = c(nSamp, n_occasions+nyears.burnin+nyears.proj, nSims, n_r))
p.ext.sim <- p.ad.ext.sim <- p.neg.sim <- array(NA, dim = c(nSims, n_r))
lambda.mean.sim <- lambda.upper.sim <- lambda.lower.sim <- array(NA, dim = c(nSims, n_r))

t.start <- Sys.time() # start clock for whole process

for (sc in scenarios) {
  for (r in 1:n_r) {
   for (sim in 1:nSims) {

    #temp storage for population model objects; need a row for each of nSamples and columns for each projection year
    N_4B <- N_5B <- N_6B <- N_6NB <- N_BB <- N_BNB <- array(NA, dim = c(nSamp, nyears.proj)) 
    Ntot_f_proj <- Ntot_m_proj <- array(NA, dim = c(nSamp, nyears.proj))
    N_NBNB <- N_NBB <- N_B <- N_NB <- N_A1 <- N_Aplus <- array(NA, dim = c(nSamp, nyears.proj))
    
    #total population size for data period + projections (Ntot) and just projections (Ntot_proj)
    Ntot <- Ntot_f <- Ntot_m <- array(NA, dim = c(nSamp, n_occasions+nyears.burnin+nyears.proj)) 
    Ntot_proj <- array(NA, dim = c(nSamp, nyears.proj))
    N_f_proj <- array(NA, dim = c(nSamp, G_f, nyears.proj))
    N_m_proj <- array(NA, dim = c(nSamp, G_m, nyears.proj))
    
    #demographic rates
    phiP.prob.proj <- phi1.prob.proj <- phi2.prob.proj <- array(NA, dim = c(nSamp, nyears.proj-1))
    phi3.prob.proj <- phi4.prob.proj <- phi5.prob.proj <- array(NA, dim = c(nSamp, nyears.proj-1))
    phiB.prob.proj <- phiNB.prob.proj <- array(NA, dim = c(nSamp, nyears.proj-1))
    
    psi3.prob.proj <- psi4.prob.proj <- psi5.prob.proj <- array(NA, dim = c(nSamp, nyears.proj-1))
    psiB.prob.proj <- psiNB.prob.proj <- array(NA, dim = c(nSamp, nyears.proj-1))

    phiPM.prob.proj <- phi1M.prob.proj <- phi2M.prob.proj <- array(NA, dim = c(nSamp, nyears.proj-1))
    phi3M.prob.proj <- phi4M.prob.proj <- phi5M.prob.proj <- array(NA, dim = c(nSamp, nyears.proj-1))
    phiBM.prob.proj <- array(NA, dim = c(nSamp, nyears.proj-1))

    #grab last year from data period to initialize
    N_B[,1] <- N_f[,7,dim(N_f)[3],r]
    N_NB[,1] <- N_f[,8,dim(N_f)[3],r]
    N_A1[,1] <- N_m[,6,dim(N_f)[3],r]
    N_Aplus[,1] <- N_m[,7,dim(N_f)[3],r]
    
    Ntot[,1:(n_occasions+nyears.burnin)] <- Ntot_est[,1:(n_occasions+nyears.burnin),r] #fills up to Ntot[,26]
    Ntot_proj[,1] <- Ntot_est[,dim(Ntot_est)[2],r] #grab 19th year
    N_f_proj[,,1] <- N_f[,,dim(N_f)[3],r] # populate with last year from data period
    N_m_proj[,,1] <- N_m[,,dim(N_m)[3],r]

   ## projection; sigma == sd, sigma^2 == variance, 1/variance == precision
    for (t in 1:(nyears.proj-1)) {
 
      if (sc == scenarios[1]) {npgo <- npgo_preds1; sst <- sst_preds1}
      if (sc == scenarios[2]) {npgo <- npgo_preds2; sst <- sst_preds2}
      if (sc == scenarios[3]) {npgo <- npgo_preds3; sst <- sst_preds3}
      if (sc == scenarios[4]) {npgo <- npgo_preds4; sst <- sst_preds4}
      if (sc == scenarios[5]) {npgo <- npgo_preds5; sst <- sst_preds5}
      if (sc == scenarios[6]) {npgo <- npgo_preds6; sst <- sst_preds6}
      if (sc == scenarios[7]) {npgo <- npgo_preds7; sst <- sst_preds7}
      if (sc == scenarios[8]) {npgo <- npgo_preds8; sst <- sst_preds8}
        
    year_pick <- picks[sim,t]
    
    #pups
    mu.temp <- mu_post %>% filter(Var2 == 'mu.P')
    eps.temp <- eps_post %>% filter(variable == 'epsP' & year == year_pick & region == r)
    reg.temp <- reg_post %>% filter(variable == 'b.regP' & region == r)
    npgo.temp <- npgo_post %>% filter(Var2 == 'b.npgoP')
    sst.temp <- sst_post %>% filter(Var2 == 'b.sstP')
    phiP.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + eps.temp[,'value'] + reg.temp[,'value'] +
                              npgo.temp[,'value']*npgo[sim,t] + sst.temp[,'value']*sst[sim,t])))
    
    mu.temp <- mu_post %>% filter(Var2 == 'mu.PM')
    eps.temp <- eps_post %>% filter(variable == 'epsP' & year == year_pick & region == r)
    reg.temp <- reg_post %>% filter(variable == 'b.regP' & region == r)
    npgo.temp <- npgo_post %>% filter(Var2 == 'b.npgoP')
    sst.temp <- sst_post %>% filter(Var2 == 'b.sstP')
    phiPM.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + eps.temp[,'value'] + reg.temp[,'value'] +
                                 npgo.temp[,'value']*npgo[sim,t] + sst.temp[,'value']*sst[sim,t])))
    #yearlings
    mu.temp <- mu_post %>% filter(Var2 == 'mu.1')
    eps.temp <- eps_post %>% filter(variable == 'eps1' & year == year_pick & region == r)
    reg.temp <- reg_post %>% filter(variable == 'b.reg1' & region == r)
    npgo.temp <- npgo_post %>% filter(Var2 == 'b.npgo1')
    sst.temp <- sst_post %>% filter(Var2 == 'b.sst1')
    phi1.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + eps.temp[,'value'] + reg.temp[,'value'] +
                              npgo.temp[,'value']*npgo[sim,t] + sst.temp[,'value']*sst[sim,t])))
    
    mu.temp <- mu_post %>% filter(Var2 == 'mu.1M')
    eps.temp <- eps_post %>% filter(variable == 'eps1' & year == year_pick & region == r)
    reg.temp <- reg_post %>% filter(variable == 'b.reg1' & region == r)
    npgo.temp <- npgo_post %>% filter(Var2 == 'b.npgo1')
    sst.temp <- sst_post %>% filter(Var2 == 'b.sst1')
    phi1M.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + eps.temp[,'value'] + reg.temp[,'value'] +
                             npgo.temp[,'value']*npgo[sim,t] + sst.temp[,'value']*sst[sim,t])))
    #year2
    mu.temp <- mu_post %>% filter(Var2 == 'mu.2')
    eps.temp <- eps_post %>% filter(variable == 'eps2' & year == year_pick & region == r)
    reg.temp <- reg_post %>% filter(variable == 'b.reg2' & region == r)
    npgo.temp <- npgo_post %>% filter(Var2 == 'b.npgo1')
    sst.temp <- sst_post %>% filter(Var2 == 'b.sst1')
    phi2.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + eps.temp[,'value'] + reg.temp[,'value'] +
                             npgo.temp[,'value']*npgo[sim,t] + sst.temp[,'value']*sst[sim,t])))
    
    mu.temp <- mu_post %>% filter(Var2 == 'mu.2M')
    eps.temp <- eps_post %>% filter(variable == 'eps2' & year == year_pick & region == r)
    reg.temp <- reg_post %>% filter(variable == 'b.reg2' & region == r)
    npgo.temp <- npgo_post %>% filter(Var2 == 'b.npgo1')
    sst.temp <- sst_post %>% filter(Var2 == 'b.sst1')
    phi2M.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + eps.temp[,'value'] + reg.temp[,'value'] +
                            npgo.temp[,'value']*npgo[sim,t] + sst.temp[,'value']*sst[sim,t])))
    
    #NB
    mu.temp <- mu_post %>% filter(Var2 == 'mu.NB')
    phiNB.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'])))
    
    #psi3
    mu.temp <- mu_post %>% filter(Var2 == 'mu.psi3')
    reg.temp <- reg_post %>% filter(variable == 'b.reg.psi3' & region == r)
    npgo.temp <- npgo_post %>% filter(Var2 == 'b.npgo.psi')
    sst.temp <- sst_post %>% filter(Var2 == 'b.sst.psi')
      
    psi3.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + reg.temp[,'value'] +
                                npgo.temp[,'value']*npgo[sim,t] + sst.temp[,'value']*sst[sim,t])))
    
    #psi5
    mu.temp <- mu_post %>% filter(Var2 == 'mu.psi5')
    reg.temp <- reg_post %>% filter(variable == 'b.reg.psi5' & region == r)
    npgo.temp <- npgo_post %>% filter(Var2 == 'b.npgo.psi')
    sst.temp <- sst_post %>% filter(Var2 == 'b.sst.psi')
      
    psi5.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + reg.temp[,'value'] +
                               npgo.temp[,'value']*npgo[sim,t] + sst.temp[,'value']*sst[sim,t])))
    
    #psiNB
    mu.temp <- mu_post %>% filter(Var2 == 'mu.psiNB')
    reg.temp <- reg_post %>% filter(variable == 'b.reg.psiNB' & region == r)
    psiNB.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + reg.temp[,'value'])))
    
    if (r < 5) {reg = 1} 
    if (r > 4) {reg = 2}
    #3-5; east-west regional effect, singular eastern random effect
    mu.temp <- mu_post %>% filter(Var2 == 'mu.3')
    eps.temp <- eps_post %>% filter(variable == 'epsPB' & year == year_pick & region == reg)
    reg.temp <- reg_post %>% filter(variable == 'b.regPB' & region == reg)
    phi3.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + eps.temp[,'value'] + reg.temp[,'value'])))
    
    mu.temp <- mu_post %>% filter(Var2 == 'mu.3M')
    eps.temp <- eps_post %>% filter(variable == 'epsPB' & year == year_pick & region == reg)
    reg.temp <- reg_post %>% filter(variable == 'b.regPB' & region == reg)
    phi3M.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + eps.temp[,'value'] + reg.temp[,'value'])))
    
    #4
    mu.temp <- mu_post %>% filter(Var2 == 'mu.4')
    eps.temp <- eps_post %>% filter(variable == 'epsPB' & year == year_pick & region == reg)
    reg.temp <- reg_post %>% filter(variable == 'b.regPB' & region == reg)
    phi4.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + eps.temp[,'value'] + reg.temp[,'value'])))
    
    mu.temp <- mu_post %>% filter(Var2 == 'mu.4M')
    eps.temp <- eps_post %>% filter(variable == 'epsPB' & year == year_pick & region == reg)
    reg.temp <- reg_post %>% filter(variable == 'b.regPB' & region == reg)
    phi4M.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + eps.temp[,'value'] + reg.temp[,'value'])))
    
    #5
    mu.temp <- mu_post %>% filter(Var2 == 'mu.5')
    eps.temp <- eps_post %>% filter(variable == 'epsPB' & year == year_pick & region == reg)
    reg.temp <- reg_post %>% filter(variable == 'b.regPB' & region == reg)
    phi5.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + eps.temp[,'value'] + reg.temp[,'value'])))
    
    mu.temp <- mu_post %>% filter(Var2 == 'mu.5M')
    eps.temp <- eps_post %>% filter(variable == 'epsPB' & year == year_pick & region == reg)
    reg.temp <- reg_post %>% filter(variable == 'b.regPB' & region == reg)
    phi5M.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + eps.temp[,'value'] + reg.temp[,'value'])))
    
    #B & BM
    mu.temp <- mu_post %>% filter(Var2 == 'mu.B')
    eps.temp <- eps_post %>% filter(variable == 'epsB' & year == year_pick & region == r)
    reg.temp <- reg_post %>% filter(variable == 'b.regB' & region == reg)
    npgo.temp <- npgo_post %>% filter(Var2 == 'b.npgoB')
    sst.temp <- sst_post %>% filter(Var2 == 'b.sstB')
    phiB.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + eps.temp[,'value'] + reg.temp[,'value']
                                   + npgo.temp[,'value']*npgo[sim,t] + sst.temp[,'value']*sst[sim,t])))
    
    mu.temp <- mu_post %>% filter(Var2 == 'mu.BM')
    eps.temp <- eps_post %>% filter(variable == 'epsB' & year == year_pick & region == reg)
    reg.temp <- reg_post %>% filter(variable == 'b.regB' & region == reg)
    phiBM.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + eps.temp[,'value'] + reg.temp[,'value'])))
      
    #psi4
    mu.temp <- mu_post %>% filter(Var2 == 'mu.psi4')
    eps.temp <- eps_post %>% filter(variable == 'eps.psiPB' & year == year_pick & region == reg)
    reg.temp <- reg_post %>% filter(variable == 'b.reg.psi4' & region == r)
    npgo.temp <- npgo_post %>% filter(Var2 == 'b.npgo.psi')
    sst.temp <- sst_post %>% filter(Var2 == 'b.sst.psi')
      
    psi4.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + eps.temp[,'value'] + reg.temp[,'value'] +
                                    npgo.temp[,'value']*npgo[sim,t] + sst.temp[,'value']*sst[sim,t])))

    #psiB
    mu.temp <- mu_post %>% filter(Var2 == 'mu.psiB')
    eps.temp <- eps_post %>% filter(variable == 'eps.psiB' & year == year_pick & region == reg)
    reg.temp <- reg_post %>% filter(variable == 'b.reg.psiB' & region == r)
    npgo.temp <- npgo_post %>% filter(Var2 == 'b.npgo.psi')
    sst.temp <- sst_post %>% filter(Var2 == 'b.sst.psi')
      
    psiB.prob.proj[,t] <- 1/(1+exp(-(mu.temp[, 'value'] + eps.temp[,'value'] + reg.temp[,'value'] +
                                    npgo.temp[,'value']*npgo[sim,t] + sst.temp[,'value']*sst[sim,t])))

    ###FEMALES
    N_f_proj[,2,t+1] <- rbinom(nSamp, N_f_proj[,1,t], phiP.prob.proj[,t]) #yearlings
    N_f_proj[,3,t+1] <- rbinom(nSamp, N_f_proj[,2,t], phi1.prob.proj[,t]) #2yos
    N_f_proj[,4,t+1] <- rbinom(nSamp, N_f_proj[,3,t], phi2.prob.proj[,t]) #3yos
    N_f_proj[,5,t+1] <- rbinom(nSamp, N_f_proj[,4,t], phi3.prob.proj[,t]*(1-psi3.prob.proj[,t])) #4yo PB
    N_f_proj[,6,t+1] <- rbinom(nSamp, N_f_proj[,5,t], phi4.prob.proj[,t]*(1-psi4.prob.proj[,t])) #5yo PB 

    N_4B[,t+1] <- rbinom(nSamp, N_f_proj[,4,t], phi3.prob.proj[,t]*psi3.prob.proj[,t]) #4yo breeders 
    N_5B[,t+1] <- rbinom(nSamp, N_f_proj[,5,t], phi4.prob.proj[,t]*psi4.prob.proj[,t]) #5yo first-B  

    N_6B[,t+1] <- rbinom(nSamp, N_f_proj[,6,t], phi5.prob.proj[,t]*psi5.prob.proj[,t]) #6yo first-B 
    N_6NB[,t+1] <- rbinom(nSamp, N_f_proj[,6,t], phi5.prob.proj[,t]*(1-psi5.prob.proj[,t])) #6yo NB that was PB at 5 

    ## Plus groups
    #breeders
    N_BB[,t+1] <- rbinom(nSamp, N_B[,t], phiB.prob.proj[,t]*psiB.prob.proj[,t]) # plus grp B given B (#6)
    N_BNB[,t+1] <- rbinom(nSamp, N_NB[,t], phiNB.prob.proj[,t]*psiNB.prob.proj[,t]) # plus grp B given NB (#8)

    #non breeders
    N_NBNB[,t+1] <- rbinom(nSamp, N_NB[,t], phiNB.prob.proj[,t]*(1-psiNB.prob.proj[,t])) # plus grp NB given NB (#9)
    N_NBB[,t+1] <- rbinom(nSamp, N_B[,t], phiB.prob.proj[,t]*(1-psiB.prob.proj[,t])) # plus grp NB given B (#7)

    #total breeders and non-breeders
    N_B[,t+1] <- N_4B[,t+1]+N_5B[,t+1]+N_6B[,t+1]+N_BB[,t+1]+N_BNB[,t+1] # total breeders
    N_NB[,t+1] <- N_6NB[,t+1]+N_NBB[,t+1]+N_NBNB[,t+1] # total breeders

    N_f_proj[,7,t+1] <- N_B[,t+1]   #B
    N_f_proj[,8,t+1] <- N_NB[,t+1]  #NB
    N_f_proj[,1,t+1] <- round(N_B[,t+1]/2) #pups 

     Ntot_f_proj[,t+1] <- rowSums(N_f_proj[1:nSamp,1:8,t+1])

    ###MALES
    N_m_proj[,1,t+1] <- round(N_B[,t+1]/2) #pups
    N_m_proj[,2,t+1] <- rbinom(nSamp, N_m_proj[,1,t], phiPM.prob.proj[,t]) #yearlings
    N_m_proj[,3,t+1] <- rbinom(nSamp, N_m_proj[,2,t], phi1M.prob.proj[,t]) #2yos
    N_m_proj[,4,t+1] <- rbinom(nSamp, N_m_proj[,3,t], phi2M.prob.proj[,t]) #3yos
    N_m_proj[,5,t+1] <- rbinom(nSamp, N_m_proj[,4,t], phi3M.prob.proj[,t]) #4yos
    N_m_proj[,6,t+1] <- rbinom(nSamp, N_m_proj[,5,t], phi4M.prob.proj[,t]) #5yos
    N_A1[,t+1] <- rbinom(nSamp, N_m_proj[,6,t], phi5M.prob.proj[,t]) #new adults from 5yos
    N_Aplus[,t+1] <- rbinom(nSamp, N_m_proj[,7,t], phiBM.prob.proj[,t]) #repeat adults 7+

    N_m_proj[,7,t+1] <- N_A1[,t+1] + N_Aplus[,t+1]

    Ntot_m_proj[,t+1] <- rowSums(N_m_proj[1:nSamp,1:7,t+1])
    Ntot_proj[,t+1] <- Ntot_f_proj[,t+1] + Ntot_m_proj[,t+1]

  } #t

#fill space in Ntot with Ntot_proj projection years, essentially bind_cols()
Ntot[,((n_occasions+nyears.burnin+1):(n_occasions+nyears.burnin+nyears.proj))] <- Ntot_proj[,]

###### summarize objects over mcmc samples

#growth rate over the whole study period
lambda.yr.mean <- lambda.yr.lower <- lambda.yr.upper <- numeric(length = length(2:(n_occasions+nyears.burnin+nyears.proj)))
for (t in 2:(n_occasions+nyears.burnin+nyears.proj)) {
  #mean and quantiles per year across mcmc samples; leave na.rm for zero size pops in mcmc samples
  lambda.yr.mean[t] <- mean(Ntot[,t]/(Ntot[,t-1]), na.rm = T)
  lambda.yr.lower[t] <- quantile(Ntot[,t]/(Ntot[,t-1]), probs = 0.025, na.rm = T, names = F)
  lambda.yr.upper[t] <- quantile(Ntot[,t]/(Ntot[,t-1]), probs = 0.975, na.rm = T, names = F)
} #t lambda

#### derive and store values for each simulation

#geometric mean, and quantiles(?)
lambda.mean.sim[sim,r] <- exp(mean(log(lambda.yr.mean[which(lambda.yr.mean>0)])))
lambda.lower.sim[sim,r] <- exp(mean(log(lambda.yr.lower[which(lambda.yr.lower>0)])))
lambda.upper.sim[sim,r] <- exp(mean(log(lambda.yr.upper[which(lambda.yr.upper>0)])))

#prob of having less than 2 individuals and less than 1 breeding age female at end
p.ext.sim[sim,r] <- mean(Ntot[,(n_occasions+nyears.burnin+nyears.proj)]<2)
p.ad.ext.sim[sim,r] <- mean(N_f_proj[,7,nyears.proj]<1)

#probability that have fewer individuals at end than start
p.neg.sim[sim,r] <- mean(Ntot[,(n_occasions+nyears.burnin+nyears.proj)] < Ntot[,1])

#population size at end of projection
# end.size.sim[sim,1:3] <- quantile(Ntot[,(nyears.gap+nyears.ch+proj)], 
#                                 probs = c(0.025, 0.5, 0.975), names = F)

#Ntot
Ntot.sim[1:nSamp,,sim,r] <- as.matrix(Ntot)

} #sim 
} #region
  
colnames(p.ext.sim) <- c("C.GULF", "E.ALEU", "E.GULF", "W.GULF", "C.ALEU", "W.ALEU")
colnames(lambda.mean.sim) <- c("C.GULF", "E.ALEU", "E.GULF", "W.GULF", "C.ALEU", "W.ALEU")
colnames(p.ad.ext.sim) <- c("C.GULF", "E.ALEU", "E.GULF", "W.GULF", "C.ALEU", "W.ALEU")
colnames(p.neg.sim) <- c("C.GULF", "E.ALEU", "E.GULF", "W.GULF", "C.ALEU", "W.ALEU")

p.ext.sim.all <- p.ext.sim %>%
  reshape2::melt() %>%
  transform(sc = sc)

lambda.mean.sim.all <- lambda.mean.sim %>%
  reshape2::melt() %>%
  transform(sc = sc)

p.ad.ext.sim.all <- p.ad.ext.sim %>%
  reshape2::melt() %>%
  transform(sc = sc)

p.neg.sim.all <- p.neg.sim %>%
  reshape2::melt() %>%
  transform(sc = sc)

#want mean and CI for each time step and region
Ntot_mean <- apply(Ntot.sim, c(4,2), median)
Ntot_q2.5 <- apply(Ntot.sim, c(4,2), function(x) quantile(x,0.025, na.rm = T))
Ntot_q97.5 <- apply(Ntot.sim, c(4,2), function(x) quantile(x,0.975))

#Ntot figures
N_mean_long_sim <- Ntot_mean %>%
  reshape2::melt(value.name = 'mean') %>%
  dplyr::rename(reg = Var1, year = Var2) %>%
  transform(sc = sc)

N_low_long_sim <- Ntot_q2.5 %>%
  reshape2::melt(value.name = 'lower') %>%
  dplyr::rename(reg = Var1, year = Var2) %>%
  transform(sc = sc)

N_high_long_sim <- Ntot_q97.5 %>%
  reshape2::melt(value.name = 'upper') %>%
  dplyr::rename(reg = Var1, year = Var2) %>%
  transform(sc = sc)

N_vals_sim <- N_mean_long_sim %>%
  merge(N_low_long_sim, by = c('reg', 'year', 'sc')) %>%
  merge(N_high_long_sim, by = c('reg', 'year', 'sc')) %>%
  arrange(reg, year) %>%
  transform(reg = factor(reg, levels = 1:6,
                            labels = c("C.GULF", "E.ALEU", "E.GULF",
                                       "W.GULF", "C.ALEU", "W.ALEU")))

Ntot.sim.cov <- bind_rows(Ntot.sim.cov, N_vals_sim)
lambda.mean.sim.cov <- bind_rows(lambda.mean.sim.cov, lambda.mean.sim.all)
p.ext.sim.cov <- bind_rows(p.ext.sim.cov, p.ext.sim.all)
p.ad.ext.sim.cov <- bind_rows(p.ad.ext.sim.cov, p.ad.ext.sim.all)
p.neg.sim.cov <- bind_rows(p.neg.sim.cov, p.neg.sim.all)
  
} #scenario

t.end <- Sys.time() # end clock
(runTime <- t.end - t.start)

## save objects
tag <- 'extreme_long'
saveRDS(Ntot.sim.cov, file = here::here('results', 'projections', paste0('Ntot_cov9', tag, '.rds')))
saveRDS(lambda.mean.sim.cov, file = here::here('results', 'projections', paste0('lambda_cov9', tag, '.rds')))
saveRDS(p.ext.sim.cov, file = here::here('results', 'projections', paste0('p.ext_cov9', tag, '.rds')))
saveRDS(p.ad.ext.sim.cov, file = here::here('results', 'projections', paste0('p.ad.ext_cov9', tag, '.rds')))
saveRDS(p.neg.sim.cov, file = here::here('results', 'projections', paste0('p.neg_cov9', tag, '.rds')))

# ggplot(Ntot.sim.cov,
#        aes(year, mean, group = factor(sc), col = factor(sc))) +
#   geom_line() +
#   geom_ribbon(aes(year, ymin = lower, ymax = upper, col = factor(sc),
#                   fill = factor(sc), alpha = 0.5), 
#               show.legend = F) +
#   xlab('') + ylab('Population size') +
#   facet_wrap(~reg, scales = 'free') +
#   plot_theme(legend.position = 'top') +
#     scale_x_continuous(limits = c(1,n_occasions+nyears.burnin+nyears.proj),
#                      breaks = seq(2, n_occasions+nyears.burnin+nyears.proj, by = 10),
#                      labels = seq(2000, (2000+n_occasions+nyears.burnin+nyears.proj), by = 10)) +
#   scale_color_manual(values = rainbow2, name = 'Scenario') +
#   scale_fill_manual(values = rainbow2)
#   scale_color_manual(values = rainbow2[-c(1)], name = 'Scenario') +
#   scale_fill_manual(values = rainbow2[-c(1)])

#####posterior summaries; boxplots of posterior means
lambda_env_plot <- ggplot(lambda.mean.sim.cov, aes(y=value, x = sc, group = sc)) +
  geom_boxplot(width = 0.5, aes(x = sc, color = sc), 
               position = position_dodge(width = 0.5)) +
  xlab('') + ylab('Population growth rate') +
  plot_theme(legend.position = 'none',
             panel.border = element_rect(fill = NA)) +
  facet_wrap(~Var2) +
  scale_color_manual(values = rainbow2[-c(1,4)], name = '') +
  scale_fill_manual(values = rainbow2[-c(1,4)], name = '') 

# p.ext.sim[1:nSamp, 1:n_r]
p.ext <- p.ext.sim %>% reshape2::melt() %>% dplyr::rename(sim = Var1, reg = Var2)
b <- ggplot(p.ext.sim.cov, aes(y=value, group = factor(reg), color = factor(reg))) +
  geom_boxplot(width = 0.5) +
  xlab('') + ylab('Probability of negative trend') +
  theme_classic() +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())

```

